import {characters,poses,objects,finds,missions,categories} from './catalog.js';
import {load,KEY,dateKey,enabled,completed,chestGoal,chestReady,familyTotal,next,start,help,advance,finish,openChest,skillSummary,friendFeed} from './state.js';
import {guidanceFor,supportSuggestion} from './guidance.js';
import {createNarrator} from './narration.js';
import {readState,saveState,exportProgress,importProgress} from './persistence.js';
import {SceneManager} from './core/scene.js';
import {normalizeWorld,interactWorld,discoverStar,chapters} from './core/world-state.js';
let scene;
const boot=readState(localStorage);let S=boot.state;
const app=document.querySelector('#app'),modal=document.querySelector('#modal');
const ui={screen:S.activeMission?'mission':'home',worldTab:'items',parentTab:'today',modal:null,helpLevel:0,reward:null,find:null,parentUnlocked:false,pin:'',attempts:0,lockedUntil:0,photo:null,zoom:1,x:50,y:50};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pet=(id=S.child.character,pose='idle',cls='')=>{const row=Math.max(0,poses.indexOf(pose)),top=[0,157,313,463,615,768,892][row],height=[156,156,153,152,153,127,157][row];return `<span class="pet ${cls}" role="img" aria-label="${esc(characters.find(c=>c[0]===id)?.[1]||'Моки')}" style="aspect-ratio:299.8 / ${height};background-size:500% ${1049/height*100}%;background-position:${[2.1,25,50,73.7,97.9][Math.max(0,characters.findIndex(c=>c[0]===id))]}% ${top/(1049-height)*100}%"></span>`};
const obj=(id,cls='')=>{const n=objects.indexOf(id);return `<span class="object ${cls}" aria-hidden="true" style="background-position:${(n%4)*100/3}% ${Math.floor(n/4)*100/3}%"></span>`};
const heroArt=(pose='idle')=>pet(S.child.character,pose)+(S.child.accessory&&pose!=='sleeping'?`<span class="accessory ${S.child.accessory}">${obj(S.child.accessory)}</span>`:'');
const worlds=[['forest','Лес','Лесная хижина'],['space','Космос','Звёздная станция'],['island','Остров','Островной дом'],['town','Город','Солнечный городок']];
const roomBg=()=>`<div class="room-bg theme-${worlds.some(w=>w[0]===S.child.theme)?S.child.theme:'forest'}"></div>`;
const worldsGrid=()=>`<div class="world-choices">${worlds.map(([id,title,desc])=>`<button class="world-choice ${S.child.theme===id?'selected':''}" data-action="theme" data-id="${id}" aria-pressed="${S.child.theme===id}"><span class="world-thumb theme-${id}"></span><b>${title}</b><small>${desc}</small></button>`).join('')}</div>`;
const name=()=>characters.find(c=>c[0]===S.child.character)[1];
const avatar=(id='child',family=false,cls='')=>{const m=S.family.members.find(m=>m.id===id);return `<span class="avatar ${cls}">${id==='child'&&S.child.portrait&&(!family||S.settings.photoFamily)?`<img src="${S.child.portrait}" alt="Портрет ${esc(S.child.name)}">`:pet(id==='child'?S.child.character:m?.character||'tobi')}</span>`};
const button=(text,action,cls='purple',attrs='')=>`<button class="btn ${cls}" data-action="${action}" ${attrs}>${text}</button>`;
const round=(text,action,label)=>`<button class="round" data-action="${action}" aria-label="${label}">${text}</button>`;
const meter=(v,max=100,cls='')=>`<div class="meter ${cls}" role="progressbar" aria-valuenow="${Math.min(v,max)}" aria-valuemin="0" aria-valuemax="${max}"><i style="width:${Math.max(0,Math.min(100,v/max*100))}%"></i></div>`;
const pageHead=(title,subtitle='',action='home')=>`<header class="page-head">${round('‹',action,'Назад')}<div><h1>${title}</h1>${subtitle?`<p>${subtitle}</p>`:''}</div></header>`;
let storageWarning=false,toastTimer;
function save(){const ok=saveState(localStorage,S);storageWarning=!ok;if(!ok)toast('Не удалось сохранить. Оставь игру открытой и освободи место на устройстве.');return ok}
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('on');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('on'),4000)}
function feedback(kind='tap'){scene?.gesture();scene?.sound(kind==='step'?'mission.step.complete':kind==='reward'?'mission.complete':'ui.tap.soft');if(S.settings.haptics&&navigator.vibrate)navigator.vibrate(kind==='reward'?[18,45,18]:8);}
function dayCheck(){if(S.day.date!==dateKey()){S.day={date:dateKey(),completed:{},chestOpened:false};save()}}
function render(){dayCheck();document.documentElement.dataset.calm=S.settings.calm?'true':'false';app.innerHTML=!S.onboarded?onboard():screen();document.documentElement.style.overflow=ui.modal?'hidden':'';drawModal();scene?.bind(S,ui);if(storageWarning)toast('Прогресс пока не сохранён на устройстве.');}
function screen(){if(ui.screen==='practice')return practice();if(ui.screen==='parent'&&!ui.parentUnlocked)ui.screen='home';return ({home:home,world:world,family:family,parent:parent,mission:mission,reward:reward,chest:chest,find:findScreen,effort:effort}[ui.screen]||home)()}
function go(screen){narrator.stop();ui.screen=screen;ui.modal=null;ui.helpLevel=0;if(screen!=='parent')ui.parentUnlocked=false;render();window.scrollTo({top:0,behavior:'instant'})}
function showModal(type){narrator.stop();ui.modal=type;scene?.pause(true);drawModal();document.documentElement.style.overflow='hidden';requestAnimationFrame(()=>modal.querySelector('button,input')?.focus())}
function closeModal(){narrator.stop();ui.modal=null;ui.pin='';ui.helpLevel=0;drawModal();document.documentElement.style.overflow='';scene?.bind(S,ui);}
const voiceIcon='<img src="./assets/controls/volume.svg" alt="" width="26" height="26">';
const narrator=createNarrator({synth:window.speechSynthesis,Utterance:window.SpeechSynthesisUtterance,onStatus:status=>{scene?.audio.mute(status==='speaking'||!!ui.modal||document.hidden);document.documentElement.dataset.speaking=status;document.querySelectorAll('[data-action="listen"]').forEach(el=>el.setAttribute('aria-pressed',String(status==='speaking')));if(status==='unavailable')toast('На устройстве нет русского голоса. Картинки помогут, а взрослый может прочитать шаг.');}});
const listenButton=(label='Послушать')=>`<button class="listen-control" data-action="listen" aria-label="${label}" aria-pressed="false">${voiceIcon}<span>Слушать</span></button>`;
function narrationText(){const m=missions.find(m=>m.id===S.activeMission?.id);if(ui.modal==='help'&&m)return ui.helpLevel===1?m.steps[S.activeMission.step].hint:ui.helpLevel===2?m.steps[S.activeMission.step].text:ui.helpLevel===3?'Позови взрослого. Сделайте этот шаг вместе.':'Нужна помощь? Можно получить намёк, посмотреть пример или сделать вместе со взрослым.';if(!S.onboarded)return ['Привет! Начни вместе со взрослым.','','','','','Теперь можно передать телефон ребёнку.','Выбери своего друга. Нажми на того, кто тебе нравится.','Выбери дом для себя и друга.','Сначала немного поиграем. Нажми зелёную кнопку.'][S.onboarding.step]||'Выберите удобный вариант.';if(ui.screen==='practice')return ui.practiceStep?'Получилось! Когда сделаешь настоящее дело, нажми зелёную галочку.':'Привет! Потрогай своего героя.';if(ui.screen==='mission'&&m)return S.activeMission.phase==='effort'?'Как тебе было? Легко, нормально или сложно? Любой ответ подходит.':m.steps[S.activeMission.step].text;if(ui.screen==='reward')return 'Получилось! Сердечки за твоё настоящее дело. Теперь можно отдохнуть.';if(ui.screen==='chest')return chestReady(S)?'Нажми на сундук. Внутри новая находка.':'В сундуке будет находка после твоих миссий.';if(ui.screen==='find')return ui.find?.[2]||'Новая находка для твоего мира.';if(ui.screen==='world')return 'Это твой дом. Нажимай на вещи, чтобы играть с ними.';if(ui.screen==='family')return 'Это твоя команда. Каждое дело помогает всем вместе.';const n=next(S);return n?`Привет! ${S.activeMission?'Продолжим?':'Наше следующее дело.'} ${n.title}. Нажми большую жёлтую кнопку.`:'На сегодня всё. Можно поиграть с героем или отдохнуть.';}
function narrate(){if(S.settings.voice)narrator.say(narrationText());}
function stepArt(id,step,cls=''){const g=guidanceFor(id,step);if(!g)return '';return `<span class="instruction-art ${cls}" role="img" aria-label="${esc(missions.find(m=>m.id===id).steps[step].text)}" style="background-image:url('./assets/instructions-${g.sheet}.webp');aspect-ratio:362 / ${g.height};background-size:300% ${1448/g.height*100}%;background-position:${step*50}% ${g.top/(1448-g.height)*100}%"></span>`;}
function routePips(){const list=enabled(S).slice(0,5);return `<div class="route-pips" aria-label="Сегодня готово ${completed(S)} из ${enabled(S).length}">${list.map(m=>`<span class="route-stop ${S.day.completed[m.id]?'done':''}" aria-label="${esc(m.title)}${S.day.completed[m.id]?', готово':''}">${obj(m.art)}${S.day.completed[m.id]?'<b aria-hidden="true">✓</b>':''}</span>`).join('')}<span class="route-destination">${obj('chest')}</span></div>`;}
function practice(){return `<section class="practice-page">${roomBg()}<header class="practice-top">${round('‹','home','Вернуться домой')}${listenButton()}</header><div class="practice-bubble"><h1>${ui.practiceStep?'Вот так!':'Привет, друг!'}</h1><p>${ui.practiceStep?'Сделал дело — нажми галочку.':'Потрогай меня'}</p></div><button class="practice-pet" data-action="practice-pet" aria-label="Потрогать героя"><span class="actor-host">${heroArt(ui.practiceStep?'happy':'idle')}</span><span class="touch-ring" aria-hidden="true"></span></button>${ui.practiceStep?button('<span class="control-check" aria-hidden="true">✓</span> Попробовать','practice-done','primary'):button('К игре →','practice-done','text')}<p class="practice-note">Знакомимся с кнопками. HP — за настоящие дела.</p></section>`;}
function home(){const m=next(S),night=new Date().getHours()>=21||new Date().getHours()<6,ready=chestReady(S),count=completed(S);let speech=ready?'Смотри, наш сундук открылся!':m?S.activeMission?'Продолжим?':'У меня есть идея!':'Все дела готовы. Побудем дома?';if(night&&!m)speech='Тихий вечер. Можно отдыхать.';if(!enabled(S).length)speech='Позовём взрослого выбрать первое дело?';return `<section class="home ${night?'night':''}">${roomBg()}<header class="home-header">${avatar()}<div class="name"><b>Привет, ${esc(S.child.name)}!</b><small>Твой друг уже ждёт</small></div><div class="pill" style="color:#513c42"><span class="heart">♥</span>${S.child.hp}</div>${round('⚙','parent','Для взрослого')}</header>${routePips()}<div class="hero-stage">${homeProps()}<div class="speech" id="speech"><span>${speech}</span>${listenButton()}</div><button class="hero-button" data-action="pet" aria-label="Погладить ${name()}">${heroArt(night&&!m?'sleeping':'idle')}</button></div><button class="mission-banner" data-action="${ready?'chest':m?'start':enabled(S).length?'world':'parent'}" ${m?`data-id="${m.id}"`:''}>${obj(ready?'chest':m?.art||'plant')}<span class="copy"><small>${ready?'Три шага к новой находке':m?S.activeMission?'Продолжим с твоего шага':`Маленькое дело · +${m.hp} HP`:'На сегодня всё'}</small><b>${ready?'Открыть сундук':m?esc(m.title):enabled(S).length?'Заглянуть в мой мир':'Выбрать миссии со взрослым'}</b></span><span class="arrow" aria-hidden="true">▶</span></button><nav class="game-dock" aria-label="Игровой мир"><button data-action="chest"><span class="dock-art">${obj('chest')}</span>Сокровища</button><button data-action="family"><span class="dock-art">${obj('team')}</span>Команда</button><button data-action="wardrobe"><span class="dock-art">${obj('shirt')}</span>Гардероб</button><button data-action="world"><span class="dock-art room-icon"></span>Мой мир</button></nav></section>`}
function homeProps(){const c=chapters(S);return `<div class="home-props">${S.child.placed.filter(id=>['plant','lantern','pet'].includes(id)).map(id=>`<button class="home-prop prop-${id}" data-action="item-react" data-id="${id}" aria-label="${esc(finds.find(f=>f[0]===id)?.[1]||id)}">${obj(id)}</button>`).join('')}<button class="chapter-door" data-action="chapter" aria-label="Открытия нашего мира">${obj(c.current.art)}<span>${c.index+1}</span></button></div>`;}
function charactersGrid(){return `<div class="character-grid">${characters.map(([id,n])=>`<button class="character-card ${id===S.child.character?'selected':''}" data-action="character" data-id="${id}" aria-pressed="${id===S.child.character}">${pet(id)}<b>${n}</b>${id===S.child.character?'<span class="selected-mark">✓</span>':''}</button>`).join('')}</div>`}
function onboard(){const i=S.onboarding.step;let content='',footer='';
 if(i===0){content=`<div class="logo">M<span>★</span>KI</div><div class="ob-art">${pet('moki','happy')}</div><h1>Маленькие дела.<br>Большие приключения.</h1><p>Уютный мир, который растёт<br>вместе с самостоятельностью.</p>`;footer=button('Начать со взрослым','ob-next');}
 if(i===1){content=`<h1>С чего начнём?</h1><p>Выберите до трёх миссий на день.<br>Остальные можно добавить позже.</p><div class="choices">${[['bag','Рюкзак без суеты'],['room','Уютная комната'],['reading','Время для книги'],['morning_teeth','Спокойное утро'],['evening_teeth','Вечерняя забота']].map(([id,title])=>{const m=missions.find(m=>m.id===id),on=S.missionSettings[id].enabled;return `<button class="choice ${on?'selected':''}" data-action="ob-mission" data-id="${id}" aria-pressed="${on}">${obj(m.art)}<div><b>${title}</b><small>${m.minutes} мин · ${m.hp} HP</small></div><span class="check">${on?'✓':''}</span></button>`}).join('')}</div>`;footer=button('Дальше','ob-next','purple',enabled(S).length?'':'disabled');}
 if(i===2){content=`<h1>Сколько помощи<br>нужно сейчас?</h1><p>Начнём с комфортного уровня.<br>Его можно менять постепенно.</p><div class="choices">${[['0','Вместе','Взрослый рядом на старте'],['1','По шагам','Одно короткое действие на экране'],['2','Почти сам','Короткий план, помощь по запросу']].map(([id,n,d])=>`<button class="choice ${S.onboarding.support===Number(id)?'selected':''}" data-action="ob-support" data-id="${id}" aria-pressed="${S.onboarding.support===Number(id)}"><div><b>${n}</b><small>${d}</small></div><span class="check">${S.onboarding.support===Number(id)?'✓':''}</span></button>`).join('')}</div>`;footer=button('Дальше','ob-next');}
 if(i===3){content=`<h1>Знакомство<br>со взрослым</h1><p>Имя — для приветствия.<br>PIN — для настроек и семейных дел.</p><label class="field">Как обращаться к ребёнку?<input id="child-name" maxlength="24" autocomplete="off" placeholder="Имя или игровой ник" value="${esc(S.child.name==='Друг'?'':S.child.name)}"></label><label class="field">Придумайте PIN из 4 цифр<input id="new-pin" type="password" inputmode="numeric" maxlength="4" autocomplete="new-password" placeholder="4 цифры"></label><p class="fineprint">PIN защищает настройки от случайного входа. Игра и прогресс хранятся на этом устройстве.</p><div class="error" id="setup-error" role="alert"></div>`;footer=button('Сохранить','ob-save');}
 if(i===4){content=`<h1>Значок исследователя</h1><p>Фото необязательно. Оно останется<br>на этом устройстве и не попадёт друзьям.</p><div style="display:grid;place-items:center">${avatar('child',false,'large')}</div>${button('Добавить фото','photo','quiet')}<p class="fineprint">Фото добавляет взрослый. Вместо него всегда можно оставить игрового героя.</p>`;footer=button('Дальше','ob-next');}
 if(i===5){content=`<div class="ob-art">${pet('moki','helping')}</div><h1>Теперь телефон<br>можно передать ребёнку</h1><p>Моки очень хочет познакомиться!</p>`;footer=button('Я здесь!','ob-next','gold');}
 if(i===6){content=`<h1>Кто станет<br>твоим другом?</h1><p>Каждый герой особенный.<br>Выбери того, кто тебе ближе.</p>${charactersGrid()}`;footer=button('Продолжить →','ob-next');}
 if(i===7){content=`<h1>Где начнётся<br>приключение?</h1><p>Выбери дом для себя и друга.<br>Мир можно менять в любое время.</p>${worldsGrid()}`;footer=button('Поселиться здесь','ob-next');}
 if(i===8){const m=next(S);content=`<div class="ob-art">${pet(S.child.character,'excited')}</div><h1>Ну что, ${esc(S.child.name)},<br>попробуем?</h1><p>${m?`Первая миссия: «${esc(m.title)}».<br>Я покажу только один шаг за раз.`:'Давай сначала посмотрим наш дом.'}</p>`;footer=button('Вперёд!','ob-finish','primary');}
 return `<section class="onboard ${i===0?'intro':''}"><div class="ob-top">${i?round('‹','ob-back','Предыдущий шаг'):''}<div class="ob-progress" aria-label="Шаг ${i+1} из 9">${Array.from({length:9},(_,n)=>`<i class="${n<=i?'on':''}"></i>`).join('')}</div></div><div class="ob-content">${i>=5?listenButton():''}${content}</div>${footer}</section>`;
}
function mission(){const a=S.activeMission,m=missions.find(m=>m.id===a?.id);if(!m){ui.screen='home';return home()}if(a.phase==='effort')return effort();const g=guidanceFor(m.id,a.step),suggested=supportSuggestion(S.history,m.id)==='together';return `<section class="mission-page visual-mission">${roomBg()}<header class="mission-top">${round('Ⅱ','pause','Пауза — шаг сохранится')}<div class="step-stones" role="progressbar" aria-label="Шаг ${a.step+1} из 3" aria-valuenow="${a.step+1}" aria-valuemin="1" aria-valuemax="3">${[0,1,2].map(n=>`<span class="${n<a.step?'done':n===a.step?'current':''}" aria-hidden="true">${n<a.step?'✓':n+1}</span>`).join('')}</div>${listenButton('Послушать текущий шаг')}</header><div class="mission-heading">${obj(m.art)}<h1>${esc(m.title)}</h1></div><article class="action-card" aria-label="Текущее действие">${stepArt(m.id,a.step)}<h2>${esc(g.label)}</h2></article><div class="guide-companion"><span class="actor-host">${pet(S.child.character,a.hints.length?'helping':'idle')}</span><div class="guide-caption">${suggested?'Можно вместе':a.step===0?'Начни с этого':a.step===1?'Теперь этот шаг':'Последний шаг'}<small>${S.missionSettings[m.id].support===0?'Взрослый может быть рядом':'Делай в своём темпе'}</small></div></div><div class="mission-actions">${button(`${obj('lantern')}<span>Помоги</span>`,'help','quiet')}${button('<span class="control-check" aria-hidden="true">✓</span><span>Готово</span>','step','primary')}</div></section>`}

function effort(){return `<section class="reward-page"><div class="eyebrow">Все три шага готовы</div>${pet(S.child.character,'happy')}<h1>Как тебе было?</h1>${listenButton()}<p>Любой ответ подходит.</p><div class="effort-options">${[['easy','happy','Легко'],['ok','idle','Нормально'],['hard','helping','Сложно']].map(([id,p,n])=>`<button data-action="effort" data-id="${id}">${pet(S.child.character,p)}${n}</button>`).join('')}</div></section>`}
function reward(){const h=ui.reward;return `<section class="reward-page"><div class="eyebrow">Маленькая победа</div><h1>Получилось!</h1><span class="actor-host reward-actor">${pet(S.child.character,'celebrate')}</span><div class="reward-hp" aria-live="polite"><span class="heart">♥</span> +${h?.hp||0} HP</div><p>${esc(missions.find(m=>m.id===h?.missionId)?.title||'Миссия')} — готово.<br>Ты сделал настоящее дело.</p>${routePips()}${button(`${obj(chestReady(S)?'chest':'plant')}<span class="child-button-label">${chestReady(S)?'Посмотреть сундук':'К своему герою'}</span>`,chestReady(S)?'chest':'home','gold')}<small class="muted">Можно вернуться к игре позже.</small></section>`}
function chest(){const ready=chestReady(S);return `<section class="reward-page"><div class="eyebrow">Твои сокровища</div><button class="chest-object-button" data-action="${ready?'reveal':'listen'}" aria-label="${ready?'Открыть сундук':'Послушать про сундук'}">${obj('chest',`big ${ready?'chest-shake':''}`)}</button><h1>${ready?'Что же внутри?':S.day.chestOpened?'Сегодняшняя находка уже дома':'Сундук ждёт своих приключений'}</h1><p>${ready?'Новая находка останется с тобой навсегда.':S.day.chestOpened?'Загляни в комнату и попробуй её потрогать.':`Заверши ${chestGoal(S)} миссии в любой удобный момент. Сейчас готово ${Math.min(chestGoal(S),completed(S))}.`}</p>${ready?button('Открыть','reveal','gold'):button(S.day.chestOpened?'Посмотреть находку':'К своему герою',S.day.chestOpened?'world':'home','purple')}${ready?button('Открыть позже','home','text'):''}</section>`}
function findScreen(){const f=ui.find;return `<section class="reward-page"><div class="eyebrow">Это твоё навсегда</div><h1>${esc(f?.[1]||'Новая радость')}</h1>${f?.[0]==='reaction'?pet(S.child.character,'celebrate'):obj(f?.[0]||'plant','big')}<p>${esc(f?.[2]||'Маленький праздник в нашем доме.')}</p>${button(`${obj(f?.[0]||'plant')}<span class="child-button-label">Посмотреть в мире</span>`,'world','gold')}</section>`}
function world(){const t=ui.worldTab;return `<section class="world-page"><div class="world-scene">${roomBg()}${pageHead('Мой мир',worlds.find(w=>w[0]===S.child.theme)?.[2]||'Лесная хижина')}<button class="hero-button" data-action="pet" aria-label="Погладить ${name()}">${heroArt()}</button>${S.child.placed.map(id=>`<button class="placed ${id}" data-action="item-react" data-id="${id}" aria-label="${esc(finds.find(f=>f[0]===id)?.[1]||id)}">${obj(id)}</button>`).join('')}</div><div class="world-drawer"><div class="tabs" role="tablist">${[['items','Находки'],['wardrobe','Гардероб'],['characters','Герои'],['worlds','Миры']].map(([id,n])=>`<button role="tab" aria-selected="${id===t}" class="${id===t?'on':''}" data-action="world-tab" data-id="${id}">${n}</button>`).join('')}</div>${!S.child.collection.length?`<div class="world-empty">${obj('plant')}<p>Твой первый предмет появится после ${chestGoal(S)} миссий. А уютный дом уже здесь.</p></div>`:''}${t==='worlds'?worldsGrid():t==='characters'?charactersGrid():`<div class="item-grid">${finds.filter(f=>t==='wardrobe'?['hat','glasses','scarf'].includes(f[0]):!['hat','glasses','scarf'].includes(f[0])).map(([id,n],i)=>{const owned=S.child.collection.includes(id),on=t==='wardrobe'?S.child.accessory===id:S.child.placed.includes(id);return `<button class="item-card ${owned?'':'locked'} ${on?'selected':''}" data-action="${t==='wardrobe'?'wear':'place'}" data-id="${id}" aria-pressed="${on}">${obj(id)}<b>${n}</b><small>${owned?on?'Выбрано':'Нажми, чтобы выбрать':`Находка ${finds.findIndex(f=>f[0]===id)+1}`}</small></button>`}).join('')}</div>`}${t==='wardrobe'&&S.child.accessory?button('Снять аксессуар','unwear','text'):''}${t==='characters'?`<p class="fineprint" style="text-align:center;margin-top:18px">Все друзья доступны. Героя можно менять в любое время.</p>`:''}</div></section>`}
function family(){const total=familyTotal(S),left=Math.max(0,S.family.bossMax-(total-S.family.bossBase)),members=[{id:'child',name:S.child.name,hp:S.child.hp},...S.family.members];return `<section class="page">${pageHead('Наша команда','Вместе мы сильнее!')}<div class="family-members">${members.map(m=>`<div class="member">${avatar(m.id,true)}<b>${esc(m.name)}</b><small>${m.hp} HP</small></div>`).join('')}<div class="member"><button class="round" data-action="invite" aria-label="Добавить члена семьи">+</button><b>Позвать</b></div></div><section class="panel family-goal"><span class="heart">♥</span><div><h2>Семейная цель</h2>${meter(total,S.family.goal)}<p>${total} / ${S.family.goal} HP · ${total>=S.family.goal?'Получилось вместе!':'Каждое дело помогает'}</p></div>${obj('chest')}</section><section class="boss-card"><div class="boss-top">${pet('nori',left?'thinking':'happy')}<div><h2>${left?'Облачный Ворчун':'Ворчун улыбается!'}</h2><p>${left?'Каждое полезное дело делает тучку меньше.':'Вы справились вместе. Можно отдыхать.'}</p></div></div>${meter(S.family.bossMax-left,S.family.bossMax,'purple')}<small>${left?`${left} HP до солнечного настроения`:'Командная победа'}</small><div class="row">${button('Твой ход','nudge','quiet')}${button('Вызов','challenge','purple')}</div></section>${S.family.challenge?`<section class="panel challenge-card"><h3>${S.family.challenge.active?'Дружеский вызов':S.family.challenge.winner==='child'?'Ты закончил первым!':'Взрослый закончил первым!'}</h3><p>${esc(S.child.name)}: ${esc(missions.find(m=>m.id===S.family.challenge.childMission)?.title)}</p><p>${esc(S.family.members.find(m=>m.id===S.family.challenge.member)?.name)}: ${esc(S.family.challenge.adultTask)}</p><small>${S.family.challenge.active?'У каждого своё дело. Можно закончить в своём темпе.':'Спасибо друг другу за компанию. Очки у каждого за своё дело.'}</small></section>`:''}<section class="panel">${S.family.feed.length?`<h3 style="margin-bottom:10px">Маленькие победы</h3>${S.family.feed.slice(0,6).map(f=>`<div class="feed-row">${avatar(f.member,true)}<div><b>${esc(f.member==='child'?S.child.name:S.family.members.find(m=>m.id===f.member)?.name||'Участник')}</b><p>${esc(f.task)}</p></div><span class="gain">${f.hp?`+${f.hp} HP`:'✓'}</span></div>`).join('')}`:`<div class="empty">${obj('team')}<h3>Первое дело — начало команды</h3><p>${S.family.members.length?'Сделайте каждый по маленькому делу. Здесь появятся ваши победы.':'Позови взрослого. У каждого будет своё дело, а цель — общая.'}</p>${button(S.family.members.length?'К своей миссии':'Позвать взрослого',S.family.members.length?'home':'invite','quiet')}</div>`}</section>${button('Что увидит друг?','friend','text')}</section>`}
function parent(){const tab=ui.parentTab,h=S.history.filter(h=>!h.legacy&&h.date===dateKey()),tabs=[['today','Сегодня'],['missions','Миссии'],['skills','Навыки'],['family','Семья'],['character','Персонаж'],['privacy','Настройки']];let content='';
 if(tab==='today')content=`<section class="panel"><div class="eyebrow">${esc(S.child.name)} · сегодня</div><h2 style="margin-top:10px">${h.length?'Есть маленькие победы':'Начните с одного дела'}</h2><p>${h.length?`Завершено ${h.length} из ${enabled(S).length} выбранных миссий.`:'Выберите удобное время. Ребёнку достаточно одной миссии за раз.'}</p><div class="metric-grid"><div class="metric"><strong>${h.length}</strong><small>миссий завершено</small></div><div class="metric"><strong>${h.reduce((n,x)=>n+x.hints,0)}</strong><small>обращений за помощью</small></div></div>${meter(h.length,Math.max(1,enabled(S).length))}</section><section class="panel"><h3>Что это говорит о самостоятельности?</h3><p>${h.length?`${h.filter(x=>x.scaffolding===0).length} миссий закончены без помощи внутри игры.`:'После первых миссий здесь появятся наблюдения.'}</p><p class="fineprint">Игра не знает, напоминали ли вы устно. Отсутствие подсказок не доказывает самостоятельный старт.</p></section><section class="panel"><h3>Сегодня в плане</h3>${enabled(S).map(m=>`<div class="mission-row">${obj(m.art)}<div><b>${m.title}</b><small>${S.day.completed[m.id]?'Готово':`${m.minutes} мин · ${m.hp} HP`}</small></div><span>${S.day.completed[m.id]?'✓':'—'}</span></div>`).join('')}</section>`;
 if(tab==='missions')content=`<p style="margin-bottom:15px">Короткий маршрут помогает начать. Выбирайте столько, сколько семье сейчас удобно.</p>${categories.map(c=>`<h3 class="section-title">${c}</h3><section class="panel">${missions.filter(m=>m.category===c).map(m=>`<div class="mission-row">${obj(m.art)}<div><b>${m.title}</b><small>3 шага · ${m.minutes} мин · ${m.hp} HP</small><select class="support-select" data-support="${m.id}" aria-label="Уровень помощи: ${m.title}">${['Вместе','По шагам','Почти сам'].map((n,i)=>`<option value="${i}" ${S.missionSettings[m.id].support===i?'selected':''}>${n}</option>`).join('')}</select></div><button class="toggle" role="switch" aria-label="${m.title}" aria-checked="${S.missionSettings[m.id].enabled}" data-action="toggle-mission" data-id="${m.id}"></button></div>`).join('')}</section>`).join('')}`;
 if(tab==='skills')content=`<section class="panel"><h2>Самостоятельность по шагам</h2><p>Смотрим на повторения и поддержку, без оценок «хорошо» и «плохо».</p>${enabled(S).map(m=>{const a=skillSummary(S,m.id);return `<div class="skill"><h3>${m.title}</h3><p>${a.count?`${a.count} завершений · ${a.independent} без подсказок · ${a.hints} обращений за помощью`:'Пока мало наблюдений. Начните с одной попытки.'}</p>${a.canFade?`<p>Четыре раза подряд получилось без подсказок. Можно попробовать более короткий план.</p>${button('Уменьшить помощь','fade','quiet',`data-id="${m.id}"`)}`:a.needsSupport?`<p>Последние два раза было сложно. Попробуйте начать вместе.</p>${button('Добавить поддержку','support-more','quiet',`data-id="${m.id}"`)}`:''}</div>`}).join('')}</section><div class="notice">Длительность включает паузы и время вне приложения. Она не используется как оценка ребёнка. Внешние напоминания автоматически не измеряются.</div>`;
 if(tab==='family')content=`<section class="panel"><h2>Семья на одном устройстве</h2><p>Добавьте участников и отмечайте взрослые дела здесь. Интернет-приглашения пока не подключены.</p>${button('Добавить участника','add-member','quiet')}<div style="margin-top:18px">${S.family.members.map(m=>`<div class="mission-row">${avatar(m.id,true)}<div><b>${esc(m.name)}</b><small>${m.hp} HP</small></div><button class="round" data-action="adult-task" data-id="${m.id}" aria-label="Отметить дело ${esc(m.name)}">+</button></div>`).join('')}</div></section><section class="panel"><h3>Общая цель</h3><label class="field" style="margin-top:12px">HP до общей победы<input id="family-goal" type="number" min="10" max="10000" value="${S.family.goal}"></label>${button('Сохранить цель','save-goal','quiet')}<p>Новая цель не уменьшает заработанные HP.</p></section>${familyTotal(S)-S.family.bossBase>=S.family.bossMax?button('Новая тучка для команды','boss-reset','quiet'):''}`;
 if(tab==='character')content=`<section class="panel"><h2>Друг ребёнка</h2><p style="margin-bottom:20px">Выбор можно менять без потери прогресса.</p>${charactersGrid()}</section><section class="panel"><h3>Значок исследователя</h3><div style="display:grid;place-items:center;padding:20px">${avatar('child',false,'large')}</div>${button('Добавить или заменить фото','photo','quiet')}${S.child.portrait?button('Вернуть игровой аватар','remove-photo','text'):''}<p class="fineprint">Фото хранится локально. Друзья его не видят.</p></section>`;
 if(tab==='privacy')content=`<section class="panel"><h2>Спокойные настройки</h2>${[['voice','Голос Моки','Автоматически читает шаги после включения ребёнком'],['calm','Спокойный режим','Без повторяющихся движений и подпрыгиваний'],['sound','Звуки','Короткий звук после успеха'],['haptics','Тактильный отклик','Если устройство поддерживает вибрацию'],['photoFamily','Фото на экране семьи','По умолчанию — игровой аватар']].map(([id,n,d])=>`<div class="settings-row"><div><b>${n}</b><p>${d}</p></div><button class="toggle" role="switch" aria-label="${n}" aria-checked="${S.settings[id]}" data-action="setting" data-id="${id}"></button></div>`).join('')}<p class="fineprint">На iPhone браузер может не поддерживать вибрацию. Уменьшение движения берётся из настроек устройства.</p></section><section class="panel"><h3>Данные ребёнка</h3><p>Фото, миссии и прогресс хранятся в этом браузере. Аккаунтов, свободного чата и передачи фото друзьям нет.</p><p>Очистка данных браузера удалит локальный прогресс. Между устройствами он пока не синхронизируется.</p>${button('Сохранить копию прогресса','export-progress','quiet')}<label class="btn quiet upload">Восстановить из копии<input type="file" id="progress-input" accept="application/json,.json" aria-label="Выбрать копию прогресса"></label><p class="fineprint">В копию не входят фото и PIN. Файл содержит имена и историю дел — храните его приватно.</p>${button('Что увидит друг?','friend','quiet')}</section><section class="panel"><h3>Вход для взрослого</h3><p>Настройки закрываются при выходе из режима и сворачивании приложения. PIN — локальная защита от случайного доступа, не шифрование данных.</p>${button('Изменить PIN','change-pin','quiet')}</section><p class="fineprint">MOKI · единое игровое ядро · 2026-09-08</p>`;
 return `<section class="page parent-page">${pageHead('Для взрослого','Спокойно растим самостоятельность')}<nav class="tabs parent-tabs" aria-label="Разделы для взрослого">${tabs.map(([id,n])=>`<button class="${tab===id?'on':''}" data-action="parent-tab" data-id="${id}" aria-current="${tab===id?'page':'false'}">${n}</button>`).join('')}</nav>${content}</section>`;
}
function drawModal(){if(!ui.modal){modal.innerHTML='';return}let title='',body='';const a=S.activeMission,m=missions.find(m=>m.id===a?.id);
 if(ui.modal==='help'){title=ui.helpLevel?'Попробуем вместе':'Я помогу';body=ui.helpLevel?`${ui.helpLevel===3?`<div class="together-art">${obj('team','big')}</div>`:stepArt(m.id,a.step,'help-art')}<h2 class="center">${esc(ui.helpLevel===1?m.steps[a.step].hint:ui.helpLevel===2?guidanceFor(m.id,a.step).label:'Позови взрослого')}</h2>${listenButton('Послушать подсказку')}<p class="center">${ui.helpLevel===3?'Сделайте этот шаг вместе.':'Можно вернуться и попробовать.'}</p>${button('<span class="control-check" aria-hidden="true">✓</span> Попробую','close-modal','primary')}`:`<div class="help-guide">${pet(S.child.character,'helping')}</div><div class="help-choices">${[['1','lantern','Намёк'],['2','book','Покажи'],['3','team','Вместе']].map(([id,art,label])=>button(`${obj(art)}<b>${label}</b>`,'help-level','quiet',`data-id="${id}"`)).join('')}</div>${listenButton()}`;}

 if(ui.modal==='chapter'){const c=chapters(S);title=c.current.title;body=`<div class="chapter-art">${obj(c.current.art,'big')}</div><div class="chapter-track">${Array.from({length:4},(_,i)=>`<span class="${i<=c.index?'unlocked':''}">${i<=c.index?'✓':i+1}</span>`).join('')}</div><p>${c.next?`Наш дом меняется после настоящих дел. До следующего открытия: ${Math.max(0,c.next.at-c.count)}.`:'В доме живут твои истории. Можно возвращаться к любимым открытиям.'}</p>${c.index>=2?button(`${obj('telescope')} Посмотреть небо`,'sky','purple'):button('Поиграть дома','close-modal','quiet')}`;}
 if(ui.modal==='sky'){title='Найди три огонька';const stars=S.world?.stars||[];body=`<div class="sky-toy" aria-label="Небо с тремя звёздами"><div class="constellation ${stars.length===3?'complete':''}"></div>${[0,1,2].map(i=>`<button class="sky-star star-${i} ${stars.includes(i)?'found':''}" data-action="star" data-id="${i}" aria-label="Звезда ${i+1}${stars.includes(i)?', найдена':''}" aria-pressed="${stars.includes(i)}">✦</button>`).join('')}</div><p>${stars.length===3?'Это созвездие теперь твоё. Оно останется здесь.':'Коснись каждого огонька.'}</p>${button('Вернуться домой','close-modal','quiet')}`;}
 if(ui.modal==='memories'){title='Наши маленькие победы';body=`${obj('shelf','big')}<p>${S.history.length?'Помнишь, что у тебя получилось?':'Здесь появятся истории твоих настоящих дел.'}</p><div class="memory-shelf">${S.history.filter(h=>!h.legacy).slice(-6).reverse().map(h=>`<div>${obj(missions.find(m=>m.id===h.missionId)?.art||'book')}<b>${esc(missions.find(m=>m.id===h.missionId)?.title||'Маленькая победа')}</b><span>✓</span></div>`).join('')}</div>${button('К герою','close-modal','quiet')}`;}
 if(ui.modal==='pause'){title='Сделаем паузу?';body=`<p>Твой шаг сохранится. Вернёшься — продолжим с него.</p>${button('Продолжить миссию','close-modal','primary')}${button('Вернуться домой','home','text')}`;}
 if(ui.modal==='gate'){title='Для взрослого';body=`<p class="center">Введите свой PIN.</p><div class="pin-dots" aria-label="Введено ${ui.pin.length} цифр">${'●'.repeat(ui.pin.length)}${'○'.repeat(4-ui.pin.length)}</div><div class="pin-pad">${['1','2','3','4','5','6','7','8','9','⌫','0','×'].map(n=>`<button data-action="pin-key" data-id="${n}" aria-label="${n==='⌫'?'Удалить цифру':n==='×'?'Отмена':n}">${n}</button>`).join('')}</div><p class="error center" id="pin-error" role="alert"></p>`;}
 if(ui.modal==='invite'){title='Позовём взрослого';body=`${obj('team','big')}<p>Попроси взрослого добавить семью. Можно играть по очереди на этом устройстве.</p>${button('Открыть режим взрослого','parent','purple')}`;}
 if(ui.modal==='nudge'){title='Поддержи команду';body=S.family.members.length?`<p>Выбери короткую реакцию. Она появится на семейном экране этого устройства.</p><div class="stack">${['Твой ход','Я тебя догоняю','Давай вместе','Ещё одно','Красиво!'].map((n,i)=>button(n,'send-nudge','quiet',`data-id="${i}"`)).join('')}</div>`:`${obj('team','big')}<p>Сначала попроси взрослого добавить участника команды.</p>${button('Позвать взрослого','parent')}`;}
 if(ui.modal==='challenge'){title='Вызов на двоих';body=S.family.members.length&&next(S)?`<p>Твоё дело: ${esc(next(S).title)}.<br>Взрослый выберет своё в режиме для взрослых.</p>${button('Выбрать вместе со взрослым','parent')}`:`<p>${!S.family.members.length?'Для вызова нужен ещё один участник.':'На сегодня твои дела готовы. Новый вызов можно начать завтра.'}</p>${button('Понятно','close-modal','quiet')}`;}
 if(ui.modal==='friend'){title='Что увидит друг';const f=friendFeed(S)[0];body=`<p>Только категория и HP. Конкретные дела и фото остаются внутри семьи.</p><div class="privacy-sample">${esc(f?.name||S.child.name)} · +${f?.hp||5} HP · ${esc(f?.category||'Учёба')}</div><p class="fineprint">Это пример безопасного отображения. Подключение друзей и обмен между устройствами пока недоступны.</p>${button('Понятно','close-modal','quiet')}`;}
 if(ui.modal==='add-member'){title='Новый участник';body=`<label class="field">Имя или роль<input id="member-name" maxlength="24" placeholder="Например, папа"></label><label class="field" style="margin-top:12px">Игровой аватар<select id="member-character">${characters.map(([id,n])=>`<option value="${id}">${n}</option>`).join('')}</select></label><p>Участник появится на семейном экране этого устройства.</p>${button('Добавить','save-member')}`;}
 if(ui.modal==='adult-task'){title='Дело взрослого';body=`<label class="field">Что планируете сделать?<input id="adult-task" maxlength="80" placeholder="Например, 20 минут прогулки" value="${esc(S.family.challenge?.active&&S.family.challenge.member===ui.member?S.family.challenge.adultTask:'')}"></label><label class="field" style="margin-top:12px">Размер дела<select id="adult-hp"><option value="3">Маленькое · 3 HP</option><option value="5" selected>Обычное · 5 HP</option><option value="8">Сложное · 8 HP</option></select></label><p>Отметьте только реально сделанное дело.</p>${button('Дело готово','adult-done','primary')}${next(S)?button('Начать вызов с ребёнком','create-challenge','quiet'):''}`;}
 if(ui.modal==='photo'){title='Приватный портрет';body=ui.photo?`<div class="crop-frame" style="--zoom:${ui.zoom};--x:${ui.x}%;--y:${ui.y}%"><img src="${ui.photo}" alt="Предпросмотр обрезки"></div><label class="field">Приближение<input type="range" data-crop="zoom" min="1" max="2.5" step="0.05" value="${ui.zoom}"></label><label class="field">Левее / правее<input type="range" data-crop="x" min="0" max="100" value="${ui.x}"></label><label class="field">Выше / ниже<input type="range" data-crop="y" min="0" max="100" value="${ui.y}"></label><p>Обрезка и сжатие выполняются на устройстве.</p>${button('Сохранить портрет','save-photo')}`:`<p>Выберите фото. Оно не отправляется на сервер. Можно оставить игровой аватар.</p><label class="btn purple upload">Выбрать фото<input type="file" id="photo-input" accept="image/jpeg,image/png,image/webp,image/heic" aria-label="Выбрать фото"></label>`;}
 if(ui.modal==='restore-progress'){title='Восстановить прогресс?';body=`<p>Заменится прогресс на этом устройстве. В копии: ${esc(ui.restore?.child.name)}, ${ui.restore?.child.hp||0} HP. После восстановления взрослый создаст новый PIN.</p>${button('Восстановить','confirm-restore')}${button('Отмена','close-modal','text')}`;}
 if(ui.modal==='change-pin'){title='Новый PIN';body=`<label class="field">Четыре цифры<input id="replacement-pin" type="password" inputmode="numeric" maxlength="4" autocomplete="new-password"></label><p>Запомните PIN. Восстановления через аккаунт пока нет.</p>${button('Сохранить PIN','save-pin')}`;}
 modal.innerHTML=`<div class="modal-shell"><section class="dialog" role="dialog" aria-modal="true" aria-label="${title}"><div class="dialog-head"><h2>${title}</h2>${round('×','close-modal','Закрыть')}</div>${body}</section></div>`;
}
async function hashPin(pin,salt){const bytes=new TextEncoder().encode(`${salt}:${pin}`);return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function setPin(pin){S.settings.pinSalt=crypto.randomUUID();S.settings.pinHash=await hashPin(pin,S.settings.pinSalt)}
let busy=false,lastStepAt=0;
document.addEventListener('click',async e=>{
 const b=e.target.closest('[data-action]');if(!b||b.disabled||busy)return;const action=b.dataset.action,id=b.dataset.id;feedback();
 const adultActions=['parent-tab','toggle-mission','fade','support-more','add-member','save-member','adult-task','adult-done','create-challenge','save-goal','boss-reset','setting','remove-photo','change-pin','save-pin','export-progress','confirm-restore'];if(adultActions.includes(action)&&!ui.parentUnlocked)return;
 if(action==='listen'){if(document.documentElement.dataset.speaking==='speaking'){narrator.stop();return}S.settings.voice=true;save();narrator.say(narrationText());return}
 if(action==='practice-pet'){ui.practiceStep=1;render();feedback('step');narrate();return}
 if(action==='practice-done'){S.settings.learnedControls=true;save();const m=next(S);if(m){start(S,m.id);save();go('mission');narrate()}else go('home');return}
 if(action==='export-progress'){const url=URL.createObjectURL(new Blob([exportProgress(S)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download=`moki-progress-${dateKey()}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return}
 if(action==='confirm-restore'&&ui.restore){S=ui.restore;ui.restore=null;ui.parentUnlocked=false;ui.modal=null;ui.screen='home';if(save())render();return}
 if(['home','world','family'].includes(action)){go(action);return}
 if(action==='close-modal'){closeModal();return}
 if(action==='pet'){scene?.event('pet');scene?.sound('character.happy');const sp=document.querySelector('#speech > span');if(sp)sp.textContent='Как здорово, что ты здесь!';return}
 if(action==='theme'&&worlds.some(w=>w[0]===id)){S.child.theme=id;save();render();return}
 if(action==='ob-next'){if(S.onboarding.step===1&&!enabled(S).length)return;S.onboarding.step=Math.min(8,S.onboarding.step+1);save();render();window.scrollTo(0,0);return}
 if(action==='ob-back'){S.onboarding.step=Math.max(0,S.onboarding.step-1);save();render();return}
 if(action==='ob-mission'){const v=S.missionSettings[id];if(!v.enabled&&enabled(S).length>=3){toast('Выберите до трёх дел. Одно можно убрать.');return}v.enabled=!v.enabled;save();render();return}
 if(action==='ob-support'){S.onboarding.support=Number(id);save();render();return}
 if(action==='ob-save'){const n=document.querySelector('#child-name').value.trim(),pin=document.querySelector('#new-pin').value;if(!n||!/^\d{4}$/.test(pin)){document.querySelector('#setup-error').textContent='Укажите имя и PIN из четырёх цифр.';return}busy=true;try{await setPin(pin);S.child.name=n;for(const m of enabled(S))S.missionSettings[m.id].support=S.onboarding.support;S.onboarding.step=4;save();render()}catch{toast('Не удалось создать PIN. Попробуйте снова.')}finally{busy=false}return}
 if(action==='ob-finish'){S.onboarded=true;ui.practiceStep=0;save();go('practice');narrate();return}
 if(action==='character'){if(!characters.some(c=>c[0]===id))return;S.child.character=id;save();render();return}
 if(action==='start'){if(!S.settings.learnedControls){ui.practiceStep=0;go('practice');return}if(start(S,id)){save();go('mission');narrate()}return}
 if(action==='pause'){showModal('pause');return}
 if(action==='step'){if(Date.now()-lastStepAt<500)return;lastStepAt=Date.now();narrator.stop();if(advance(S)){save();render();scene?.event('step');feedback('step');narrate()}return}
 if(action==='help'){ui.helpLevel=0;scene?.event('help');showModal('help');return}
 if(action==='help-level'){const level=Number(id);if(help(S,level)){ui.helpLevel=level;save();drawModal();narrate()}return}
 if(action==='effort'){ui.reward=finish(S,id);if(ui.reward){save();go('reward');scene?.reward();narrate()}return}
 if(action==='chest'){go('chest');return}
 if(action==='reveal'){ui.find=openChest(S);if(ui.find){save();go('find');scene?.sound('chest.open');narrate()}return}
 if(action==='wardrobe'){ui.worldTab='wardrobe';go('world');return}
 if(action==='world-tab'){ui.worldTab=id;render();return}
 if(action==='place'||action==='wear'){if(!S.child.collection.includes(id)){toast('Эта находка ждёт тебя в одном из следующих сундуков.');return}if(action==='wear'){S.child.accessory=S.child.accessory===id?null:id;toast(S.child.accessory?'Аксессуар выбран.':'Аксессуар снят.')}else{S.child.placed=S.child.placed.includes(id)?S.child.placed.filter(x=>x!==id):[...S.child.placed,id]}save();render();return}
 if(action==='unwear'){S.child.accessory=null;save();render();return}
 if(action==='item-react'){const result=interactWorld(S,id);if(!result)return;save();scene?.item(id,b);if(['telescope','shelf','trophy'].includes(id))showModal(id==='telescope'?'sky':'memories');if(id==='bed'){S.world.napping?scene?.event('sleep'):scene?.event('wake');}return}
 if(action==='chapter'){showModal('chapter');return}
 if(action==='sky'){showModal('sky');return}
 if(action==='star'){if(discoverStar(S,Number(id))){save();b.classList.add('found');b.setAttribute('aria-pressed','true');b.setAttribute('aria-label',`Звезда ${Number(id)+1}, найдена`);if(S.world.stars.length===3){modal.querySelector('.constellation')?.classList.add('complete');const text=modal.querySelector('.dialog>p');if(text)text.textContent='Это созвездие теперь твоё. Оно останется здесь.';}scene?.sound('reward.common')}return}
 if(action==='parent'){ui.pin='';if(ui.parentUnlocked){ui.modal=null;ui.screen='parent';render()}else showModal('gate');return}
 if(action==='pin-key'){if(id==='×'){closeModal();return}if(Date.now()<ui.lockedUntil){toast('Подождите немного перед следующей попыткой.');return}if(id==='⌫')ui.pin=ui.pin.slice(0,-1);else if(ui.pin.length<4)ui.pin+=id;drawModal();if(ui.pin.length===4){busy=true;try{const ok=await hashPin(ui.pin,S.settings.pinSalt)===S.settings.pinHash;if(ok){ui.parentUnlocked=true;ui.modal=null;ui.pin='';ui.attempts=0;ui.screen='parent';render()}else{ui.pin='';ui.attempts++;if(ui.attempts>=5){ui.lockedUntil=Date.now()+30000;ui.attempts=0}drawModal();document.querySelector('#pin-error').textContent='PIN не подошёл. Попробуйте ещё раз.'}}finally{busy=false}}return}
 if(action==='parent-tab'){ui.parentTab=id;render();window.scrollTo(0,0);return}
 if(action==='toggle-mission'){S.missionSettings[id].enabled=!S.missionSettings[id].enabled;save();render();return}
 if(action==='fade'||action==='support-more'){S.missionSettings[id].support=action==='fade'?2:0;save();render();toast('Уровень помощи обновлён.');return}
 if(['invite','nudge','challenge','friend','add-member','change-pin'].includes(action)){showModal(action);return}
 if(action==='send-nudge'){const texts=['Твой ход','Я тебя догоняю','Давай вместе','Ещё одно','Красиво!'];const last=S.family.feed.find(f=>f.kind==='nudge');if(last&&Date.now()-last.at<60000){toast('Дадим команде минутку ответить.');return}S.family.feed.unshift({id:crypto.randomUUID(),kind:'nudge',member:'child',task:texts[Number(id)],hp:0,at:Date.now()});save();closeModal();render();return}
 if(action==='save-member'){const n=document.querySelector('#member-name').value.trim();if(!n){toast('Введите имя участника.');return}S.family.members.push({id:crypto.randomUUID(),name:n,character:document.querySelector('#member-character').value,hp:0});save();closeModal();render();return}
 if(action==='adult-task'){ui.member=id;showModal('adult-task');return}
 if(action==='adult-done'||action==='create-challenge'){const task=document.querySelector('#adult-task').value.trim(),hp=Number(document.querySelector('#adult-hp').value),member=S.family.members.find(m=>m.id===ui.member);if(!task||!member){toast('Опишите дело взрослого.');return}if(action==='create-challenge'){const m=next(S);if(!m)return;S.family.challenge={id:crypto.randomUUID(),member:member.id,childMission:m.id,adultTask:task,active:true,startedAt:Date.now()};}else{member.hp+=hp;S.family.feed.unshift({id:crypto.randomUUID(),member:member.id,category:'Дело взрослого',task,hp,at:Date.now()});if(S.family.challenge?.active&&S.family.challenge.member===member.id&&S.family.challenge.adultTask===task){S.family.challenge.active=false;S.family.challenge.winner=member.id}}save();closeModal();render();return}
 if(action==='save-goal'){const n=Number(document.querySelector('#family-goal').value);if(!Number.isInteger(n)||n<10||n>10000){toast('Введите цель от 10 до 10 000 HP.');return}S.family.goal=n;save();toast('Общая цель сохранена.');return}
 if(action==='boss-reset'){S.family.bossBase=familyTotal(S);save();render();return}
 if(action==='setting'){if(!['voice','calm','sound','haptics','photoFamily'].includes(id))return;S.settings[id]=!S.settings[id];if(id==='voice')narrator.stop();save();render();return}
 if(action==='photo'){if(S.onboarded&&!ui.parentUnlocked){showModal('gate');return}ui.photo=null;ui.zoom=1;ui.x=ui.y=50;showModal('photo');return}
 if(action==='save-photo'){if(S.onboarded&&!ui.parentUnlocked)return;await savePhoto();return}
 if(action==='remove-photo'){S.child.portrait=null;S.settings.photoFamily=false;save();render();return}
 if(action==='save-pin'){const pin=document.querySelector('#replacement-pin').value;if(!/^\d{4}$/.test(pin)){toast('Нужны четыре цифры.');return}await setPin(pin);save();closeModal();toast('PIN изменён.');return}
});
document.addEventListener('change',async e=>{if(e.target.id==='progress-input'&&ui.parentUnlocked){try{const file=e.target.files?.[0];if(!file)return;if(file.size>5*1024*1024)throw new Error('Too large');ui.restore=importProgress(await file.text());showModal('restore-progress')}catch{toast('Не получилось открыть копию. Выберите JSON-файл MOKI.')}return}if(e.target.dataset.support&&ui.parentUnlocked){const id=e.target.dataset.support;S.missionSettings[id].support=Number(e.target.value);save()}if(e.target.id==='photo-input'){const file=e.target.files?.[0];if(!file)return;if(file.size>15*1024*1024){toast('Выберите фото меньше 15 МБ.');return}const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{ui.photo=r.result;ui.photoImage=im;drawModal()};im.onerror=()=>toast('Не получилось открыть фото. Попробуйте JPEG или PNG.');im.src=r.result};r.readAsDataURL(file)}});
document.addEventListener('input',e=>{const p=e.target.dataset.crop;if(p){ui[p]=Number(e.target.value);const frame=modal.querySelector('.crop-frame');frame.style.setProperty('--'+p,p==='zoom'?ui[p]:ui[p]+'%')}});
async function savePhoto(){const im=ui.photoImage;if(!im)return;const canvas=document.createElement('canvas');canvas.width=canvas.height=320;const ctx=canvas.getContext('2d');const scale=Math.max(320/im.width,320/im.height)*ui.zoom,w=im.width*scale,h=im.height*scale;ctx.drawImage(im,(320-w)*ui.x/100,(320-h)*ui.y/100,w,h);S.child.portrait=canvas.toDataURL('image/jpeg',.82);if(save()){ui.photo=null;ui.photoImage=null;closeModal();render();toast('Портрет сохранён только на этом устройстве.')}}
document.addEventListener('keydown',e=>{if(!ui.modal)return;if(e.key==='Escape'){closeModal();return}if(e.key==='Tab'){const nodes=[...modal.querySelectorAll('button,input,select')].filter(el=>!el.disabled);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){scene?.pause(true);narrator.stop();ui.parentUnlocked=false;if(ui.screen==='parent'){ui.screen='home';ui.modal=null;render()}}else{dayCheck();render()}});
window.addEventListener('storage',e=>{if(e.key===KEY){narrator.stop();S=readState(localStorage).state;ui.modal=null;ui.parentUnlocked=false;if(ui.screen==='parent')ui.screen='home';render();toast('Прогресс обновлён из другой вкладки.')}});
scene=new SceneManager({app,markup:(id,pose,accessory)=>pet(id,pose)+(accessory&&pose!=='sleeping'?`<span class="accessory ${accessory}">${obj(accessory)}</span>`:'')});
render();if(boot.recovered)toast('Прогресс восстановлен из последней исправной копии.');
