import {characters,poses,objects,finds,missions,categories} from './catalog.js';
import {load,KEY,dateKey,enabled,completed,chestGoal,chestReady,familyTotal,next,start,help,advance,finish,openChest,skillSummary,friendFeed} from './state.js';
let S=load(localStorage);
const app=document.querySelector('#app'),modal=document.querySelector('#modal');
const ui={screen:S.activeMission?'mission':'home',worldTab:'items',parentTab:'today',modal:null,helpLevel:0,reward:null,find:null,parentUnlocked:false,pin:'',attempts:0,lockedUntil:0,photo:null,zoom:1,x:50,y:50};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pet=(id=S.child.character,pose='idle',cls='')=>{const row=Math.max(0,poses.indexOf(pose)),top=[0,157,313,463,615,768,892][row],height=[156,156,153,152,153,127,157][row];return `<span class="pet ${cls}" role="img" aria-label="${esc(characters.find(c=>c[0]===id)?.[1]||'Моки')}" style="aspect-ratio:299.8 / ${height};background-size:500% ${1049/height*100}%;background-position:${[2.1,25,50,73.7,97.9][Math.max(0,characters.findIndex(c=>c[0]===id))]}% ${top/(1049-height)*100}%"></span>`};
const obj=(id,cls='')=>{const n=objects.indexOf(id);return `<span class="object ${cls}" aria-hidden="true" style="background-position:${(n%4)*100/3}% ${Math.floor(n/4)*100/3}%"></span>`};
const heroArt=(pose='idle')=>pet(S.child.character,pose)+(S.child.accessory&&pose!=='sleeping'?`<span class="accessory ${S.child.accessory}">${obj(S.child.accessory)}</span>`:'');
const worlds=[['forest','Лес','Лесная хижина'],['space','Космос','Звёздная станция'],['island','Остров','Островной дом'],['town','Город','Солнечный городок']];
const roomBg=()=>`<div class="room-bg theme-${worlds.some(w=>w[0]===S.child.theme)?S.child.theme:'forest'}"></div>`;
const worldsGrid=()=>`<div class="world-choices">${worlds.map(([id,title,desc])=>`<button class="world-choice ${S.child.theme===id?'selected':''}" data-action="theme" data-id="${id}" aria-pressed="${S.child.theme===id}"><span class="world-thumb theme-${id}"></span><b>${title}</b><small>${desc}</small></button>`).join('')}</div>`;
const name=()=>characters.find(c=>c[0]===S.child.character)[1];
const avatar=(id='child',family=false,cls='')=>{const m=S.family.members.find(m=>m.id===id);return `<span class="avatar ${cls}">${id==='child'&&S.child.portrait&&(!family||S.settings.photoFamily)?`<img src="${S.child.portrait}" alt="Портрет ${esc(S.child.name)}">`:pet(id==='child'?S.child.character:m?.character||'tobi')}</span>`};
const button=(text,action,cls='purple',attrs='')=>`<button class="btn ${cls}" data-action="${action}" ${attrs}>${text}</button>`;
const round=(text,action,label)=>`<button class="round" data-action="${action}" aria-label="${label}">${text}</button>`;
const meter=(v,max=100,cls='')=>`<div class="meter ${cls}" role="progressbar" aria-valuenow="${Math.min(v,max)}" aria-valuemin="0" aria-valuemax="${max}"><i style="width:${Math.max(0,Math.min(100,v/max*100))}%"></i></div>`;
const pageHead=(title,subtitle='',action='home')=>`<header class="page-head">${round('‹',action,'Назад')}<div><h1>${title}</h1>${subtitle?`<p>${subtitle}</p>`:''}</div></header>`;
let storageWarning=false,toastTimer;
function save(){try{localStorage.setItem(KEY,JSON.stringify(S));storageWarning=false;return true}catch{storageWarning=true;toast('Не удалось сохранить. Оставь игру открытой и освободи место на устройстве.');return false}}
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('on');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('on'),4000)}
function feedback(kind='tap'){if(S.settings.haptics&&navigator.vibrate)navigator.vibrate(kind==='reward'?[18,45,18]:8);if(!S.settings.sound||kind==='tap')return;try{const C=window.AudioContext||window.webkitAudioContext;const c=feedback.ctx||(feedback.ctx=new C());c.resume();const o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.type='sine';o.frequency.setValueAtTime(520,c.currentTime);o.frequency.exponentialRampToValueAtTime(780,c.currentTime+.13);g.gain.setValueAtTime(.045,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.24);o.start();o.stop(c.currentTime+.25)}catch{}}
function dayCheck(){if(S.day.date!==dateKey()){S.day={date:dateKey(),completed:{},chestOpened:false};S.activeMission=null;if(ui.screen==='mission')ui.screen='home';save()}}
function render(){dayCheck();app.innerHTML=!S.onboarded?onboard():screen();document.documentElement.style.overflow=ui.modal?'hidden':'';drawModal();if(storageWarning)toast('Прогресс пока не сохранён на устройстве.');}
function screen(){if(ui.screen==='parent'&&!ui.parentUnlocked)ui.screen='home';return ({home:home,world:world,family:family,parent:parent,mission:mission,reward:reward,chest:chest,find:findScreen,effort:effort}[ui.screen]||home)()}
function go(screen){ui.screen=screen;ui.modal=null;ui.helpLevel=0;if(screen!=='parent')ui.parentUnlocked=false;render();window.scrollTo({top:0,behavior:'instant'})}
function showModal(type){ui.modal=type;drawModal();document.documentElement.style.overflow='hidden';requestAnimationFrame(()=>modal.querySelector('button,input')?.focus())}
function closeModal(){ui.modal=null;ui.pin='';ui.helpLevel=0;drawModal();document.documentElement.style.overflow='';}
function home(){const m=next(S),night=new Date().getHours()>=21||new Date().getHours()<6,ready=chestReady(S),count=completed(S);let speech=ready?'Смотри, наш сундук открылся!':m?`Привет! Давай сделаем одно маленькое дело?`:'Все дела готовы. Побудем дома?';if(night&&!m)speech='Тихий вечер. Можно отдыхать.';if(!enabled(S).length)speech='Позовём взрослого выбрать первое дело?';return `<section class="home ${night?'night':''}">${roomBg()}<header class="home-header">${avatar()}<div class="name"><b>Привет, ${esc(S.child.name)}!</b><small>Твой друг уже ждёт</small></div><div class="pill" style="color:#513c42"><span class="heart">♥</span>${S.child.hp}</div>${round('⚙','parent','Для взрослого')}</header><div class="home-progress"><span class="heart">♥</span>${meter(count,Math.max(1,enabled(S).length))}<small>${count} из ${enabled(S).length}<br>дел сегодня</small></div><div class="hero-stage"><div class="speech" id="speech">${speech}</div><button class="hero-button" data-action="pet" aria-label="Погладить ${name()}">${heroArt(night&&!m?'sleeping':'idle')}</button></div><button class="mission-banner" data-action="${ready?'chest':m?'start':enabled(S).length?'world':'parent'}" ${m?`data-id="${m.id}"`:''}>${obj(ready?'chest':m?.art||'plant')}<span class="copy"><small>${ready?'Три шага к новой находке':m?`Следующая миссия · ${m.minutes} мин · +${m.hp} HP`:'На сегодня всё'}</small><b>${ready?'Открыть сундук':m?esc(m.title):enabled(S).length?'Заглянуть в мой мир':'Выбрать миссии со взрослым'}</b></span><span class="arrow">›</span></button><nav class="game-dock" aria-label="Игровой мир"><button data-action="chest"><span class="dock-art">${obj('chest')}</span>Сокровища</button><button data-action="family"><span class="dock-art">${obj('team')}</span>Команда</button><button data-action="wardrobe"><span class="dock-art">${obj('shirt')}</span>Гардероб</button><button data-action="world"><span class="dock-art room-icon"></span>Мой мир</button></nav></section>`}
function charactersGrid(){return `<div class="character-grid">${characters.map(([id,n])=>`<button class="character-card ${id===S.child.character?'selected':''}" data-action="character" data-id="${id}" aria-pressed="${id===S.child.character}">${pet(id)}<b>${n}</b>${id===S.child.character?'<span class="selected-mark">✓</span>':''}</button>`).join('')}</div>`}
function onboard(){const i=S.onboarding.step;let content='',footer='';
 if(i===0){content=`<div class="logo">M<span>★</span>KI</div><div class="ob-art">${pet('moki','happy')}</div><h1>Маленькие дела.<br>Большие приключения.</h1><p>Уютный мир, который растёт<br>вместе с самостоятельностью.</p>`;footer=button('Начать со взрослым','ob-next');}
 if(i===1){content=`<h1>С чего начнём?</h1><p>Выберите до трёх миссий на день.<br>Остальные можно добавить позже.</p><div class="choices">${[['bag','Рюкзак без суеты'],['room','Уютная комната'],['reading','Время для книги'],['morning_teeth','Спокойное утро'],['evening_teeth','Вечерняя забота']].map(([id,title])=>{const m=missions.find(m=>m.id===id),on=S.missionSettings[id].enabled;return `<button class="choice ${on?'selected':''}" data-action="ob-mission" data-id="${id}" aria-pressed="${on}">${obj(m.art)}<div><b>${title}</b><small>${m.minutes} мин · ${m.hp} HP</small></div><span class="check">${on?'✓':''}</span></button>`}).join('')}</div>`;footer=button('Дальше','ob-next','purple',enabled(S).length?'':'disabled');}
 if(i===2){content=`<h1>Сколько помощи<br>нужно сейчас?</h1><p>Начнём с комфортного уровня.<br>Его можно менять постепенно.</p><div class="choices">${[['0','Вместе','Взрослый рядом на старте'],['1','По шагам','Одно короткое действие на экране'],['2','Почти сам','Короткий план, помощь по запросу']].map(([id,n,d])=>`<button class="choice ${S.onboarding.support===Number(id)?'selected':''}" data-action="ob-support" data-id="${id}" aria-pressed="${S.onboarding.support===Number(id)}"><div><b>${n}</b><small>${d}</small></div><span class="check">${S.onboarding.support===Number(id)?'✓':''}</span></button>`).join('')}</div>`;footer=button('Дальше','ob-next');}
 if(i===3){content=`<h1>Знакомство<br>со взрослым</h1><p>Имя — для приветствия.<br>PIN — для настроек и семейных дел.</p><label class="field">Как обращаться к ребёнку?<input id="child-name" maxlength="24" autocomplete="off" placeholder="Имя или игровой ник" value="${esc(S.child.name==='Друг'?'':S.child.name)}"></label><label class="field">Придумайте PIN из 4 цифр<input id="new-pin" type="password" inputmode="numeric" maxlength="4" autocomplete="new-password" placeholder="4 цифры"></label><p class="fineprint">PIN защищает настройки от случайного входа. Игра и прогресс хранятся на этом устройстве.</p><div class="error" id="setup-error" role="alert"></div>`;footer=button('Сохранить','ob-save');}
 if(i===4){content=`<h1>Значок исследователя</h1><p>Фото необязательно. Оно останется<br>на этом устройстве и не попадёт друзьям.</p><div style="display:grid;place-items:center">${avatar('child',false,'large')}</div>${button('Добавить фото','photo','quiet')}<p class="fineprint">Фото добавляет взрослый. Вместо него всегда можно оставить игрового героя.</p>`;footer=button('Дальше','ob-next');}
 if(i===5){content=`<div class="ob-art">${pet('moki','helping')}</div><h1>Теперь телефон<br>можно передать ребёнку</h1><p>Моки очень хочет познакомиться!</p>`;footer=button('Я здесь!','ob-next','gold');}
 if(i===6){content=`<h1>Кто станет<br>твоим другом?</h1><p>Каждый герой особенный.<br>Выбери того, кто тебе ближе.</p>${charactersGrid()}`;footer=button('Продолжить →','ob-next');}
 if(i===7){content=`<h1>Где начнётся<br>приключение?</h1><p>Выбери дом для себя и друга.<br>Мир можно менять в любое время.</p>${worldsGrid()}`;footer=button('Поселиться здесь','ob-next');}
 if(i===8){const m=next(S);content=`<div class="ob-art">${pet(S.child.character,'excited')}</div><h1>Ну что, ${esc(S.child.name)},<br>попробуем?</h1><p>${m?`Первая миссия: «${esc(m.title)}».<br>Я покажу только один шаг за раз.`:'Давай сначала посмотрим наш дом.'}</p>`;footer=button('Вперёд!','ob-finish','primary');}
 return `<section class="onboard ${i===0?'intro':''}"><div class="ob-top">${i?round('‹','ob-back','Предыдущий шаг'):''}<div class="ob-progress" aria-label="Шаг ${i+1} из 9">${Array.from({length:9},(_,n)=>`<i class="${n<=i?'on':''}"></i>`).join('')}</div></div><div class="ob-content">${content}</div>${footer}</section>`;
}
function mission(){const a=S.activeMission,m=missions.find(m=>m.id===a?.id);if(!m){ui.screen='home';return home()}if(a.phase==='effort')return effort();const simple=S.missionSettings[m.id].support===2;return `<section class="mission-page">${roomBg()}<header class="mission-top">${round('×','pause','Закрыть миссию, сохранив шаг')}${meter(a.step,3)}<span>${a.step+1}/3</span></header><div class="mission-title">${obj(m.art)}<h1>${esc(m.title)}</h1></div><div class="mission-center"><div class="step-card"><div class="eyebrow">${S.missionSettings[m.id].support===0?'Можно позвать взрослого':'Один маленький шаг'}</div><h2>${esc(m.steps[a.step].text)}</h2>${simple?'':`<p style="margin-top:10px">${a.step===0?'Начнём с этого. Остальное — потом.':a.step===1?'Отлично. Теперь следующий шаг.':'Ещё чуть-чуть — и готово.'}</p>`}</div>${pet(S.child.character,a.hints.some(h=>h.step===a.step)?'helping':'idle')}</div><div class="mission-actions">${button('Помощь','help','purple')}${button('Готово!','step','primary')}</div></section>`}
function effort(){return `<section class="reward-page"><div class="eyebrow">Все три шага готовы</div>${pet(S.child.character,'happy')}<h1>Как тебе было?</h1><p>Любой ответ подходит.</p><div class="effort-options">${[['easy','happy','Легко'],['ok','idle','Нормально'],['hard','thinking','Сложно']].map(([id,p,n])=>`<button data-action="effort" data-id="${id}">${pet(S.child.character,p)}${n}</button>`).join('')}</div></section>`}
function reward(){const h=ui.reward;return `<section class="reward-page"><div class="eyebrow">Маленькая победа</div><h1>Получилось!</h1>${pet(S.child.character,'celebrate')}<div class="reward-hp"><span class="heart">♥</span> +${h?.hp||0} HP</div><p>${esc(missions.find(m=>m.id===h?.missionId)?.title||'Миссия')} — готово.<br>Наш мир стал немного уютнее.</p>${button(chestReady(S)?'Посмотреть сундук':'К своему герою',chestReady(S)?'chest':'home','gold')}<small class="muted">Можно вернуться к игре позже.</small></section>`}
function chest(){const ready=chestReady(S);return `<section class="reward-page"><div class="eyebrow">Твои сокровища</div>${obj('chest',`big ${ready?'chest-shake':''}`)}<h1>${ready?'Что же внутри?':S.day.chestOpened?'Сегодняшняя находка уже дома':'Сундук ждёт своих приключений'}</h1><p>${ready?'Новая находка останется с тобой навсегда.':S.day.chestOpened?'Загляни в комнату и попробуй её потрогать.':`Заверши ${chestGoal(S)} миссии в любой удобный момент. Сейчас готово ${Math.min(chestGoal(S),completed(S))}.`}</p>${ready?button('Открыть','reveal','gold'):button(S.day.chestOpened?'Посмотреть находку':'К своему герою',S.day.chestOpened?'world':'home','purple')}${ready?button('Открыть позже','home','text'):''}</section>`}
function findScreen(){const f=ui.find;return `<section class="reward-page"><div class="eyebrow">Это твоё навсегда</div><h1>${esc(f?.[1]||'Новая радость')}</h1>${f?.[0]==='reaction'?pet(S.child.character,'celebrate'):obj(f?.[0]||'plant','big')}<p>${esc(f?.[2]||'Маленький праздник в нашем доме.')}</p>${button('Посмотреть в мире','world','gold')}</section>`}
function world(){const t=ui.worldTab;return `<section class="world-page"><div class="world-scene">${roomBg()}${pageHead('Мой мир',worlds.find(w=>w[0]===S.child.theme)?.[2]||'Лесная хижина')}<button class="hero-button" data-action="pet" aria-label="Погладить ${name()}">${heroArt()}</button>${S.child.placed.map(id=>`<button class="placed ${id}" data-action="item-react" data-id="${id}" aria-label="${esc(finds.find(f=>f[0]===id)?.[1]||id)}">${obj(id)}</button>`).join('')}</div><div class="world-drawer"><div class="tabs" role="tablist">${[['items','Находки'],['wardrobe','Гардероб'],['characters','Герои'],['worlds','Миры']].map(([id,n])=>`<button role="tab" aria-selected="${id===t}" class="${id===t?'on':''}" data-action="world-tab" data-id="${id}">${n}</button>`).join('')}</div>${!S.child.collection.length?`<div class="world-empty">${obj('plant')}<p>Твой первый предмет появится после ${chestGoal(S)} миссий. А уютный дом уже здесь.</p></div>`:''}${t==='worlds'?worldsGrid():t==='characters'?charactersGrid():`<div class="item-grid">${finds.filter(f=>t==='wardrobe'?['hat','glasses','scarf'].includes(f[0]):!['hat','glasses','scarf'].includes(f[0])).map(([id,n],i)=>{const owned=S.child.collection.includes(id),on=t==='wardrobe'?S.child.accessory===id:S.child.placed.includes(id);return `<button class="item-card ${owned?'':'locked'} ${on?'selected':''}" data-action="${t==='wardrobe'?'wear':'place'}" data-id="${id}" aria-pressed="${on}">${obj(id)}<b>${n}</b><small>${owned?on?'Выбрано':'Нажми, чтобы выбрать':`Находка ${finds.findIndex(f=>f[0]===id)+1}`}</small></button>`}).join('')}</div>`}${t==='wardrobe'&&S.child.accessory?button('Снять аксессуар','unwear','text'):''}${t==='characters'?`<p class="fineprint" style="text-align:center;margin-top:18px">Все друзья доступны. Героя можно менять в любое время.</p>`:''}</div></section>`}
function family(){const total=familyTotal(S),left=Math.max(0,S.family.bossMax-(total-S.family.bossBase)),members=[{id:'child',name:S.child.name,hp:S.child.hp},...S.family.members];return `<section class="page">${pageHead('Наша команда','Вместе мы сильнее!')}<div class="family-members">${members.map(m=>`<div class="member">${avatar(m.id,true)}<b>${esc(m.name)}</b><small>${m.hp} HP</small></div>`).join('')}<div class="member"><button class="round" data-action="invite" aria-label="Добавить члена семьи">+</button><b>Позвать</b></div></div><section class="panel family-goal"><span class="heart">♥</span><div><h2>Семейная цель</h2>${meter(total,S.family.goal)}<p>${total} / ${S.family.goal} HP · ${total>=S.family.goal?'Получилось вместе!':'Каждое дело помогает'}</p></div>${obj('chest')}</section><section class="boss-card"><div class="boss-top">${pet('nori',left?'thinking':'happy')}<div><h2>${left?'Облачный Ворчун':'Ворчун улыбается!'}</h2><p>${left?'Каждое полезное дело делает тучку меньше.':'Вы справились вместе. Можно отдыхать.'}</p></div></div>${meter(S.family.bossMax-left,S.family.bossMax,'purple')}<small>${left?`${left} HP до солнечного настроения`:'Командная победа'}</small><div class="row">${button('Твой ход','nudge','quiet')}${button('Вызов','challenge','purple')}</div></section>${S.family.challenge?`<section class="panel challenge-card"><h3>${S.family.challenge.active?'Дружеский вызов':S.family.challenge.winner==='child'?'Ты закончил первым!':'Взрослый закончил первым!'}</h3><p>${esc(S.child.name)}: ${esc(missions.find(m=>m.id===S.family.challenge.childMission)?.title)}</p><p>${esc(S.family.members.find(m=>m.id===S.family.challenge.member)?.name)}: ${esc(S.family.challenge.adultTask)}</p><small>${S.family.challenge.active?'У каждого своё дело. Можно закончить в своём темпе.':'Спасибо друг другу за компанию. Очки у каждого за своё дело.'}</small></section>`:''}<section class="panel">${S.family.feed.length?`<h3 style="margin-bottom:10px">Маленькие победы</h3>${S.family.feed.slice(0,6).map(f=>`<div class="feed-row">${avatar(f.member,true)}<div><b>${esc(f.member==='child'?S.child.name:S.family.members.find(m=>m.id===f.member)?.name||'Участник')}</b><p>${esc(f.task)}</p></div><span class="gain">${f.hp?`+${f.hp} HP`:'✓'}</span></div>`).join('')}`:`<div class="empty">${obj('team')}<h3>Первое дело — начало команды</h3><p>${S.family.members.length?'Сделайте каждый по маленькому делу. Здесь появятся ваши победы.':'Позови взрослого. У каждого будет своё дело, а цель — общая.'}</p>${button(S.family.members.length?'К своей миссии':'Позвать взрослого',S.family.members.length?'home':'invite','quiet')}</div>`}</section>${button('Что увидит друг?','friend','text')}</section>`}
function parent(){const tab=ui.parentTab,h=S.history.filter(h=>!h.legacy&&h.date===dateKey()),tabs=[['today','Сегодня'],['missions','Миссии'],['skills','Навыки'],['family','Семья'],['character','Персонаж'],['privacy','Настройки']];let content='';
 if(tab==='today')content=`<section class="panel"><div class="eyebrow">${esc(S.child.name)} · сегодня</div><h2 style="margin-top:10px">${h.length?'Есть маленькие победы':'Начните с одного дела'}</h2><p>${h.length?`Завершено ${h.length} из ${enabled(S).length} выбранных миссий.`:'Выберите удобное время. Ребёнку достаточно одной миссии за раз.'}</p><div class="metric-grid"><div class="metric"><strong>${h.length}</strong><small>миссий завершено</small></div><div class="metric"><strong>${h.reduce((n,x)=>n+x.hints,0)}</strong><small>обращений за помощью</small></div></div>${meter(h.length,Math.max(1,enabled(S).length))}</section><section class="panel"><h3>Что это говорит о самостоятельности?</h3><p>${h.length?`${h.filter(x=>x.scaffolding===0).length} миссий закончены без помощи внутри игры.`:'После первых миссий здесь появятся наблюдения.'}</p><p class="fineprint">Игра не знает, напоминали ли вы устно. Отсутствие подсказок не доказывает самостоятельный старт.</p></section><section class="panel"><h3>Сегодня в плане</h3>${enabled(S).map(m=>`<div class="mission-row">${obj(m.art)}<div><b>${m.title}</b><small>${S.day.completed[m.id]?'Готово':`${m.minutes} мин · ${m.hp} HP`}</small></div><span>${S.day.completed[m.id]?'✓':'—'}</span></div>`).join('')}</section>`;
 if(tab==='missions')content=`<p style="margin-bottom:15px">Короткий маршрут помогает начать. Выбирайте столько, сколько семье сейчас удобно.</p>${categories.map(c=>`<h3 class="section-title">${c}</h3><section class="panel">${missions.filter(m=>m.category===c).map(m=>`<div class="mission-row">${obj(m.art)}<div><b>${m.title}</b><small>3 шага · ${m.minutes} мин · ${m.hp} HP</small><select class="support-select" data-support="${m.id}" aria-label="Уровень помощи: ${m.title}">${['Вместе','По шагам','Почти сам'].map((n,i)=>`<option value="${i}" ${S.missionSettings[m.id].support===i?'selected':''}>${n}</option>`).join('')}</select></div><button class="toggle" role="switch" aria-label="${m.title}" aria-checked="${S.missionSettings[m.id].enabled}" data-action="toggle-mission" data-id="${m.id}"></button></div>`).join('')}</section>`).join('')}`;
 if(tab==='skills')content=`<section class="panel"><h2>Самостоятельность по шагам</h2><p>Смотрим на повторения и поддержку, без оценок «хорошо» и «плохо».</p>${enabled(S).map(m=>{const a=skillSummary(S,m.id);return `<div class="skill"><h3>${m.title}</h3><p>${a.count?`${a.count} завершений · ${a.independent} без подсказок · ${a.hints} обращений за помощью`:'Пока мало наблюдений. Начните с одной попытки.'}</p>${a.canFade?`<p>Четыре раза подряд получилось без подсказок. Можно попробовать более короткий план.</p>${button('Уменьшить помощь','fade','quiet',`data-id="${m.id}"`)}`:a.needsSupport?`<p>Последние два раза было сложно. Попробуйте начать вместе.</p>${button('Добавить поддержку','support-more','quiet',`data-id="${m.id}"`)}`:''}</div>`}).join('')}</section><div class="notice">Длительность включает паузы и время вне приложения. Она не используется как оценка ребёнка. Внешние напоминания автоматически не измеряются.</div>`;
 if(tab==='family')content=`<section class="panel"><h2>Семья на одном устройстве</h2><p>Добавьте участников и отмечайте взрослые дела здесь. Интернет-приглашения пока не подключены.</p>${button('Добавить участника','add-member','quiet')}<div style="margin-top:18px">${S.family.members.map(m=>`<div class="mission-row">${avatar(m.id,true)}<div><b>${esc(m.name)}</b><small>${m.hp} HP</small></div><button class="round" data-action="adult-task" data-id="${m.id}" aria-label="Отметить дело ${esc(m.name)}">+</button></div>`).join('')}</div></section><section class="panel"><h3>Общая цель</h3><label class="field" style="margin-top:12px">HP до общей победы<input id="family-goal" type="number" min="10" max="10000" value="${S.family.goal}"></label>${button('Сохранить цель','save-goal','quiet')}<p>Новая цель не уменьшает заработанные HP.</p></section>${familyTotal(S)-S.family.bossBase>=S.family.bossMax?button('Новая тучка для команды','boss-reset','quiet'):''}`;
 if(tab==='character')content=`<section class="panel"><h2>Друг ребёнка</h2><p style="margin-bottom:20px">Выбор можно менять без потери прогресса.</p>${charactersGrid()}</section><section class="panel"><h3>Значок исследователя</h3><div style="display:grid;place-items:center;padding:20px">${avatar('child',false,'large')}</div>${button('Добавить или заменить фото','photo','quiet')}${S.child.portrait?button('Вернуть игровой аватар','remove-photo','text'):''}<p class="fineprint">Фото хранится локально. Друзья его не видят.</p></section>`;
 if(tab==='privacy')content=`<section class="panel"><h2>Спокойные настройки</h2>${[['sound','Звуки','Короткий звук после успеха'],['haptics','Тактильный отклик','Если устройство поддерживает вибрацию'],['photoFamily','Фото на экране семьи','По умолчанию — игровой аватар']].map(([id,n,d])=>`<div class="settings-row"><div><b>${n}</b><p>${d}</p></div><button class="toggle" role="switch" aria-label="${n}" aria-checked="${S.settings[id]}" data-action="setting" data-id="${id}"></button></div>`).join('')}<p class="fineprint">На iPhone браузер может не поддерживать вибрацию. Уменьшение движения берётся из настроек устройства.</p></section><section class="panel"><h3>Данные ребёнка</h3><p>Фото, миссии и прогресс хранятся в этом браузере. Аккаунтов, свободного чата и передачи фото друзьям нет.</p><p>Очистка данных браузера удалит локальный прогресс. Между устройствами он пока не синхронизируется.</p>${button('Что увидит друг?','friend','quiet')}</section><section class="panel"><h3>Вход для взрослого</h3><p>Настройки закрываются при выходе из режима и сворачивании приложения. PIN — локальная защита от случайного доступа, не шифрование данных.</p>${button('Изменить PIN','change-pin','quiet')}</section><p class="fineprint">MOKI · единое игровое ядро · 2026-09-08</p>`;
 return `<section class="page parent-page">${pageHead('Для взрослого','Спокойно растим самостоятельность')}<nav class="tabs parent-tabs" aria-label="Разделы для взрослого">${tabs.map(([id,n])=>`<button class="${tab===id?'on':''}" data-action="parent-tab" data-id="${id}" aria-current="${tab===id?'page':'false'}">${n}</button>`).join('')}</nav>${content}</section>`;
}
function drawModal(){if(!ui.modal){modal.innerHTML='';return}let title='',body='';const a=S.activeMission,m=missions.find(m=>m.id===a?.id);
 if(ui.modal==='help'){title=ui.helpLevel?'Попробуем так':'Как помочь?';body=ui.helpLevel?`${pet(S.child.character,'helping','big')}<h2 class="center">${esc(ui.helpLevel===1?m.steps[a.step].hint:ui.helpLevel===2?m.steps[a.step].show:'Позови взрослого. Сделайте этот шаг вместе.')}</h2><p class="center">Дальше можно снова попробовать самому.</p>${button('К моему шагу','close-modal','primary')}`:`${pet(S.child.character,'thinking','big')}<div class="stack">${button('Дай намёк','help-level','quiet','data-id="1"')}${button('Покажи первый шаг','help-level','quiet','data-id="2"')}${button('Сделаем вместе','help-level','quiet','data-id="3"')}</div>`;}
 if(ui.modal==='pause'){title='Сделаем паузу?';body=`<p>Твой шаг сохранится. Вернёшься — продолжим с него.</p>${button('Продолжить миссию','close-modal','primary')}${button('Вернуться домой','home','text')}`;}
 if(ui.modal==='gate'){title='Для взрослого';body=`<p class="center">Введите свой PIN.</p><div class="pin-dots" aria-label="Введено ${ui.pin.length} цифр">${'●'.repeat(ui.pin.length)}${'○'.repeat(4-ui.pin.length)}</div><div class="pin-pad">${['1','2','3','4','5','6','7','8','9','⌫','0','×'].map(n=>`<button data-action="pin-key" data-id="${n}" aria-label="${n==='⌫'?'Удалить цифру':n==='×'?'Отмена':n}">${n}</button>`).join('')}</div><p class="error center" id="pin-error" role="alert"></p>`;}
 if(ui.modal==='invite'){title='Позовём взрослого';body=`${obj('team','big')}<p>Попроси взрослого добавить семью. Можно играть по очереди на этом устройстве.</p>${button('Открыть режим взрослого','parent','purple')}`;}
 if(ui.modal==='nudge'){title='Поддержи команду';body=S.family.members.length?`<p>Выбери короткую реакцию. Она появится на семейном экране этого устройства.</p><div class="stack">${['Твой ход','Я тебя догоняю','Давай вместе','Ещё одно','Красиво!'].map((n,i)=>button(n,'send-nudge','quiet',`data-id="${i}"`)).join('')}</div>`:`${obj('team','big')}<p>Сначала попроси взрослого добавить участника команды.</p>${button('Позвать взрослого','parent')}`;}
 if(ui.modal==='challenge'){title='Вызов на двоих';body=S.family.members.length&&next(S)?`<p>Твоё дело: ${esc(next(S).title)}.<br>Взрослый выберет своё в режиме для взрослых.</p>${button('Выбрать вместе со взрослым','parent')}`:`<p>${!S.family.members.length?'Для вызова нужен ещё один участник.':'На сегодня твои дела готовы. Новый вызов можно начать завтра.'}</p>${button('Понятно','close-modal','quiet')}`;}
 if(ui.modal==='friend'){title='Что увидит друг';const f=friendFeed(S)[0];body=`<p>Только категория и HP. Конкретные дела и фото остаются внутри семьи.</p><div class="privacy-sample">${esc(f?.name||S.child.name)} · +${f?.hp||5} HP · ${esc(f?.category||'Учёба')}</div><p class="fineprint">Это пример безопасного отображения. Подключение друзей и обмен между устройствами пока недоступны.</p>${button('Понятно','close-modal','quiet')}`;}
 if(ui.modal==='add-member'){title='Новый участник';body=`<label class="field">Имя или роль<input id="member-name" maxlength="24" placeholder="Например, папа"></label><label class="field" style="margin-top:12px">Игровой аватар<select id="member-character">${characters.map(([id,n])=>`<option value="${id}">${n}</option>`).join('')}</select></label><p>Участник появится на семейном экране этого устройства.</p>${button('Добавить','save-member')}`;}
 if(ui.modal==='adult-task'){title='Дело взрослого';body=`<label class="field">Что планируете сделать?<input id="adult-task" maxlength="80" placeholder="Например, 20 минут прогулки" value="${esc(S.family.challenge?.active&&S.family.challenge.member===ui.member?S.family.challenge.adultTask:'')}"></label><label class="field" style="margin-top:12px">Размер дела<select id="adult-hp"><option value="3">Маленькое · 3 HP</option><option value="5" selected>Обычное · 5 HP</option><option value="8">Сложное · 8 HP</option></select></label><p>Отметьте только реально сделанное дело.</p>${button('Дело готово','adult-done','primary')}${next(S)?button('Начать вызов с ребёнком','create-challenge','quiet'):''}`;}
 if(ui.modal==='photo'){title='Приватный портрет';body=ui.photo?`<div class="crop-frame" style="--zoom:${ui.zoom};--x:${ui.x}%;--y:${ui.y}%"><img src="${ui.photo}" alt="Предпросмотр обрезки"></div><label class="field">Приближение<input type="range" data-crop="zoom" min="1" max="2.5" step="0.05" value="${ui.zoom}"></label><label class="field">Левее / правее<input type="range" data-crop="x" min="0" max="100" value="${ui.x}"></label><label class="field">Выше / ниже<input type="range" data-crop="y" min="0" max="100" value="${ui.y}"></label><p>Обрезка и сжатие выполняются на устройстве.</p>${button('Сохранить портрет','save-photo')}`:`<p>Выберите фото. Оно не отправляется на сервер. Можно оставить игровой аватар.</p><label class="btn purple upload">Выбрать фото<input type="file" id="photo-input" accept="image/jpeg,image/png,image/webp,image/heic" aria-label="Выбрать фото"></label>`;}
 if(ui.modal==='change-pin'){title='Новый PIN';body=`<label class="field">Четыре цифры<input id="replacement-pin" type="password" inputmode="numeric" maxlength="4" autocomplete="new-password"></label><p>Запомните PIN. Восстановления через аккаунт пока нет.</p>${button('Сохранить PIN','save-pin')}`;}
 modal.innerHTML=`<div class="modal-shell"><section class="dialog" role="dialog" aria-modal="true" aria-label="${title}"><div class="dialog-head"><h2>${title}</h2>${round('×','close-modal','Закрыть')}</div>${body}</section></div>`;
}
async function hashPin(pin,salt){const bytes=new TextEncoder().encode(`${salt}:${pin}`);return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function setPin(pin){S.settings.pinSalt=crypto.randomUUID();S.settings.pinHash=await hashPin(pin,S.settings.pinSalt)}
let busy=false;
document.addEventListener('click',async e=>{
 const b=e.target.closest('[data-action]');if(!b||b.disabled||busy)return;const action=b.dataset.action,id=b.dataset.id;feedback();
 const adultActions=['parent-tab','toggle-mission','fade','support-more','add-member','save-member','adult-task','adult-done','create-challenge','save-goal','boss-reset','setting','remove-photo','change-pin','save-pin'];if(adultActions.includes(action)&&!ui.parentUnlocked)return;
 if(['home','world','family'].includes(action)){go(action);return}
 if(action==='close-modal'){closeModal();return}
 if(action==='pet'){const hero=b;hero.innerHTML=heroArt('happy');hero.classList.add('reacting');const sp=document.querySelector('#speech');if(sp)sp.textContent='Как здорово, что ты здесь!';setTimeout(()=>{if(hero.isConnected){hero.innerHTML=heroArt();hero.classList.remove('reacting')}},1800);return}
 if(action==='theme'&&worlds.some(w=>w[0]===id)){S.child.theme=id;save();render();return}
 if(action==='ob-next'){if(S.onboarding.step===1&&!enabled(S).length)return;S.onboarding.step=Math.min(8,S.onboarding.step+1);save();render();window.scrollTo(0,0);return}
 if(action==='ob-back'){S.onboarding.step=Math.max(0,S.onboarding.step-1);save();render();return}
 if(action==='ob-mission'){const v=S.missionSettings[id];if(!v.enabled&&enabled(S).length>=3){toast('Выберите до трёх дел. Одно можно убрать.');return}v.enabled=!v.enabled;save();render();return}
 if(action==='ob-support'){S.onboarding.support=Number(id);save();render();return}
 if(action==='ob-save'){const n=document.querySelector('#child-name').value.trim(),pin=document.querySelector('#new-pin').value;if(!n||!/^\d{4}$/.test(pin)){document.querySelector('#setup-error').textContent='Укажите имя и PIN из четырёх цифр.';return}busy=true;try{await setPin(pin);S.child.name=n;for(const m of enabled(S))S.missionSettings[m.id].support=S.onboarding.support;S.onboarding.step=4;save();render()}catch{toast('Не удалось создать PIN. Попробуйте снова.')}finally{busy=false}return}
 if(action==='ob-finish'){S.onboarded=true;save();const m=next(S);if(m){start(S,m.id);save();go('mission')}else go('home');return}
 if(action==='character'){if(!characters.some(c=>c[0]===id))return;S.child.character=id;save();render();return}
 if(action==='start'){if(start(S,id)){save();go('mission')}return}
 if(action==='pause'){showModal('pause');return}
 if(action==='step'){if(advance(S)){save();render();feedback('step')}return}
 if(action==='help'){ui.helpLevel=0;showModal('help');return}
 if(action==='help-level'){const level=Number(id);if(help(S,level)){ui.helpLevel=level;save();drawModal()}return}
 if(action==='effort'){ui.reward=finish(S,id);if(ui.reward){save();go('reward');feedback('reward')}return}
 if(action==='chest'){go('chest');return}
 if(action==='reveal'){ui.find=openChest(S);if(ui.find){save();go('find');feedback('reward')}return}
 if(action==='wardrobe'){ui.worldTab='wardrobe';go('world');return}
 if(action==='world-tab'){ui.worldTab=id;render();return}
 if(action==='place'||action==='wear'){if(!S.child.collection.includes(id)){toast('Эта находка ждёт тебя в одном из следующих сундуков.');return}if(action==='wear'){S.child.accessory=S.child.accessory===id?null:id;toast(S.child.accessory?'Аксессуар выбран.':'Аксессуар снят.')}else{S.child.placed=S.child.placed.includes(id)?S.child.placed.filter(x=>x!==id):[...S.child.placed,id]}save();render();return}
 if(action==='unwear'){S.child.accessory=null;save();render();return}
 if(action==='item-react'){b.animate([{transform:'translateY(0)'},{transform:'translateY(-8px) rotate(4deg)'},{transform:'translateY(0)'}],{duration:450});toast(finds.find(f=>f[0]===id)?.[2]||'Твоя находка!');return}
 if(action==='parent'){ui.pin='';if(ui.parentUnlocked){ui.modal=null;ui.screen='parent';render()}else showModal('gate');return}
 if(action==='pin-key'){if(id==='×'){closeModal();return}if(Date.now()<ui.lockedUntil){toast('Подождите немного перед следующей попыткой.');return}if(id==='⌫')ui.pin=ui.pin.slice(0,-1);else if(ui.pin.length<4)ui.pin+=id;drawModal();if(ui.pin.length===4){busy=true;try{const ok=await hashPin(ui.pin,S.settings.pinSalt)===S.settings.pinHash;if(ok){ui.parentUnlocked=true;ui.modal=null;ui.pin='';ui.attempts=0;ui.screen='parent';render()}else{ui.pin='';ui.attempts++;if(ui.attempts>=5){ui.lockedUntil=Date.now()+30000;ui.attempts=0}drawModal();document.querySelector('#pin-error').textContent='PIN не подошёл. Попробуйте ещё раз.'}}finally{busy=false}}return}
 if(action==='parent-tab'){ui.parentTab=id;render();window.scrollTo(0,0);return}
 if(action==='toggle-mission'){S.missionSettings[id].enabled=!S.missionSettings[id].enabled;save();render();return}
 if(action==='fade'||action==='support-more'){S.missionSettings[id].support=action==='fade'?2:0;save();render();toast('Уровень помощи обновлён.');return}
 if(['invite','nudge','challenge','friend','add-member','change-pin'].includes(action)){showModal(action);return}
 if(action==='send-nudge'){const texts=['Твой ход','Я тебя догоняю','Давай вместе','Ещё одно','Красиво!'];const last=S.family.feed.find(f=>f.kind==='nudge');if(last&&Date.now()-last.at<60000){toast('Дадим команде минутку ответить.');return}S.family.feed.unshift({id:crypto.randomUUID(),kind:'nudge',member:'child',task:texts[Number(id)],hp:0,at:Date.now()});save();closeModal();render();return}
 if(action==='save-member'){const n=document.querySelector('#member-name').value.trim();if(!n){toast('Введите имя участника.');return}S.family.members.push({id:crypto.randomUUID(),name:n,character:document.querySelector('#member-character').value,hp:0});save();closeModal();render();return}
 if(action==='adult-task'){ui.member=id;showModal('adult-task');return}
 if(action==='adult-done'||action==='create-challenge'){const task=document.querySelector('#adult-task').value.trim(),hp=Number(document.querySelector('#adult-hp').value),member=S.family.members.find(m=>m.id===ui.member);if(!task||!member){toast('Опишите дело взрослого.');return}if(action==='create-challenge'){const m=next(S);if(!m)return;S.family.challenge={id:crypto.randomUUID(),member:member.id,childMission:m.id,adultTask:task,active:true,startedAt:Date.now()};}else{member.hp+=hp;S.family.feed.unshift({id:crypto.randomUUID(),member:member.id,category:'Дело взрослого',task,hp,at:Date.now()});if(S.family.challenge?.active&&S.family.challenge.member===member.id&&S.family.challenge.adultTask===task){S.family.challenge.active=false;S.family.challenge.winner=member.id}}save();closeModal();render();return}
 if(action==='save-goal'){const n=Number(document.querySelector('#family-goal').value);if(!Number.isInteger(n)||n<10||n>10000){toast('Введите цель от 10 до 10 000 HP.');return}S.family.goal=n;save();toast('Общая цель сохранена.');return}
 if(action==='boss-reset'){S.family.bossBase=familyTotal(S);save();render();return}
 if(action==='setting'){S.settings[id]=!S.settings[id];save();render();return}
 if(action==='photo'){if(S.onboarded&&!ui.parentUnlocked){showModal('gate');return}ui.photo=null;ui.zoom=1;ui.x=ui.y=50;showModal('photo');return}
 if(action==='save-photo'){if(S.onboarded&&!ui.parentUnlocked)return;await savePhoto();return}
 if(action==='remove-photo'){S.child.portrait=null;S.settings.photoFamily=false;save();render();return}
 if(action==='save-pin'){const pin=document.querySelector('#replacement-pin').value;if(!/^\d{4}$/.test(pin)){toast('Нужны четыре цифры.');return}await setPin(pin);save();closeModal();toast('PIN изменён.');return}
});
document.addEventListener('change',e=>{if(e.target.dataset.support&&ui.parentUnlocked){const id=e.target.dataset.support;S.missionSettings[id].support=Number(e.target.value);save()}if(e.target.id==='photo-input'){const file=e.target.files?.[0];if(!file)return;if(file.size>15*1024*1024){toast('Выберите фото меньше 15 МБ.');return}const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{ui.photo=r.result;ui.photoImage=im;drawModal()};im.onerror=()=>toast('Не получилось открыть фото. Попробуйте JPEG или PNG.');im.src=r.result};r.readAsDataURL(file)}});
document.addEventListener('input',e=>{const p=e.target.dataset.crop;if(p){ui[p]=Number(e.target.value);const frame=modal.querySelector('.crop-frame');frame.style.setProperty('--'+p,p==='zoom'?ui[p]:ui[p]+'%')}});
async function savePhoto(){const im=ui.photoImage;if(!im)return;const canvas=document.createElement('canvas');canvas.width=canvas.height=320;const ctx=canvas.getContext('2d');const scale=Math.max(320/im.width,320/im.height)*ui.zoom,w=im.width*scale,h=im.height*scale;ctx.drawImage(im,(320-w)*ui.x/100,(320-h)*ui.y/100,w,h);S.child.portrait=canvas.toDataURL('image/jpeg',.82);if(save()){ui.photo=null;ui.photoImage=null;closeModal();render();toast('Портрет сохранён только на этом устройстве.')}}
document.addEventListener('keydown',e=>{if(!ui.modal)return;if(e.key==='Escape'){closeModal();return}if(e.key==='Tab'){const nodes=[...modal.querySelectorAll('button,input,select')].filter(el=>!el.disabled);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){ui.parentUnlocked=false;if(ui.screen==='parent'){ui.screen='home';ui.modal=null;render()}}else{dayCheck();render()}});
window.addEventListener('storage',e=>{if(e.key===KEY){S=load(localStorage);ui.modal=null;ui.parentUnlocked=false;if(ui.screen==='parent')ui.screen='home';render();toast('Прогресс обновлён из другой вкладки.')}});
render();
