(()=>{
const BK='moki_v6_product',FK='moki_family_v1',VK='moki_v7_identity';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const read=(k,d={})=>{try{return {...d,...JSON.parse(localStorage.getItem(k)||'{}')}}catch(e){return {...d}}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}};
const names={moki:'Моки',tobi:'Тоби',runi:'Руни',bip:'Бип',nori:'Нори'};
const defaultColors={moki:'#38c895',tobi:'#f39a3e',runi:'#f48db3',bip:'#4f91e8',nori:'#8c6ddd'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let parentTab='today';
function B(){return read(BK)} function F(){return read(FK)} function V(){return read(VK,{character:'moki',accessory:'none',portrait:null,parentTab:'today'})}
function active(b){return (b.missions||[]).filter(m=>m.enabled).sort((a,b)=>(a.order||999)-(b.order||999))}
function next(b){return active(b).find(m=>!b.daily?.completed?.[m.id])}
function done(b){return active(b).filter(m=>b.daily?.completed?.[m.id]).length}
function totalHp(f){return (f.members||[]).reduce((n,m)=>n+(m.earned||0),0)}
function childHp(f){return (f.members||[]).find(m=>m.id==='child')?.earned||0}
function charSvg(type='moki',mood='happy'){
 const color=defaultColors[type]||'#38c895', sleep=mood==='sleep';
 if(type==='bip')return `<svg viewBox="0 0 220 240"><defs><linearGradient id="rb" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#ffffff"/><stop offset="1" stop-color="#bcd5f8"/></linearGradient></defs><ellipse cx="110" cy="205" rx="64" ry="20" fill="rgba(37,50,78,.12)"/><rect x="48" y="62" width="124" height="112" rx="40" fill="url(#rb)" stroke="#3f7bc7" stroke-width="5"/><rect x="61" y="75" width="98" height="68" rx="25" fill="#16243d"/><ellipse cx="87" cy="107" rx="8" ry="12" fill="#68d8ff"/><ellipse cx="133" cy="107" rx="8" ry="12" fill="#68d8ff"/><path d="M91 128Q110 142 129 128" stroke="#68d8ff" stroke-width="6" fill="none" stroke-linecap="round"/><rect x="72" y="168" width="26" height="42" rx="13" fill="#75aaf0"/><rect x="122" y="168" width="26" height="42" rx="13" fill="#75aaf0"/><path d="M110 62V34" stroke="#356dae" stroke-width="7" stroke-linecap="round"/><circle cx="110" cy="27" r="11" fill="#f5b52f"/><circle cx="52" cy="109" r="15" fill="#4e91e7"/><circle cx="168" cy="109" r="15" fill="#4e91e7"/></svg>`;
 if(type==='tobi')return `<svg viewBox="0 0 220 240"><defs><linearGradient id="fo" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#ffb04d"/><stop offset="1" stop-color="#e86f2f"/></linearGradient></defs><ellipse cx="110" cy="207" rx="70" ry="20" fill="rgba(74,46,22,.14)"/><path d="M45 85L31 28L77 60Q110 44 143 60L189 28L175 85Q190 105 184 145Q178 186 145 201L75 201Q42 186 36 145Q30 105 45 85Z" fill="url(#fo)"/><path d="M40 41L67 67L48 78Z" fill="#fff0df"/><path d="M180 41L153 67L172 78Z" fill="#fff0df"/><ellipse cx="80" cy="115" rx="20" ry="25" fill="#fff"/><ellipse cx="140" cy="115" rx="20" ry="25" fill="#fff"/><circle cx="82" cy="118" r="8" fill="#22283a"/><circle cx="138" cy="118" r="8" fill="#22283a"/><ellipse cx="110" cy="142" rx="22" ry="17" fill="#fff0df"/><ellipse cx="110" cy="136" rx="8" ry="6" fill="#302a29"/><path d="M88 155Q110 174 132 155" stroke="#302a29" stroke-width="7" fill="none" stroke-linecap="round"/><path d="M163 175Q205 168 189 134" stroke="#e86f2f" stroke-width="18" fill="none" stroke-linecap="round"/></svg>`;
 if(type==='runi')return `<svg viewBox="0 0 220 240"><defs><linearGradient id="pn" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#ffb1ce"/><stop offset="1" stop-color="#e66fa5"/></linearGradient></defs><ellipse cx="110" cy="207" rx="66" ry="19" fill="rgba(80,48,70,.12)"/><path d="M65 76Q38 38 56 16Q85 30 93 65" fill="url(#pn)"/><path d="M155 76Q182 38 164 16Q135 30 127 65" fill="url(#pn)"/><ellipse cx="110" cy="132" rx="72" ry="76" fill="url(#pn)"/><ellipse cx="82" cy="116" rx="19" ry="24" fill="#fff"/><ellipse cx="138" cy="116" rx="19" ry="24" fill="#fff"/><circle cx="84" cy="119" r="8" fill="#27283b"/><circle cx="136" cy="119" r="8" fill="#27283b"/><ellipse cx="110" cy="143" rx="8" ry="6" fill="#dc6d92"/><path d="M91 154Q110 171 129 154" stroke="#332b3a" stroke-width="6" fill="none" stroke-linecap="round"/><ellipse cx="60" cy="143" rx="14" ry="8" fill="#ff7ea9" opacity=".45"/><ellipse cx="160" cy="143" rx="14" ry="8" fill="#ff7ea9" opacity=".45"/></svg>`;
 if(type==='nori')return `<svg viewBox="0 0 220 240"><defs><linearGradient id="pu" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#a78af0"/><stop offset="1" stop-color="#7757c6"/></linearGradient></defs><ellipse cx="110" cy="208" rx="70" ry="20" fill="rgba(64,46,95,.12)"/><g fill="url(#pu)"><circle cx="58" cy="91" r="38"/><circle cx="84" cy="66" r="40"/><circle cx="122" cy="62" r="41"/><circle cx="158" cy="88" r="38"/><ellipse cx="110" cy="139" rx="77" ry="72"/></g><ellipse cx="110" cy="145" rx="42" ry="35" fill="#f2e8fb"/><path d="M72 118Q84 ${sleep?118:108} 96 118" stroke="#29263a" stroke-width="7" fill="none" stroke-linecap="round"/><path d="M124 118Q136 ${sleep?118:108} 148 118" stroke="#29263a" stroke-width="7" fill="none" stroke-linecap="round"/><ellipse cx="110" cy="140" rx="8" ry="6" fill="#44374e"/><path d="M96 151Q110 162 124 151" stroke="#44374e" stroke-width="5" fill="none" stroke-linecap="round"/></svg>`;
 return `<svg viewBox="0 0 220 240"><defs><linearGradient id="gr" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#62dfa9"/><stop offset="1" stop-color="#1ba66f"/></linearGradient></defs><ellipse cx="110" cy="209" rx="70" ry="20" fill="rgba(35,82,63,.14)"/><path d="M42 91Q27 47 49 26Q73 42 83 64Q110 50 137 64Q147 42 171 26Q193 47 178 91Q193 108 187 148Q181 187 149 203L71 203Q39 187 33 148Q27 108 42 91Z" fill="url(#gr)"/><path d="M52 49Q69 56 79 70L53 76Z" fill="#a9f0d2"/><path d="M168 49Q151 56 141 70L167 76Z" fill="#a9f0d2"/><ellipse cx="78" cy="117" rx="24" ry="31" fill="#fff"/><ellipse cx="142" cy="117" rx="24" ry="31" fill="#fff"/><ellipse cx="81" cy="122" rx="10" ry="13" fill="#20263a"/><ellipse cx="139" cy="122" rx="10" ry="13" fill="#20263a"/><circle cx="85" cy="117" r="4" fill="#fff"/><circle cx="143" cy="117" r="4" fill="#fff"/><ellipse cx="110" cy="147" rx="9" ry="7" fill="#20352f"/><path d="M85 160Q110 184 135 160" stroke="#20352f" stroke-width="8" fill="none" stroke-linecap="round"/><ellipse cx="58" cy="145" rx="16" ry="9" fill="#ff9fa9" opacity=".55"/><ellipse cx="162" cy="145" rx="16" ry="9" fill="#ff9fa9" opacity=".55"/><circle cx="50" cy="176" r="25" fill="#2ab77f"/><circle cx="170" cy="176" r="25" fill="#2ab77f"/></svg>`;
}
function heroHtml(type,mood='happy'){const v=V(),acc=v.accessory,photo=v.portrait;return `<div class="mk-hero" data-mk-pet>${charSvg(type,mood)}${acc==='hat'?'<span style="position:absolute;left:50%;top:-5px;transform:translateX(-50%);font-size:49px">🧢</span>':''}${acc==='glasses'?'<span style="position:absolute;left:50%;top:83px;transform:translateX(-50%);font-size:48px">👓</span>':''}${photo?`<span style="position:absolute;right:-6px;bottom:32px;width:44px;height:44px;border-radius:50%;overflow:hidden;border:4px solid #fff;box-shadow:0 4px 12px #0002"><img src="${photo}" style="width:100%;height:100%;object-fit:cover"></span>`:''}</div>`}
function userPhoto(){const v=V();return v.portrait?`<img src="${v.portrait}">`:`<span class="fallback">${charSvg(v.character)}</span>`}
function show(id){ensureFamily();$$('.screen').forEach(s=>s.classList.toggle('on',s.id===id));const top=$('#topbar');if(top)top.style.display=id==='parent'?'flex':'none';if(id==='home')renderHome();if(id==='collection')renderWorld();if(id==='family')renderFamily();if(id==='parent')renderParent();scrollTo({top:0,behavior:'smooth'})}
function ensureFamily(){if(!$('#family')){const m=document.createElement('main');m.id='family';m.className='screen';document.querySelector('.app-shell')?.insertBefore(m,$('#collection'))}}
function renderHome(){const root=$('#home');if(!root)return;const b=B(),f=F(),v=V(),m=next(b),d=done(b),a=active(b),hp=childHp(f),team=totalHp(f),pct=Math.min(100,Math.round(hp/100*100)),theme=b.child?.theme||'forest';root.innerHTML=`<div class="mk-screen"><div class="mk-home-head"><div class="mk-user"><div class="mk-user-photo">${userPhoto()}</div><div class="mk-user-copy"><b>Привет, ${esc(b.child?.name||'Макс')}! 👋</b><span>Сегодня отличный день!</span></div></div><div class="mk-score"><div class="mk-score-pill">❤️ ${hp}</div><button class="adult-button" data-action="parentGate">⚙️</button></div></div><section class="mk-scene ${theme}"><div class="mk-room-wall"></div><div class="mk-window"></div><div class="mk-shelf"></div><div class="mk-plant">🌿</div><div class="mk-note">Маленькие дела делают большой мир ♡</div><div class="mk-hpbar"><span class="heart">❤️</span><div class="mk-track"><i style="width:${pct}%"></i></div><span class="mk-hpnum">${hp} / 100</span></div><div class="mk-speech">${m?`Доброе утро! Готов к «${esc(m.title)}»?`:'На сегодня всё! Можно отдыхать 🌿'}</div><div class="mk-rug"></div>${heroHtml(v.character,m?'happy':'sleep')}${m?`<button class="mk-mission-banner" data-action="startMission" data-id="${m.id}"><span class="icon">${m.icon}</span><span class="copy"><small>Следующая миссия</small><b>${esc(m.title)}</b></span><span class="arrow">›</span></button>`:`<button class="mk-mission-banner" data-mk-go="collection"><span class="icon">🏡</span><span class="copy"><small>${d}/${a.length} сегодня</small><b>Посмотреть мой мир</b></span><span class="arrow">›</span></button>`}</section><nav class="mk-home-nav"><button data-action="chest"><span>🎁</span>Сокровища</button><button data-mk-go="family"><span>👨‍👩‍👧</span>Команда${team?` · ${team}`:''}</button><button data-mk-go="collection" data-scroll="wardrobe"><span>👕</span>Гардероб</button><button data-mk-go="collection"><span>🗺️</span>Мой мир</button></nav></div>`}
function renderWorld(){const root=$('#collection');if(!root)return;const b=B(),v=V(),col=b.child?.collection||[];const objs=[['plant','🌱','Растение'],['lantern','🏮','Фонарь'],['shelf','📚','Полка'],['bed','🛏️','Кровать'],['telescope','🔭','Телескоп'],['kite','🪁','Змей'],['crystal','🔮','Кристалл'],['chest','🧰','Сундук']];root.innerHTML=`<div class="mk-screen"><div class="mk-world-head"><button class="mk-back" data-mk-go="home">‹</button><div class="mk-page-title"><b>Мой мир</b><span>${b.child?.theme==='space'?'Космическая база':b.child?.theme==='ocean'?'Остров приключений':'Лесная хижина'}</span></div><button class="adult-button" data-action="parentGate">⚙️</button></div><section class="mk-world-scene"><div class="mk-room-wall"></div><div class="mk-window"></div><div class="mk-shelf"></div><div class="mk-plant">🌿</div><div class="mk-note">Здесь рождаются большие мечты ♡</div><div class="mk-rug"></div>${heroHtml(v.character,'sleep')}<div class="mk-world-menu"><button data-scroll="wardrobe"><span>👕</span>Гардероб</button><button><span>⭐</span>Коллекция</button><button><span>🏆</span>Достижения</button></div></section><div class="mk-object-row">${objs.map(([id,ic,n])=>`<div class="mk-object ${col.includes(id)?'':'locked'}"><div class="art">${ic}</div>${n}</div>`).join('')}</div><section id="wardrobe" style="margin-top:14px;background:#fff;border-radius:24px;padding:14px;box-shadow:0 12px 30px rgba(45,55,90,.08)"><b style="font-size:16px">Выбери героя</b><div style="display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-top:12px">${Object.keys(names).map(t=>`<button data-mk-char="${t}" style="border:${v.character===t?'3px solid #73c7ff':'0'};background:#f4f6fb;border-radius:16px;padding:6px"><div style="height:58px">${charSvg(t)}</div><small style="font-weight:850">${names[t]}</small></button>`).join('')}</div><label style="display:block;margin-top:12px;font-size:11px;font-weight:850">Фото ребёнка <input id="mkPhoto" type="file" accept="image/*" style="display:block;margin-top:7px;width:100%"></label></section></div>`}
function renderFamily(){ensureFamily();const root=$('#family');if(!root)return;const f=F(),b=B(),v=V(),members=f.members||[],total=totalHp(f),goal=f.goal||220,pct=Math.min(100,Math.round(total/goal*100)),boss=Math.max(0,(f.bossMax||260)-total);root.innerHTML=`<div class="mk-screen"><div class="mk-family-head"><button class="mk-back" data-mk-go="home">‹</button><div class="mk-page-title"><b>Наша команда</b><span>Вместе мы сильнее! 💪</span></div><button class="mk-back" data-family-action="adult">＋</button></div><section class="mk-family-hero"><div class="mk-avatars">${members.map(m=>`<div class="mk-member"><div class="avatar">${m.id==='child'?charSvg(v.character):m.avatar||'👤'}</div><b>${m.id==='child'?(b.child?.name||'Макс'):m.name}</b><span>${m.earned||0} HP</span></div>`).join('')}<div class="mk-member"><button class="avatar" data-family-action="adult">＋</button><b>Пригласить</b></div></div><div class="mk-family-progress"><div class="row"><span class="big">❤️</span><div style="flex:1"><b>Семейное HP</b><small>${total} / ${goal}</small><div class="mk-track" style="margin-top:7px"><i style="width:${pct}%"></i></div></div><span>🎁</span></div></div><div class="mk-boss"><div class="bossart">☁️</div><div class="copy"><b>Облачный Ворчун</b><p>Исчезает, когда мы вместе выполняем реальные миссии!</p><div class="mk-track"><i style="width:${Math.max(0,100-Math.round(boss/(f.bossMax||260)*100))}%"></i></div><small>${boss} HP осталось</small></div></div></section>${(f.feed||[])[0]?`<div class="mk-feed"><div class="avatar">${(f.feed[0].memberId==='child')?'🧒':'👩'}</div><div style="flex:1"><b>${(f.feed[0].memberId==='child')?(b.child?.name||'Макс'):'Кто-то из команды'} выполнил миссию!</b><span>+${f.feed[0].hp||0} к командному HP ⭐</span></div><span>❤️</span></div>`:''}</div>`}
function renderParent(){const root=$('#parent');if(!root)return;const b=B(),a=active(b),d=done(b),pct=a.length?Math.round(d/a.length*100):0;root.innerHTML=`<div class="mk-screen"><div class="mk-parent-head"><button class="mk-back" data-mk-go="home">‹</button><div class="mk-page-title"><b>Для взрослого</b></div><button class="adult-button">⚙️</button></div><nav class="mk-parent-tabs">${[['today','Сегодня'],['missions','Миссии'],['family','Семья'],['avatar','Персонаж']].map(([id,n])=>`<button class="${parentTab===id?'on':''}" data-mk-parent="${id}">${n}</button>`).join('')}</nav>${parentTab==='today'?parentToday(b,a,d,pct):parentTab==='missions'?parentMissions(b,a):parentTab==='family'?parentFamily():parentAvatar()}</div>`}
function parentToday(b,a,d,pct){return `<section class="mk-insight"><div class="top"><div style="display:flex;gap:9px;align-items:center"><span class="sun">☀️</span><div><b>Хороший день! ✨</b><p>${d} из ${a.length} миссий выполнено</p></div></div><div class="mk-ring" style="--p:${pct}%"><span>${pct}%</span></div></div><div class="mk-week">${['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map((x,i)=>`<div class="mk-day"><i style="--h:${i<3?'70%':'15%'}"></i>${x}</div>`).join('')}</div></section><div class="mk-stats"><div class="mk-stat"><span class="ico">👤</span><div><b>${b.metrics?.avgMins||3} мин</b><span>Среднее время</span></div></div><div class="mk-stat"><span class="ico">🎯</span><div><b>${b.metrics?.solo||0}</b><span>Без подсказок</span></div></div></div>${parentMissions(b,a)}`}
function parentMissions(b,a){return `<section class="mk-mission-list"><h3>Активные миссии</h3>${a.slice(0,8).map(m=>`<div class="mk-mission-row"><span class="ico">${m.icon}</span><span class="copy"><b>${esc(m.title)}</b><span>${m.support===0?'Вместе':m.support===1?'По шагам':'Почти сам'}</span></span><span class="mk-toggle"></span></div>`).join('')}</section>`}
function parentFamily(){const f=F();return `<section class="mk-insight"><b>Семейная игра</b><p>Команда набрала ${totalHp(f)} HP. Здесь можно добавлять взрослых и друзей, запускать вызовы и менять режим соревнования.</p><button class="button primary" data-mk-go="family">Открыть команду</button></section>`}
function parentAvatar(){const v=V();return `<section class="mk-insight"><b>Персонаж ребёнка</b><p>Выбран: ${names[v.character]}. Фото используется только как приватный медальон.</p><button class="button secondary" data-mk-go="collection" data-scroll="wardrobe">Изменить персонажа</button></section>`}
function patchOnboarding(){const wrap=$('#onboardingWrap');if(!wrap||!$('#onboarding')?.classList.contains('on'))return;wrap.classList.add('mk-onboarding');const txt=wrap.textContent||'';if(txt.includes('Каким будет наш мир?')||txt.includes('Выбери компаньона')){const v=V();const block=wrap.querySelector('.v7-onboard-character-block');if(block)block.innerHTML=`<h3 style="font-size:16px;margin:0 0 10px">Кто станет твоим другом?</h3><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:10px">${Object.keys(names).map(t=>`<button data-mk-char="${t}" style="border:${v.character===t?'3px solid #5ccca6':'0'};background:#fff;border-radius:20px;padding:8px;box-shadow:0 7px 18px #29345a12"><div style="height:78px">${charSvg(t)}</div><b>${names[t]}</b></button>`).join('')}</div>`}}
function handlePhoto(file){if(!file||!file.type.startsWith('image/'))return;const r=new FileReader();r.onload=()=>{const v=V();v.portrait=r.result;write(VK,v);renderWorld();renderHome()};r.readAsDataURL(file)}
function refresh(){const on=$('#onboarding');if(on?.classList.contains('on'))patchOnboarding();const activeScreen=$$('.screen.on')[0]?.id;if(activeScreen==='home')renderHome();else if(activeScreen==='collection')renderWorld();else if(activeScreen==='family')renderFamily();else if(activeScreen==='parent')renderParent()}
document.addEventListener('click',e=>{const go=e.target.closest('[data-mk-go]');if(go){show(go.dataset.mkGo);const sc=go.dataset.scroll;if(sc)setTimeout(()=>$('#'+sc)?.scrollIntoView({behavior:'smooth'}),80);return}const ch=e.target.closest('[data-mk-char]');if(ch){const v=V();v.character=ch.dataset.mkChar;write(VK,v);refresh();return}const pt=e.target.closest('[data-mk-parent]');if(pt){parentTab=pt.dataset.mkParent;renderParent();return}if(e.target.closest('[data-mk-pet]')){const sp=$('.mk-speech');if(sp)sp.textContent=['Я рядом! ✨','Давай одно маленькое дело?','Хочешь посмотреть мой мир?','Ты отлично справляешься!'][Math.floor(Math.random()*4)];return}const act=e.target.closest('[data-action]')?.dataset.action;if(act){setTimeout(refresh,160)}},true);
document.addEventListener('change',e=>{if(e.target.id==='mkPhoto')handlePhoto(e.target.files?.[0])});
setTimeout(()=>{ensureFamily();patchOnboarding();const on=$('#onboarding');if(!on?.classList.contains('on'))show('home')},500);
window.addEventListener('focus',()=>setTimeout(refresh,80));
})();