(()=>{
const BK='moki_v6_product', FK='moki_family_v1', VK='moki_v7_identity';
const A=window.MOKI_ART||{}, I=window.MOKI_ITEMS||{};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const rd=(k,d={})=>{try{return {...d,...JSON.parse(localStorage.getItem(k)||'{}')}}catch(e){return {...d}}};
const wr=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}};
const B=()=>rd(BK), F=()=>rd(FK), V=()=>rd(VK,{character:'moki',portrait:null,accessory:'none',portraitVisibleFamily:true});
const names={moki:'Моки',tobi:'Тоби',runi:'Руни',bip:'Бип',nori:'Нори'};
const traits={moki:'Любопытный',tobi:'Добрый',runi:'Смелый',bip:'Логичный',nori:'Игривый'};
const active=b=>(b.missions||[]).filter(m=>m.enabled).sort((x,y)=>(x.order||999)-(y.order||999));
const next=b=>active(b).find(m=>!b.daily?.completed?.[m.id]);
const done=b=>active(b).filter(m=>b.daily?.completed?.[m.id]).length;
const totalHp=f=>(f.members||[]).reduce((n,m)=>n+(m.earned||0),0);
const childHp=f=>(f.members||[]).find(m=>m.id==='child')?.earned||0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let parentTab='today';
function src(t){return A[t]||A.moki||''}
function item(id,fallback){return I[id]?`<img src="${I[id]}" alt="">`:`<span>${fallback}</span>`}
function hero(t,photo,extra=''){return `<div class="hero ${t} ${extra}" data-pet><img src="${src(t)}" alt="${names[t]||'Персонаж'}">${photo?`<span class="medal"><img src="${photo}" alt="Портрет"></span>`:''}</div>`}
function avatar(t,photo){return `<div class="ava ${photo?'':'pet'}">${photo?`<img src="${photo}" alt="">`:`<img src="${src(t)}" alt="${names[t]}">`}</div>`}
function marker(cls){return `<i class="${cls}" hidden aria-hidden="true"></i>`}
function show(id){$$('.screen').forEach(s=>s.classList.toggle('on',s.id===id));if(id==='home')home();if(id==='family')family();if(id==='collection')world();if(id==='parent')parent();scrollTo({top:0,behavior:'smooth'})}
function greeting(){const h=new Date().getHours();return h<11?'Доброе утро!':h<18?'Привет!':h<22?'Добрый вечер!':'Ещё не спишь?'}
function home(){
 const r=$('#home');if(!r)return;const b=B(),f=F(),v=V(),m=next(b),d=done(b),aa=active(b),hp=childHp(f),team=totalHp(f);
 r.innerHTML=`${marker('v7-home')}<div class="px"><div class="head"><div class="usr">${avatar(v.character,v.portrait)}<div class="uc"><b>Привет, ${esc(b.child?.name||'Макс')}! 👋</b><span>${d?`Уже ${d} маленьких побед`:'Сегодня отличный день!'}</span></div></div><div class="ha"><div class="hp">❤️ ${hp}</div><button class="gear" data-action="parentGate">⚙️</button></div></div><section class="room" style="--room-art:url('${window.MOKI_ROOM||''}')"><div class="bar"><span style="font-size:24px">❤️</span><div class="track"><i style="width:${Math.min(100,hp)}%"></i></div><span class="num">${hp} / 100</span></div><div class="note">Маленькие дела делают большой мир ♡</div><div class="speech">${m?`${greeting()} Готов к «${esc(m.title)}»?`:`На сегодня всё! ${names[v.character]} отдыхает 🌿`}</div><div class="rug"></div>${hero(v.character,v.portrait)}${m?`<button class="banner" data-action="startMission" data-id="${m.id}"><span class="ba">${item(/рюкзак/i.test(m.title)?'backpack':'',m.icon)}</span><span class="bc"><small>Следующая миссия</small><b>${esc(m.title)}</b></span><span class="arr">›</span></button>`:`<button class="banner" data-lite-go="collection"><span class="ba">${item('chest','🎁')}</span><span class="bc"><small>${d}/${aa.length} сегодня</small><b>Посмотреть мой мир</b></span><span class="arr">›</span></button>`}</section><nav class="nav"><button data-action="chest"><span class="ni">${item('chest','🎁')}</span>Сокровища</button><button data-lite-go="family"><span class="ni">👨‍👩‍👧</span>Команда${team?` · ${team}`:''}</button><button data-lite-go="collection" data-open-custom><span class="ni">${item('hat','👕')}</span>Гардероб</button><button data-lite-go="collection"><span class="ni">🗺️</span>Мой мир</button></nav></div>`;
}
function memberPic(m,b,v){if(m.id==='child')return v.portrait?`<div class="pic"><img src="${v.portrait}" alt=""></div>`:`<div class="pic pet"><img src="${src(v.character)}" alt=""></div>`;return `<div class="pic"><span style="font-size:27px">${m.avatar||'👤'}</span></div>`}
function family(){
 const r=$('#family');if(!r)return;const f=F(),b=B(),v=V(),ms=f.members||[],total=totalHp(f),goal=f.goal||220,pct=Math.min(100,Math.round(total/Math.max(1,goal)*100)),left=Math.max(0,(f.bossMax||260)-total),feed=(f.feed||[])[0];
 r.innerHTML=`<div class="px"><div class="ph"><button class="back" data-lite-go="home">‹</button><div class="pt"><b>Наша команда</b><span>Вместе мы делаем больше!</span></div><button class="back" data-family-action="adult" style="font-size:20px">＋</button></div><section class="card"><div class="members">${ms.map(m=>`<div class="mem">${memberPic(m,b,v)}<b>${esc(m.id==='child'?(b.child?.name||'Макс'):m.name)}</b><span>${m.earned||0} HP</span></div>`).join('')}<div class="mem"><button class="pic" data-family-action="adult" style="border:0;font-size:24px">＋</button><b>Пригласить</b></div></div><div class="fp"><div class="fr"><span style="font-size:34px">❤️</span><div class="fm"><b>Общий прогресс</b><small>${total} / ${goal} HP</small><div class="track" style="margin-top:7px"><i style="width:${pct}%"></i></div></div><span style="width:48px;height:48px;display:grid;place-items:center">${item('chest','🎁')}</span></div></div><div class="boss"><div class="bossart"><div class="cloudboss">☁️<span>😈</span></div></div><div class="copy"><b>Облачный Ворчун</b><p>Каждое полезное дело всей команды делает его слабее.</p><div class="track"><i style="width:${Math.max(5,100-Math.round(left/(f.bossMax||260)*100))}%"></i></div><small>${left} HP осталось</small></div></div><div class="fa"><button data-family-action="nudge">⚡ Подначить</button><button data-family-action="challenge">⚔️ Вызов</button></div></section><div class="feed"><div style="font-size:27px">${feed?'⭐':'🌱'}</div><div class="copy"><b>${feed?'Последнее действие команды':'Здесь появятся победы семьи'}</b><span>${feed?`+${feed.hp||0} HP`:'Сделайте первое полезное дело'}</span></div></div></div>`;
}
function charGrid(v){return `<div class="char-grid">${Object.keys(names).map(t=>`<button class="char-card ${v.character===t?'on':''}" data-px-char="${t}"><div class="char-art"><img src="${src(t)}" alt=""></div><b>${names[t]}</b><span>${traits[t]}</span>${v.character===t?'<em>✓</em>':''}</button>`).join('')}</div>`}
function customPanel(v){return `<section class="custom" id="custom"><div class="custom-head"><div><b>Образ героя</b><span>Выбери персонажа и добавь личный портрет</span></div></div>${charGrid(v)}<div class="portrait-card"><div class="portrait-preview">${v.portrait?`<img src="${v.portrait}">`:'📷'}</div><div class="portrait-copy"><b>${v.portrait?'Портрет добавлен':'Добавить фото ребёнка'}</b><span>Фото становится медальоном и не заменяет лицо героя</span></div><label class="upload">${v.portrait?'Заменить':'Добавить'}<input id="pxPhoto" type="file" accept="image/*" hidden></label></div><div class="acc-title">Аксессуары</div><div class="acc-row"><button class="acc ${v.accessory==='none'?'on':''}" data-px-acc="none"><span>✨</span>Без</button><button class="acc ${v.accessory==='hat'?'on':''}" data-px-acc="hat"><span>${item('hat','🧢')}</span>Шапка</button><button class="acc ${v.accessory==='glasses'?'on':''}" data-px-acc="glasses"><span>${item('glasses','👓')}</span>Очки</button><button class="acc ${v.accessory==='scarf'?'on':''}" data-px-acc="scarf"><span>${item('scarf','🧣')}</span>Шарф</button></div></section>`}
function world(){
 const r=$('#collection');if(!r)return;const v=V();
 r.innerHTML=`${marker('v7-world')}<div class="px"><div class="ph"><button class="back" data-lite-go="home">‹</button><div class="pt"><b>Мой мир</b><span>Твой уютный уголок</span></div><button class="gear" data-action="parentGate">⚙️</button></div><section class="world" style="--room-art:url('${window.MOKI_ROOM||''}')"><div class="rug"></div>${hero(v.character,v.portrait)}<div class="wm"><button data-open-custom><b>👕</b>Гардероб</button><button><b>⭐</b>Коллекция</button><button><b>🏆</b>Достижения</button></div></section><div class="world-items"><div class="wi">${item('plant','🌱')}<span>Растение</span></div><div class="wi">${item('lantern','🏮')}<span>Фонарь</span></div><div class="wi">${item('bed','🛏️')}<span>Кровать</span></div><div class="wi">${item('telescope','🔭')}<span>Телескоп</span></div></div>${customPanel(v)}</div>`;
}
function parent(){
 const r=$('#parent');if(!r)return;const b=B(),aa=active(b),d=done(b),pct=aa.length?Math.round(d/aa.length*100):0;
 r.innerHTML=`${marker('v7-parent-nav')}<div class="px"><div class="ph"><button class="back" data-lite-go="home">‹</button><div class="pt"><b>Для взрослого</b><span>Прогресс без давления</span></div><button class="gear">⚙️</button></div><nav class="tabs">${[['today','Сегодня'],['missions','Миссии'],['family','Семья'],['avatar','Персонаж']].map(([id,n])=>`<button class="${parentTab===id?'on':''}" data-pt="${id}">${n}</button>`).join('')}</nav>${parentTab==='today'?pToday(b,aa,d,pct):parentTab==='missions'?pMiss(aa):parentTab==='family'?`<div class="ins"><b>Семейная игра</b><p>Команда набрала ${totalHp(F())} HP. Ребёнок видит, что взрослые тоже делают свои дела.</p><button class="button primary violet" data-lite-go="family">Открыть команду</button></div>`:`<div class="ins"><b>Персонаж ребёнка</b><p>Сейчас выбран ${names[V().character]}. Персонажа и фото можно менять в Мире.</p><button class="button secondary" data-lite-go="collection" data-open-custom>Настроить образ</button></div>`}</div>`;
}
function pToday(b,aa,d,pct){return `<section class="ins"><div class="it"><div><b>☀️ Хороший день! ✨</b><div style="font-size:9px;color:#7d8494;font-weight:800;margin-top:3px">${d} из ${aa.length} миссий выполнено</div></div><div class="ring" style="--p:${pct}%"><b>${pct}%</b></div></div><div class="week">${['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map((x,i)=>`<div class="day"><i style="--h:${i<3?'72%':'18%'}"></i>${x}</div>`).join('')}</div></section><div class="stats"><div class="stat"><b>${b.metrics?.avgMins||3} мин</b><div style="font-size:8px;color:#7f8798">Среднее время</div></div><div class="stat"><b>${b.metrics?.solo||0}</b><div style="font-size:8px;color:#7f8798">Без подсказок</div></div></div>${pMiss(aa)}`}
function pMiss(aa){return `<section class="missions"><h3 style="margin:0 0 6px">Активные миссии</h3>${aa.slice(0,8).map(m=>`<div class="mr"><span style="font-size:24px">${m.icon}</span><div class="c"><b>${esc(m.title)}</b><span>${m.support===0?'Вместе':m.support===1?'По шагам':'Почти сам'}</span></div><span class="tog"></span></div>`).join('')}</section>`}
function saveIdentity(mut){const v=V();mut(v);wr(VK,v);return v}
function handlePhoto(file){if(!file||!file.type.startsWith('image/'))return;const fr=new FileReader();fr.onload=()=>{const img=new Image();img.onload=()=>{const size=320,c=document.createElement('canvas');c.width=c.height=size;const ctx=c.getContext('2d'),scale=Math.max(size/img.width,size/img.height),w=img.width*scale,h=img.height*scale;ctx.drawImage(img,(size-w)/2,(size-h)/2,w,h);saveIdentity(v=>v.portrait=c.toDataURL('image/jpeg',.78));world();};img.src=fr.result};fr.readAsDataURL(file)}
function patchOnboarding(){const on=$('#onboarding'),wrap=$('#onboardingWrap');if(!on?.classList.contains('on')||!wrap)return;const v=V();wrap.classList.add('pixel-onboarding');wrap.querySelectorAll('[data-v7-character]').forEach(btn=>{const t=btn.dataset.v7Character;if(!src(t))return;const svg=btn.querySelector('svg');if(svg)svg.outerHTML=`<img class="ob-char-img" src="${src(t)}" alt="${names[t]}">`;btn.classList.toggle('on',t===v.character)});const ill=wrap.querySelector('.ob-illustration');if(ill&&!ill.querySelector('.ob-char-img')&&(wrap.textContent.includes('ПЕРВАЯ ПОБЕДА')||wrap.textContent.includes('Каким будет наш мир?'))){ill.innerHTML=`<img class="ob-char-img hero-ob" src="${src(v.character)}" alt="">`}}
function patchOverlay(){const sh=$('#sheet');if(!sh||!$('#overlay')?.classList.contains('on'))return;sh.classList.add('pixel');const v=V();const mini=sh.querySelector('.v7-companion-mini');if(mini)mini.innerHTML=`<img src="${src(v.character)}" style="width:100%;height:100%;object-fit:contain">`;const step=sh.querySelector('.step-illustration,.lessonEmoji');if(step&&/рюкзак/i.test(sh.textContent||''))step.innerHTML=I.backpack?`<img src="${I.backpack}" alt="">`:'🎒';}
function maintain(){if($('#onboarding')?.classList.contains('on')){patchOnboarding();return}const id=$$('.screen.on')[0]?.id||'home';if(id==='home'&&!$('#home .room'))home();if(id==='family'&&!$('#family .card'))family();if(id==='collection'&&!$('#collection .world'))world();if(id==='parent'&&!$('#parent .tabs'))parent();patchOverlay()}
document.addEventListener('click',e=>{const g=e.target.closest('[data-lite-go]');if(g){e.preventDefault();e.stopPropagation();show(g.dataset.liteGo);if(g.hasAttribute('data-open-custom'))setTimeout(()=>$('#custom')?.scrollIntoView({behavior:'smooth'}),80);return}const pt=e.target.closest('[data-pt]');if(pt){parentTab=pt.dataset.pt;parent();return}const cc=e.target.closest('[data-px-char]');if(cc){saveIdentity(v=>v.character=cc.dataset.pxChar);world();return}const ac=e.target.closest('[data-px-acc]');if(ac){saveIdentity(v=>v.accessory=ac.dataset.pxAcc);world();return}if(e.target.closest('[data-open-custom]')){setTimeout(()=>$('#custom')?.scrollIntoView({behavior:'smooth'}),80);return}if(e.target.closest('[data-action],[data-family-action]'))setTimeout(maintain,90)},true);
document.addEventListener('change',e=>{if(e.target.id==='pxPhoto')handlePhoto(e.target.files?.[0]);setTimeout(maintain,30)});
const observer=new MutationObserver(()=>queueMicrotask(maintain));['home','family','collection','parent','overlay','onboarding'].forEach(id=>{const el=$('#'+id);if(el)observer.observe(el,{childList:true,attributes:true,attributeFilter:['class']})});
setTimeout(()=>{$('#onboarding')?.classList.contains('on')?patchOnboarding():show('home')},650);
window.addEventListener('pageshow',()=>setTimeout(maintain,40));
})();