(()=>{
const BASE_KEY='moki_v6_product', FAMILY_KEY='moki_family_v1', VKEY='moki_v7_identity';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const defaultV={character:'moki',accessory:'none',portrait:null,portraitVisibleFamily:true,parentTab:'today',mood:'happy'};
let V;try{V={...defaultV,...JSON.parse(localStorage.getItem(VKEY)||'{}')}}catch(e){V={...defaultV}}
const saveV=()=>{try{localStorage.setItem(VKEY,JSON.stringify(V))}catch(e){}};
const base=()=>{try{return JSON.parse(localStorage.getItem(BASE_KEY)||'{}')}catch(e){return {}}};
const fam=()=>{try{return JSON.parse(localStorage.getItem(FAMILY_KEY)||'{}')}catch(e){return {}}};
const names={moki:'Моки',tobi:'Тоби',runi:'Руни',bip:'Бип',nori:'Нори'};
const days={morning:'Доброе утро',day:'Привет',evening:'Добрый вечер',night:'Ещё не спишь?'};
function dayPart(){const h=new Date().getHours();return h<11?'morning':h<17?'day':h<21?'evening':'night'}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function charSvg(type=V.character,color='#7565ef',mood='happy'){
 const eyeY=mood==='sleep'?69:66, mouth=mood==='wow'?`<ellipse cx="75" cy="91" rx="9" ry="12" fill="#273142"/>`:mood==='sleep'?`<path d="M58 88Q75 96 92 88" stroke="#273142" stroke-width="5" fill="none" stroke-linecap="round"/>`:`<path d="M55 86Q75 103 95 86" stroke="#273142" stroke-width="7" fill="none" stroke-linecap="round"/>`;
 if(type==='bip')return `<svg class="v7-hero-svg" viewBox="0 0 150 170" aria-hidden="true"><defs><linearGradient id="rb" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${color}"/><stop offset="1" stop-color="#4a6bc6"/></linearGradient></defs><rect x="31" y="38" width="88" height="91" rx="31" fill="url(#rb)"/><rect x="42" y="52" width="66" height="48" rx="20" fill="#edf6ff" opacity=".96"/><circle cx="61" cy="${eyeY}" r="7" fill="#273142"/><circle cx="89" cy="${eyeY}" r="7" fill="#273142"/><circle cx="63" cy="${eyeY-2}" r="2" fill="#fff"/><circle cx="91" cy="${eyeY-2}" r="2" fill="#fff"/>${mouth}<path d="M75 38V20" stroke="#273142" stroke-width="6" stroke-linecap="round"/><circle cx="75" cy="16" r="7" fill="#ffc94f"/><rect x="49" y="126" width="18" height="27" rx="8" fill="#37445e"/><rect x="83" y="126" width="18" height="27" rx="8" fill="#37445e"/><rect x="17" y="65" width="17" height="46" rx="8" fill="${color}"/><rect x="116" y="65" width="17" height="46" rx="8" fill="${color}"/></svg>`;
 if(type==='tobi')return `<svg class="v7-hero-svg" viewBox="0 0 150 170" aria-hidden="true"><circle cx="43" cy="42" r="25" fill="${color}"/><circle cx="107" cy="42" r="25" fill="${color}"/><circle cx="43" cy="42" r="13" fill="#f6cba2" opacity=".75"/><circle cx="107" cy="42" r="13" fill="#f6cba2" opacity=".75"/><path d="M30 70Q30 37 75 34Q120 37 120 74V111Q112 136 97 143L98 158H82L75 147L68 158H52L53 143Q37 136 30 111Z" fill="${color}"/><ellipse cx="56" cy="${eyeY}" rx="13" ry="15" fill="#fff"/><ellipse cx="94" cy="${eyeY}" rx="13" ry="15" fill="#fff"/><circle cx="58" cy="${eyeY+1}" r="6" fill="#273142"/><circle cx="92" cy="${eyeY+1}" r="6" fill="#273142"/><ellipse cx="75" cy="82" rx="9" ry="7" fill="#5c4137"/>${mouth}<ellipse cx="75" cy="100" rx="25" ry="22" fill="#f6cba2" opacity=".42"/></svg>`;
 if(type==='runi')return `<svg class="v7-hero-svg" viewBox="0 0 150 170" aria-hidden="true"><path d="M38 48L25 22L51 36M112 48L125 22L99 36" fill="#ffd66e" stroke="#d39a31" stroke-width="3"/><path d="M33 53Q22 34 33 18Q53 25 62 41Q75 32 89 41Q98 25 117 18Q128 34 117 53Q129 68 124 98Q120 127 100 139L101 157H84L75 146L66 157H49L50 139Q30 127 26 98Q21 68 33 53Z" fill="${color}"/><path d="M28 88Q9 80 12 62Q30 67 38 78" fill="#9bd7ff" opacity=".8"/><path d="M122 88Q141 80 138 62Q120 67 112 78" fill="#9bd7ff" opacity=".8"/><ellipse cx="55" cy="${eyeY}" rx="14" ry="17" fill="#fff"/><ellipse cx="95" cy="${eyeY}" rx="14" ry="17" fill="#fff"/><circle cx="57" cy="${eyeY+2}" r="6" fill="#273142"/><circle cx="93" cy="${eyeY+2}" r="6" fill="#273142"/><ellipse cx="75" cy="83" rx="8" ry="6" fill="#273142"/>${mouth}<path d="M74 139L84 151L75 164L66 151Z" fill="#ffd66e"/></svg>`;
 if(type==='nori')return `<svg class="v7-hero-svg" viewBox="0 0 150 170" aria-hidden="true"><path d="M30 56L24 16L57 39Q75 29 93 39L126 16L120 56Q129 72 123 102Q118 130 98 141L99 158H82L75 147L68 158H51L52 141Q32 130 27 102Q21 72 30 56Z" fill="${color}"/><path d="M32 43L29 25L48 39" fill="#ffb3bf" opacity=".8"/><path d="M118 43L121 25L102 39" fill="#ffb3bf" opacity=".8"/><ellipse cx="54" cy="${eyeY}" rx="14" ry="16" fill="#fff"/><ellipse cx="96" cy="${eyeY}" rx="14" ry="16" fill="#fff"/><ellipse cx="56" cy="${eyeY+1}" rx="4" ry="8" fill="#273142"/><ellipse cx="94" cy="${eyeY+1}" rx="4" ry="8" fill="#273142"/><path d="M70 82L75 87L80 82" fill="#ff9aaa"/><path d="M75 87Q75 93 67 94M75 87Q75 93 83 94" stroke="#273142" stroke-width="3" fill="none"/>${mouth}<path d="M39 86H16M39 93H12M111 86H134M111 93H138" stroke="#273142" stroke-width="2" opacity=".65"/></svg>`;
 return `<svg class="v7-hero-svg" viewBox="0 0 150 170" aria-hidden="true"><defs><linearGradient id="vf" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${color}"/><stop offset="1" stop-color="#5f55c6"/></linearGradient></defs><path d="M34 54Q18 31 28 13Q48 20 59 37Q75 28 91 37Q102 20 122 13Q132 31 116 54Q126 68 123 91Q120 119 100 132L102 150Q99 161 88 158L78 146H70L60 158Q49 161 46 150L48 132Q28 119 25 91Q22 68 34 54Z" fill="url(#vf)"/><ellipse cx="54" cy="${eyeY}" rx="15" ry="18" fill="#fff"/><ellipse cx="96" cy="${eyeY}" rx="15" ry="18" fill="#fff"/><ellipse cx="56" cy="${eyeY+2}" rx="6" ry="8" fill="#273142"/><ellipse cx="94" cy="${eyeY+2}" rx="6" ry="8" fill="#273142"/><circle cx="58" cy="${eyeY-1}" r="2" fill="#fff"/><circle cx="96" cy="${eyeY-1}" r="2" fill="#fff"/><ellipse cx="75" cy="84" rx="7" ry="5" fill="#273142"/>${mouth}<ellipse cx="39" cy="84" rx="9" ry="5" fill="#ff9aaa" opacity=".42"/><ellipse cx="111" cy="84" rx="9" ry="5" fill="#ff9aaa" opacity=".42"/></svg>`;
}
function portrait(){return V.portrait?`<div class="v7-portrait-medallion"><img alt="Портрет ребёнка" src="${V.portrait}"></div>`:''}
function accessory(){if(V.accessory==='hat')return `<span class="v7-accessory hat">🧢</span>`;if(V.accessory==='glasses')return `<span class="v7-accessory glasses">🕶️</span>`;if(V.accessory==='cape')return `<span class="v7-accessory cape">🦸</span>`;return ''}
function hero(color,mood='happy'){return `<div class="v7-hero-wrap" data-v7-pet>${charSvg(V.character,color,mood)}${accessory()}${portrait()}</div>`}
function active(B){return (B.missions||[]).filter(m=>m.enabled).sort((a,b)=>(a.order||999)-(b.order||999))}
function next(B){return active(B).find(m=>!B.daily?.completed?.[m.id])}
function done(B){return active(B).filter(m=>B.daily?.completed?.[m.id]).length}
function goal(B){return Math.min(4,active(B).length||1)}
function childHp(F){const m=(F.members||[]).find(x=>x.id==='child');return m?.earned||0}
function totalHp(F){return (F.members||[]).reduce((a,m)=>a+(m.earned||0),0)}
function sceneItems(B){const map={lantern:'🏮',plant:'🌱',flag:'🚩',telescope:'🔭',kite:'🪁',crystal:'🔮'};return (B.child?.collection||[]).map(id=>`<button class="v7-scene-item ${id}" data-v7-object="${id}" aria-label="${id}">${map[id]||'✨'}</button>`).join('')}
function familyStack(F){const ms=(F.members||[]).slice(0,4);return `<div class="v7-family-mini">${ms.map((m,i)=>`<span class="v7-avatar-dot">${m.id==='child'?({moki:'🦊',tobi:'🐻',runi:'🐲',bip:'🤖',nori:'🐱'}[V.character]):(m.avatar||'👤')}</span>`).join('')}</div>`}
function speech(B,F,n,ready){const name=B.child?.name||'Игрок',heroName=names[V.character];if(ready)return `${name}, сундук готов! Я хочу посмотреть, что внутри ✨`;if(!n)return `На сегодня всё. ${heroName} отдыхает — можно идти играть дальше без телефона 🌿`;const part=dayPart();const variants={morning:`${days[part]}, ${name}! Начнём с «${n.title}»?`,day:`${name}, у нас одна короткая миссия: «${n.title}».`,evening:`Почти закончили день. Осталось: «${n.title}».`,night:`Если ещё не спишь — можно сделать «${n.title}», а можно вернуться завтра.`};return variants[part]}
function renderHome(){const root=$('#home');if(!root)return;const B=base(),F=fam(),A=active(B),n=next(B),d=done(B),g=goal(B),ready=d>=g&&!B.daily?.chestOpened,finished=!n&&!ready,part=dayPart(),color=B.child?.color||'#7565ef',theme=B.child?.theme||'forest',hp=childHp(F),thp=totalHp(F),pct=A.length?Math.round(d/A.length*100):100;
 let action;if(ready)action=`<div class="v7-action-icon">🎁</div><div class="v7-action-copy"><div class="eyebrow">НАГРАДА ГОТОВА</div><b>Сундук дня</b><span>${d} миссии уже сделаны</span></div><button class="v7-action-button gold" data-action="chest">Открыть</button>`;else if(finished)action=`<div class="v7-action-icon">🌿</div><div class="v7-action-copy"><div class="eyebrow">НА СЕГОДНЯ ВСЁ</div><b>Можно закрыть MOKI</b><span>Мир сохранил весь прогресс</span></div><button class="v7-action-button done" data-v7-pet>Пока!</button>`;else action=`<div class="v7-action-icon">${n.icon}</div><div class="v7-action-copy"><div class="eyebrow">${esc(n.group)} · ≈ ${n.mins} мин</div><b>${esc(n.title)}</b><span>${esc(n.steps?.[0]?.text||'Начнём с первого шага')}</span></div><button class="v7-action-button" data-action="startMission" data-id="${n.id}">Начать</button>`;
 root.innerHTML=`<div class="v7-home"><div class="v7-mini-status"><div class="v7-name">${esc(B.child?.name||'Игрок')} + ${names[V.character]}</div><div class="v7-status-pills"><span class="v7-pill">❤️ ${hp} HP</span><span class="v7-pill">👨‍👩‍👧 ${thp}</span></div></div><section class="v7-tama-scene theme-${theme} part-${part}"><div class="v7-sky-orb"></div><div class="v7-cloud c1"></div><div class="v7-cloud c2"></div><div class="v7-hill"></div><div class="v7-room-platform"></div><div class="v7-speech" id="v7Speech">${speech(B,F,n,ready)}</div>${sceneItems(B)}${hero(color,part==='night'?'sleep':'happy')}<button class="v7-hotspot wardrobe" data-v7-open="wardrobe"><span class="ico">🪞</span><span>Образ</span></button><button class="v7-hotspot family" data-v7-open="family"><span class="ico">👨‍👩‍👧</span><span>Команда</span>${thp?`<span class="badge">${thp}</span>`:''}</button>${n&&!ready?`<button class="v7-hotspot mission ready" data-action="startMission" data-id="${n.id}"><span class="ico">${n.icon}</span><span>Миссия</span></button>`:''}${ready?`<button class="v7-hotspot chest ready" data-action="chest"><span class="ico">🎁</span><span>Сундук</span></button>`:`<button class="v7-hotspot chest" data-go="collection"><span class="ico">🏡</span><span>Мир</span></button>`}<button class="v7-hotspot noticed" data-action="noticed"><span class="ico">✦</span><span>${B.daily?.noticed?'Сам заметил ✓':'Сам заметил'}</span></button></section><section class="v7-action-dock"><div class="v7-action-row">${action}</div></section><div class="v7-day-progress"><span>${d}/${A.length||0} сегодня</span><div class="v7-progress-line"><i style="width:${pct}%"></i></div>${familyStack(F)}</div></div>`;
}
function renderWorld(){const root=$('#collection');if(!root)return;const B=base(),color=B.child?.color||'#7565ef',theme=B.child?.theme||'forest',col=B.child?.collection||[];const charButtons=Object.keys(names).map(t=>`<button class="v7-character-choice ${V.character===t?'on':''}" data-v7-character="${t}">${charSvg(t,color)}<b>${names[t]}</b></button>`).join('');const acc=[['none','✓'],['hat','🧢'],['glasses','🕶️'],['cape','🦸']].map(([id,ic])=>`<button class="v7-accessory-choice ${V.accessory===id?'on':''}" data-v7-accessory="${id}">${ic}</button>`).join('');
 root.innerHTML=`<div class="v7-world"><div class="v7-world-head"><div><h1>Мир ${names[V.character]}</h1><p>Предметы из реальных миссий остаются здесь.</p></div><span class="v7-pill">🎁 ${B.child?.chests||0}</span></div><section class="v7-room theme-${theme}"><div class="v7-room-window"></div><div class="v7-room-rug"></div>${hero(color)}<button class="v7-room-object wardrobe" data-v7-open="wardrobe">🪞</button><button class="v7-room-object shelf" data-v7-object="shelf">${col.length?'🧸':'🗄️'}</button><button class="v7-room-object frame" data-v7-open="portrait">${V.portrait?'🖼️':'📷'}</button><button class="v7-room-object petbed" data-v7-object="bed">🛏️</button>${sceneItems(B)}</section><section class="v7-custom-card"><h2>Выбери своего героя</h2><p>Персонаж — компаньон, а не оценка ребёнка. Можно менять когда угодно.</p><div class="v7-character-grid">${charButtons}</div></section><section class="v7-custom-card"><h2>Аксессуары</h2><p>Позже они будут выпадать из сундуков. В прототипе можно примерить сразу.</p><div class="v7-accessory-grid">${acc}</div></section><section class="v7-custom-card"><h2>Портрет ребёнка</h2><p>Гибридный вариант: фотография становится медальоном на герое, а не «лицом зверька».</p><div class="v7-photo-row"><div class="v7-photo-preview">${V.portrait?`<img src="${V.portrait}" alt="Портрет">`:'📷'}</div><div class="v7-photo-copy"><b>${V.portrait?'Портрет добавлен':'Фото пока нет'}</b><span>По умолчанию показывается только на этом устройстве и в семье.</span></div><label class="v7-photo-button">${V.portrait?'Заменить':'Добавить'}<input id="v7PhotoInput" type="file" accept="image/*" hidden></label></div>${V.portrait?`<button class="button secondary" style="margin-top:8px" data-v7-remove-photo>Удалить фото</button>`:''}</section></div>`;
}
function renderParent(){const root=$('#parent');if(!root)return;const B=base(),F=fam(),hist=B.history||[],today=new Date().toLocaleDateString('sv-SE'),todayHist=hist.filter(h=>h.date===today&&h.missionId),solo=todayHist.filter(h=>h.supportUsed==='solo').length,support=todayHist.length-solo,A=active(B),tab=V.parentTab||'today';let content='';
 if(tab==='today')content=`<section class="v7-parent-summary"><div class="eyebrow">СЕГОДНЯ</div><h2>${todayHist.length?`Ребёнок тренируется без давления`:'День только начинается'}</h2><p>${todayHist.length?`Смотрите не на количество галочек, а на то, становится ли меньше внешней помощи.`:'Когда появятся выполненные миссии, здесь будет видно, сколько поддержки потребовалось.'}</p></section><div class="v7-parent-grid"><div class="v7-parent-metric"><b>${todayHist.length}</b><span>завершено</span></div><div class="v7-parent-metric"><b>${solo}</b><span>без подсказок</span></div><div class="v7-parent-metric"><b>${support}</b><span>с поддержкой</span></div></div><section class="v7-parent-section"><h2>Следующее решение</h2><p>${A.some(m=>(m.soloStreak||0)>=3)?'Один из навыков уже стабильно получается — можно мягко уменьшить подсказки.':'Пока сохраняйте текущий уровень поддержки. Система сама покажет, когда навык станет устойчивее.'}</p>${A.filter(m=>(m.soloStreak||0)>=3).slice(0,2).map(m=>`<div class="v7-privacy-box"><b>${m.icon} ${esc(m.title)}</b><br>${m.soloStreak} раза подряд без подсказок. Попробуйте следующий уровень самостоятельности.</div>`).join('')}</section>`;
 if(tab==='missions')content=`<section class="v7-parent-section"><h2>Миссии и уровень помощи</h2><p>Можно включить длинный семейный маршрут. Ребёнок всё равно увидит только одну следующую миссию.</p>${(B.missions||[]).map(m=>`<div class="v7-mission-row"><div class="v7-mission-icon">${m.icon}</div><div class="v7-mission-copy"><b>${esc(m.title)}</b><span>${esc(m.group)} · ${m.mins} мин · ${['вместе','по шагам','почти сам'][m.support]||'по шагам'}</span></div><div class="v7-row-actions"><button data-toggle="${m.id}">${m.enabled?'ВКЛ':'ВЫКЛ'}</button><button class="support" data-support="${m.id}">Помощь</button></div></div>`).join('')}</section>`;
 if(tab==='family')content=`<section class="v7-parent-section"><h2>MOKI Family</h2><p>Взрослые и ребёнок делают разные реальные дела, но двигают общий прогресс.</p><div class="v7-family-preview"><div class="v7-family-stack">${(F.members||[]).slice(0,4).map(m=>`<span>${m.id==='child'?({moki:'🦊',tobi:'🐻',runi:'🐲',bip:'🤖',nori:'🐱'}[V.character]):m.avatar||'👤'}</span>`).join('')}</div><div class="v7-family-copy"><b>${esc(F.name||'Наша команда')}</b><span>${totalHp(F)} HP · ${(F.members||[]).length||1} участников</span></div><button class="v7-parent-cta" data-v7-open="family">Открыть</button></div></section><section class="v7-parent-section"><h2>Приватность</h2><p>Конкретные бытовые задачи ребёнка должны оставаться внутри семьи.</p><div class="v7-privacy-box">👥 Друзья видят только категорию и HP.<br>📷 Фото ребёнка не показывается друзьям автоматически.<br>💬 Свободный детский чат в прототип не добавляем — только безопасные реакции.</div></section>`;
 if(tab==='avatar')content=`<section class="v7-parent-section"><h2>Персонаж и портрет</h2><p>Фото используется как приватный медальон. Оно не заменяет лицо персонажа и не публикуется автоматически.</p><div class="v7-photo-row"><div class="v7-photo-preview">${V.portrait?`<img src="${V.portrait}" alt="Портрет">`:'📷'}</div><div class="v7-photo-copy"><b>${V.portrait?'Портрет ребёнка добавлен':'Портрет не добавлен'}</b><span>${V.portraitVisibleFamily?'Разрешён внутри семейного круга':'Только на устройстве ребёнка'}</span></div><label class="v7-photo-button">${V.portrait?'Заменить':'Добавить'}<input id="v7PhotoInput" type="file" accept="image/*" hidden></label></div>${V.portrait?`<button class="button secondary" style="margin-top:8px" data-v7-family-photo>${V.portraitVisibleFamily?'Не показывать семье':'Показывать семье'}</button><button class="button secondary" style="margin-top:8px" data-v7-remove-photo>Удалить фото</button>`:''}</section><section class="v7-parent-section"><h2>Текущий герой</h2><p>${names[V.character]} · аксессуар ${V.accessory==='none'?'без аксессуара':V.accessory}</p><button class="button primary violet" data-v7-go-world>Открыть кастомизацию</button></section>`;
 root.innerHTML=`<div class="parent-head"><button class="icon-button" data-action="parentBack">←</button><h1>Для взрослого</h1></div><nav class="v7-parent-nav"><button class="${tab==='today'?'on':''}" data-v7-parent-tab="today">Сегодня</button><button class="${tab==='missions'?'on':''}" data-v7-parent-tab="missions">Миссии</button><button class="${tab==='family'?'on':''}" data-v7-parent-tab="family">Семья</button><button class="${tab==='avatar'?'on':''}" data-v7-parent-tab="avatar">Персонаж</button></nav>${content}`;
}
function patchOnboarding(){const wrap=$('#onboardingWrap');if(!wrap)return;const B=base(),color=B.child?.color||'#7565ef',ill=wrap.querySelector('.ob-illustration');if(wrap.textContent.includes('ПЕРВАЯ ПОБЕДА')){if(ill)ill.innerHTML=charSvg(V.character,color,'wow');const p=wrap.querySelector('.ob-body p');if(p)p.textContent=`${names[V.character]} теперь твой компаньон: одно маленькое дело → видимый результат.`;return}if(!wrap.textContent.includes('Каким будет наш мир?'))return;if(ill)ill.innerHTML=charSvg(V.character,color);const h=wrap.querySelector('.ob-body h1');if(h)h.textContent='Выбери компаньона и наш мир';const body=wrap.querySelector('.ob-body'),theme=wrap.querySelector('.theme-grid');if(!body||!theme)return;let box=wrap.querySelector('.v7-onboard-character-block');if(!box){box=document.createElement('div');box.className='v7-onboard-character-block';body.insertBefore(box,theme)}box.innerHTML=`<h3>Кто пойдёт с тобой?</h3><div class="v7-onboard-character-grid">${Object.keys(names).map(t=>`<button class="v7-onboard-character ${V.character===t?'on':''}" data-v7-character="${t}">${charSvg(t,color)}<b>${names[t]}</b></button>`).join('')}</div>`}
function enhanceSheet(){const sheet=$('#sheet');if(!sheet||!sheet.innerHTML)return;sheet.classList.add('v7-sheet');const body=sheet.querySelector('.mission-body,.reward-screen,.chest-stage');if(body&&!body.querySelector('.v7-companion-mini')&&!sheet.querySelector('.big-chest')){const B=base(),mini=document.createElement('div');mini.className='v7-companion-mini';mini.innerHTML=charSvg(V.character,B.child?.color||'#7565ef',sheet.textContent.includes('готова')||sheet.textContent.includes('звёзд')?'wow':'happy');body.insertBefore(mini,body.firstChild)}}
function keepHeader(){const B=base(),counter=$('#starCount')||$('#starsTop');if(counter){if(counter.id!=='starCount')counter.id='starCount';const val=String(B.child?.stars||0);if(counter.textContent!==val)counter.textContent=val;const holder=counter.closest('.star-counter');if(holder&&holder.firstChild?.nodeType===3&&holder.firstChild.textContent!=='💎 ')holder.firstChild.textContent='💎 '}}
let busy=false;
function patch(){if(busy)return;busy=true;try{keepHeader();const home=$('#home');if(home?.classList.contains('on')&&!home.querySelector('.v7-home'))renderHome();const col=$('#collection');if(col?.classList.contains('on')&&!col.querySelector('.v7-world'))renderWorld();const par=$('#parent');if(par?.classList.contains('on')&&!par.querySelector('.v7-parent-nav'))renderParent();patchOnboarding();enhanceSheet();const nav=$('#bottomNav');if(nav){const c=nav.querySelector('[data-go="collection"]');if(c&&!c.dataset.v7Label){c.innerHTML='<span>🏡</span>Мир';c.dataset.v7Label='1'}const f=nav.querySelector('[data-family-tab]');if(f&&!f.dataset.v7Label){f.innerHTML='<span>👨‍👩‍👧</span>Команда';f.dataset.v7Label='1'}}}finally{busy=false}}
function react(){const el=$('#v7Speech');if(!el)return;const r=[`${names[V.character]} рад тебя видеть ✨`,`У тебя уже получается больше, чем кажется.`,`Одно маленькое дело — и снова можно играть.`,`Хочешь посмотреть, что изменилось в мире?`];el.textContent=r[Math.floor(Math.random()*r.length)]}
function openWorld(){const b=$('#bottomNav [data-go="collection"]');if(b)b.click()}
function openFamily(){const top=$('#topbar'),nav=$('#bottomNav');if(top)top.style.display='flex';if(nav)nav.style.display='grid';const b=$('[data-family-tab]');if(b)b.click()}
function wardrobe(){openWorld();setTimeout(()=>document.querySelector('.v7-custom-card')?.scrollIntoView({behavior:'smooth',block:'start'}),120)}
function handleFile(file){if(!file||!file.type.startsWith('image/'))return;const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const size=256,c=document.createElement('canvas');c.width=c.height=size;const ctx=c.getContext('2d'),scale=Math.max(size/img.width,size/img.height),w=img.width*scale,h=img.height*scale;ctx.drawImage(img,(size-w)/2,(size-h)/2,w,h);V.portrait=c.toDataURL('image/jpeg',.76);saveV();const col=$('#collection'),par=$('#parent');if(col?.classList.contains('on'))renderWorld();if(par?.classList.contains('on'))renderParent();};img.src=r.result};r.readAsDataURL(file)}
document.addEventListener('click',e=>{const ch=e.target.closest('[data-v7-character]');if(ch){V.character=ch.dataset.v7Character;saveV();$$('[data-v7-character]').forEach(x=>x.classList.toggle('on',x.dataset.v7Character===V.character));const home=$('#home'),col=$('#collection');if(home?.classList.contains('on'))renderHome();if(col?.classList.contains('on'))renderWorld();patchOnboarding();return}const ac=e.target.closest('[data-v7-accessory]');if(ac){V.accessory=ac.dataset.v7Accessory;saveV();renderWorld();return}const op=e.target.closest('[data-v7-open]');if(op){const a=op.dataset.v7Open;if(a==='family')return openFamily();if(a==='wardrobe'||a==='portrait')return wardrobe()}if(e.target.closest('[data-v7-pet]'))return react();const pt=e.target.closest('[data-v7-parent-tab]');if(pt){V.parentTab=pt.dataset.v7ParentTab;saveV();return renderParent()}if(e.target.closest('[data-v7-remove-photo]')){V.portrait=null;saveV();if($('#collection')?.classList.contains('on'))renderWorld();if($('#parent')?.classList.contains('on'))renderParent();return}if(e.target.closest('[data-v7-family-photo]')){V.portraitVisibleFamily=!V.portraitVisibleFamily;saveV();return renderParent()}if(e.target.closest('[data-v7-go-world]')){const top=$('#topbar'),nav=$('#bottomNav');if(top)top.style.display='flex';if(nav)nav.style.display='grid';return openWorld()}const obj=e.target.closest('[data-v7-object]');if(obj){const text={lantern:'Фонарь напоминает о первой находке 🏮',plant:'Сад растёт вместе с твоими привычками 🌱',flag:'У этого мира уже есть свой флаг 🚩',telescope:'Ночью здесь видно звёзды 🔭',kite:'Змей любит дни, когда всё получается 🪁',crystal:'Редкая находка из новой главы ✨',shelf:'Здесь живут найденные предметы.',bed:`${names[V.character]} отдыхает здесь после длинного дня.`}[obj.dataset.v7Object]||'Предмет из твоего мира.';const sp=$('#v7Speech');if(sp)sp.textContent=text;return}},true);
document.addEventListener('change',e=>{if(e.target.id==='v7PhotoInput')handleFile(e.target.files?.[0])});
const obs=new MutationObserver(()=>setTimeout(patch,0));obs.observe(document.documentElement,{childList:true,subtree:true});
setInterval(()=>{const h=$('#home');if(h?.classList.contains('on')&&!h.querySelector('.v7-home'))patch()},650);
setTimeout(patch,80);
})();