(()=>{
const BASE_KEY='moki_v6_product', FAMILY_KEY='moki_family_v1', VKEY='moki_v7_identity';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const defaultV={character:'moki',accessory:'none',portrait:null,portraitVisibleFamily:true,parentTab:'today',mood:'happy'};
let V;try{V={...defaultV,...JSON.parse(localStorage.getItem(VKEY)||'{}')}}catch(e){V={...defaultV}}
const saveV=()=>{try{localStorage.setItem(VKEY,JSON.stringify(V))}catch(e){}};
const names={moki:'Моки',tobi:'Тоби',runi:'Руни',bip:'Бип',nori:'Нори'};
const charMeta={moki:{emoji:'🦊',kind:'fox'},tobi:{emoji:'🐻',kind:'bear'},runi:{emoji:'🐲',kind:'dragon'},bip:{emoji:'🤖',kind:'bot'},nori:{emoji:'🐱',kind:'cat'}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const base=()=>{try{return JSON.parse(localStorage.getItem(BASE_KEY)||'{}')}catch(e){return {}}};
const fam=()=>{try{return JSON.parse(localStorage.getItem(FAMILY_KEY)||'{}')}catch(e){return {}}};
const active=B=>(B.missions||[]).filter(m=>m.enabled).sort((a,b)=>(a.order||999)-(b.order||999));
const next=B=>active(B).find(m=>!B.daily?.completed?.[m.id]);
const done=B=>active(B).filter(m=>B.daily?.completed?.[m.id]).length;
const goal=B=>Math.min(4,active(B).length||1);
const dayPart=()=>{const h=new Date().getHours();return h<11?'morning':h<17?'day':h<21?'evening':'night'};
const days={morning:'Доброе утро',day:'Привет',evening:'Добрый вечер',night:'Ещё не спишь?'};
function charSvg(type=V.character,color='#7565ef',mood='happy'){
 const k=charMeta[type]?.kind||'fox',sleep=mood==='sleep',wow=mood==='wow';
 if(k==='bot')return `<svg viewBox="0 0 150 170" aria-hidden="true"><rect x="34" y="42" width="82" height="89" rx="30" fill="${color}"/><rect x="43" y="55" width="64" height="49" rx="19" fill="#eef5ff"/><circle cx="62" cy="78" r="7" fill="#253044"/><circle cx="88" cy="78" r="7" fill="#253044"/><path d="M61 94Q75 104 89 94" stroke="#253044" stroke-width="6" fill="none" stroke-linecap="round"/><path d="M75 42V25" stroke="#253044" stroke-width="6" stroke-linecap="round"/><circle cx="75" cy="22" r="7" fill="#ffca4b"/><rect x="48" y="125" width="20" height="29" rx="9" fill="${color}"/><rect x="82" y="125" width="20" height="29" rx="9" fill="${color}"/></svg>`;
 if(k==='bear')return `<svg viewBox="0 0 150 170" aria-hidden="true"><circle cx="45" cy="43" r="23" fill="${color}"/><circle cx="105" cy="43" r="23" fill="${color}"/><ellipse cx="75" cy="91" rx="52" ry="56" fill="${color}"/><ellipse cx="56" cy="76" rx="13" ry="16" fill="#fff"/><ellipse cx="94" cy="76" rx="13" ry="16" fill="#fff"/><ellipse cx="56" cy="78" rx="5" ry="7" fill="#273142"/><ellipse cx="94" cy="78" rx="5" ry="7" fill="#273142"/><ellipse cx="75" cy="94" rx="17" ry="13" fill="#f3d5bb"/><ellipse cx="75" cy="91" rx="7" ry="5" fill="#273142"/><path d="M63 101Q75 112 87 101" stroke="#273142" stroke-width="5" fill="none" stroke-linecap="round"/><rect x="48" y="133" width="22" height="25" rx="10" fill="${color}"/><rect x="80" y="133" width="22" height="25" rx="10" fill="${color}"/></svg>`;
 if(k==='dragon')return `<svg viewBox="0 0 150 170" aria-hidden="true"><path d="M36 54Q28 23 47 18L61 39Q75 29 89 39L103 18Q122 23 114 54Q128 66 123 96Q118 126 98 136L99 157L82 146H68L51 157L52 136Q32 126 27 96Q22 66 36 54Z" fill="${color}"/><path d="M53 35L61 15L69 38" fill="#ffd35b"/><path d="M81 38L89 15L97 35" fill="#ffd35b"/><ellipse cx="55" cy="75" rx="14" ry="17" fill="#fff"/><ellipse cx="95" cy="75" rx="14" ry="17" fill="#fff"/><ellipse cx="57" cy="77" rx="5" ry="7" fill="#273142"/><ellipse cx="93" cy="77" rx="5" ry="7" fill="#273142"/><path d="M58 97Q75 110 92 97" stroke="#273142" stroke-width="6" fill="none" stroke-linecap="round"/><path d="M106 89Q132 87 126 110Q119 126 103 119" fill="${color}"/></svg>`;
 if(k==='cat')return `<svg viewBox="0 0 150 170" aria-hidden="true"><path d="M31 55L32 17L59 39Q75 30 91 39L118 17L119 55Q128 68 124 94Q120 124 99 135L101 157L84 146H66L49 157L51 135Q30 124 26 94Q22 68 31 55Z" fill="${color}"/><ellipse cx="54" cy="75" rx="14" ry="17" fill="#fff"/><ellipse cx="96" cy="75" rx="14" ry="17" fill="#fff"/><ellipse cx="56" cy="77" rx="5" ry="7" fill="#273142"/><ellipse cx="94" cy="77" rx="5" ry="7" fill="#273142"/><path d="M68 91L75 96L82 91" fill="#ff9aaa"/><path d="M59 99Q75 112 91 99" stroke="#273142" stroke-width="5" fill="none" stroke-linecap="round"/><path d="M113 124Q139 118 130 96" stroke="${color}" stroke-width="12" fill="none" stroke-linecap="round"/></svg>`;
 return `<svg viewBox="0 0 150 170" aria-hidden="true"><defs><linearGradient id="furV7" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${color}"/><stop offset="1" stop-color="#5f55c6"/></linearGradient></defs><path d="M34 54Q18 31 28 13Q48 20 59 37Q75 28 91 37Q102 20 122 13Q132 31 116 54Q126 68 123 91Q120 119 100 132L102 150Q99 161 88 158L78 146H70L60 158Q49 161 46 150L48 132Q28 119 25 91Q22 68 34 54Z" fill="url(#furV7)"/><ellipse cx="54" cy="70" rx="15" ry="18" fill="#fff"/><ellipse cx="96" cy="70" rx="15" ry="18" fill="#fff"/><ellipse cx="56" cy="72" rx="6" ry="${sleep?2:8}" fill="#273142"/><ellipse cx="94" cy="72" rx="6" ry="${sleep?2:8}" fill="#273142"/><ellipse cx="75" cy="84" rx="7" ry="5" fill="#273142"/><path d="M56 83Q75 ${wow?108:101} 94 83" stroke="#283142" stroke-width="7" fill="none" stroke-linecap="round"/><ellipse cx="39" cy="84" rx="9" ry="5" fill="#ff9aaa" opacity=".42"/><ellipse cx="111" cy="84" rx="9" ry="5" fill="#ff9aaa" opacity=".42"/></svg>`;
}
function accessory(){if(V.accessory==='hat')return '<span class="v7-accessory hat">🧢</span>';if(V.accessory==='glasses')return '<span class="v7-accessory glasses">🕶️</span>';if(V.accessory==='cape')return '<span class="v7-accessory cape">🦸</span>';return ''}
function portrait(){return V.portrait?`<div class="v7-portrait-medallion"><img alt="Портрет ребёнка" src="${V.portrait}"></div>`:''}
function hero(color,mood='happy'){return `<div class="v7-hero-wrap" data-v7-pet>${charSvg(V.character,color,mood)}${accessory()}${portrait()}</div>`}
function totalHp(F){return (F.members||[]).reduce((n,m)=>n+(m.earned||0),0)}
function childHp(F){return (F.members||[]).find(m=>m.id==='child')?.earned||0}
function sceneItems(B){const col=B.child?.collection||[];return col.map(id=>{const map={lantern:'🏮',plant:'🌱',flag:'🚩',telescope:'🔭',kite:'🪁',crystal:'🔮'};return `<button class="v7-scene-item ${id}" data-v7-object="${id}">${map[id]||'✨'}</button>`}).join('')}
function familyStack(F){const ms=(F.members||[]).slice(0,4);return `<div class="v7-family-mini">${ms.map(m=>`<span class="v7-avatar-dot">${m.id==='child'?({moki:'🦊',tobi:'🐻',runi:'🐲',bip:'🤖',nori:'🐱'}[V.character]):(m.avatar||'👤')}</span>`).join('')}</div>`}
function speech(B,F,n,ready){const name=B.child?.name||'Игрок',heroName=names[V.character];if(ready)return `${name}, сундук готов! Я хочу посмотреть, что внутри ✨`;if(!n)return `На сегодня всё. ${heroName} отдыхает — можно идти играть дальше без телефона 🌿`;const part=dayPart();const variants={morning:`${days[part]}, ${name}! Начнём с «${n.title}»?`,day:`${name}, у нас одна короткая миссия: «${n.title}».`,evening:`Почти закончили день. Осталось: «${n.title}».`,night:`Если ещё не спишь — можно сделать «${n.title}», а можно вернуться завтра.`};return variants[part]}
function renderHome(){const root=$('#home');if(!root)return;const B=base(),F=fam(),A=active(B),n=next(B),d=done(B),g=goal(B),ready=d>=g&&!B.daily?.chestOpened,finished=!n&&!ready,part=dayPart(),color=B.child?.color||'#7565ef',theme=B.child?.theme||'forest',hp=childHp(F),thp=totalHp(F),pct=A.length?Math.round(d/A.length*100):100;
 let action;if(ready)action=`<div class="v7-action-icon">🎁</div><div class="v7-action-copy"><div class="eyebrow">НАГРАДА ГОТОВА</div><b>Сундук дня</b><span>${d} миссии уже сделаны</span></div><button class="v7-action-button gold" data-action="chest">Открыть</button>`;else if(finished)action=`<div class="v7-action-icon">🌿</div><div class="v7-action-copy"><div class="eyebrow">НА СЕГОДНЯ ВСЁ</div><b>Можно закрыть MOKI</b><span>Мир сохранил весь прогресс</span></div><button class="v7-action-button done" data-v7-pet>Пока!</button>`;else action=`<div class="v7-action-icon">${n.icon}</div><div class="v7-action-copy"><div class="eyebrow">${esc(n.group)} · ≈ ${n.mins} мин</div><b>${esc(n.title)}</b><span>${esc(n.steps?.[0]?.text||'Начнём с первого шага')}</span></div><button class="v7-action-button" data-action="startMission" data-id="${n.id}">Начать</button>`;
 root.innerHTML=`<div class="v7-home"><div class="v7-mini-status"><div class="v7-name">${esc(B.child?.name||'Игрок')} + ${names[V.character]}</div><div class="v7-status-pills"><span class="v7-pill">❤️ ${hp} HP</span><span class="v7-pill">👨‍👩‍👧 ${thp}</span></div></div><section class="v7-tama-scene theme-${theme} part-${part}"><div class="v7-sky-orb"></div><div class="v7-cloud c1"></div><div class="v7-cloud c2"></div><div class="v7-hill"></div><div class="v7-room-platform"></div><div class="v7-speech" id="v7Speech">${speech(B,F,n,ready)}</div>${sceneItems(B)}${hero(color,part==='night'?'sleep':'happy')}<button class="v7-hotspot wardrobe" data-v7-open="wardrobe"><span class="ico">🪞</span><span>Образ</span></button><button class="v7-hotspot family" data-v7-open="family"><span class="ico">👨‍👩‍👧</span><span>Команда</span>${thp?`<span class="badge">${thp}</span>`:''}</button>${n&&!ready?`<button class="v7-hotspot mission ready" data-action="startMission" data-id="${n.id}"><span class="ico">${n.icon}</span><span>Миссия</span></button>`:''}${ready?`<button class="v7-hotspot chest ready" data-action="chest"><span class="ico">🎁</span><span>Сундук</span></button>`:`<button class="v7-hotspot chest" data-go="collection"><span class="ico">🏡</span><span>Мир</span></button>`}<button class="v7-hotspot noticed" data-action="noticed"><span class="ico">✦</span><span>${B.daily?.noticed?'Сам заметил ✓':'Сам заметил'}</span></button></section><section class="v7-action-dock"><div class="v7-action-row">${action}</div></section><div class="v7-day-progress"><span>${d}/${A.length||0} сегодня</span><div class="v7-progress-line"><i style="width:${pct}%"></i></div>${familyStack(F)}</div></div>`;
}
function renderWorld(){const root=$('#collection');if(!root)return;const B=base(),color=B.child?.color||'#7565ef',theme=B.child?.theme||'forest',col=B.child?.collection||[];const charButtons=Object.keys(names).map(t=>`<button class="v7-character-choice ${V.character===t?'on':''}" data-v7-character="${t}">${charSvg(t,color)}<b>${names[t]}</b></button>`).join('');const acc=[['none','✓'],['hat','🧢'],['glasses','🕶️'],['cape','🦸']].map(([id,ic])=>`<button class="v7-accessory-choice ${V.accessory===id?'on':''}" data-v7-accessory="${id}">${ic}</button>`).join('');
 root.innerHTML=`<div class="v7-world"><div class="v7-world-head"><div><h1>Мир ${names[V.character]}</h1><p>Предметы из реальных миссий остаются здесь.</p></div><span class="v7-pill">🎁 ${B.child?.chests||0}</span></div><section class="v7-room theme-${theme}"><div class="v7-room-window"></div><div class="v7-room-rug"></div>${hero(color)}<button class="v7-room-object wardrobe" data-v7-open="wardrobe">🪞</button><button class="v7-room-object shelf" data-v7-object="shelf">${col.length?'🧸':'🗄️'}</button><button class="v7-room-object frame" data-v7-open="portrait">${V.portrait?'🖼️':'📷'}</button><button class="v7-room-object petbed" data-v7-object="bed">🛏️</button>${sceneItems(B)}</section><section class="v7-custom-card"><h2>Выбери своего героя</h2><p>Персонаж — компаньон, а не оценка ребёнка. Можно менять когда угодно.</p><div class="v7-character-grid">${charButtons}</div></section><section class="v7-custom-card"><h2>Аксессуары</h2><p>Позже они будут выпадать из сундуков. В прототипе можно примерить сразу.</p><div class="v7-accessory-grid">${acc}</div></section><section class="v7-custom-card"><h2>Портрет ребёнка</h2><p>Гибридный вариант: фотография становится медальоном на герое, а не «лицом зверька».</p><div class="v7-photo-row"><div class="v7-photo-preview">${V.portrait?`<img src="${V.portrait}" alt="Портрет">`:'📷'}</div><div class="v7-photo-copy"><b>${V.portrait?'Портрет добавлен':'Фото пока нет'}</b><span>По умолчанию показывается только на этом устройстве и в семье.</span></div><label class="v7-photo-button">${V.portrait?'Заменить':'Добавить'}<input id="v7PhotoInput" type="file" accept="image/*" hidden></label></div>${V.portrait?`<button class="button secondary" style="margin-top:8px" data-v7-remove-photo>Удалить фото</button>`:''}</section></div>`;
}
function renderParent(){const root=$('#parent');if(!root)return;const B=base(),F=fam(),hist=B.history||[],today=new Date().toLocaleDateString('sv-SE'),todayHist=hist.filter(h=>h.date===today&&h.missionId),solo=todayHist.filter(h=>h.supportUsed==='solo').length,support=todayHist.length-solo,A=active(B),tab=V.parentTab||'today';let content='';
 if(tab==='today')content=`<section class="v7-parent-summary"><div class="eyebrow">СЕГОДНЯ</div><h2>${todayHist.length?`Ребёнок тренируется без давления`:'День только начинается'}</h2><p>${todayHist.length?`Смотрите не на количество галочек, а на то, становится ли меньше внешней помощи.`:'Когда появятся выполненные миссии, здесь будет видно, сколько поддержки потребовалось.'}</p></section><div class="v7-parent-grid"><div class="v7-parent-metric"><b>${todayHist.length}</b><span>завершено</span></div><div class="v7-parent-metric"><b>${solo}</b><span>без подсказок</span></div><div class="v7-parent-metric"><b>${support}</b><span>с поддержкой</span></div></div><section class="v7-parent-section"><h2>Следующее решение</h2><p>${A.some(m=>(m.soloStreak||0)>=3)?'Один из навыков уже стабильно получается — можно мягко уменьшить подсказки.':'Пока сохраняйте текущий уровень поддержки. Система сама покажет, когда навык станет устойчивее.'}</p>${A.filter(m=>(m.soloStreak||0)>=3).slice(0,2).map(m=>`<div class="v7-privacy-box"><b>${m.icon} ${esc(m.title)}</b><br>${m.soloStreak} раза подряд без подсказок. Попробуйте следующий уровень самостоятельности.</div>`).join('')}</section>`;
 if(tab==='missions')content=`<section class="v7-parent-section"><h2>Миссии и уровень помощи</h2><p>Можно включить длинный семейный маршрут. Ребёнок всё равно увидит только одну следующую миссию.</p>${(B.missions||[]).map(m=>`<div class="v7-mission-row"><div class="v7-mission-icon">${m.icon}</div><div class="v7-mission-copy"><b>${esc(m.title)}</b><span>${esc(m.group)} · ${m.mins} мин · ${['вместе','по шагам','почти сам'][m.support]||'по шагам'}</span></div><div class="v7-row-actions"><button data-toggle="${m.id}">${m.enabled?'ВКЛ':'ВЫКЛ'}</button><button class="support" data-support="${m.id}">Помощь</button></div></div>`).join('')}</section>`;
 if(tab==='family')content=`<section class="v7-parent-section"><h2>MOKI Family</h2><p>Взрослые и ребёнок делают разные реальные дела, но двигают общий прогресс.</p><div class="v7-family-preview"><div class="v7-family-stack">${(F.members||[]).slice(0,4).map(m=>`<span>${m.id==='child'?({moki:'🦊',tobi:'🐻',runi:'🐲',bip:'🤖',nori:'🐱'}[V.character]):m.avatar||'👤'}</span>`).join('')}</div><div class="v7-family-copy"><b>${esc(F.name||'Наша команда')}</b><span>${totalHp(F)} HP · ${(F.members||[]).length||1} участников</span></div><button class="v7-parent-cta" data-v7-open="family">Открыть</button></div></section><section class="v7-parent-section"><h2>Приватность</h2><p>Конкретные бытовые задачи ребёнка должны оставаться внутри семьи.</p><div class="v7-privacy-box">👥 Друзья видят только категорию и HP.<br>📷 Фото ребёнка не показывается друзьям автоматически.<br>💬 Свободный детский чат в прототип не добавляем — только безопасные реакции.</div></section>`;
 if(tab==='avatar')content=`<section class="v7-parent-section"><h2>Персонаж и портрет</h2><p>Фото используется как приватный медальон. Оно не заменяет лицо персонажа и не публикуется автоматически.</p><div class="v7-photo-row"><div class="v7-photo-preview">${V.portrait?`<img src="${V.portrait}" alt="Портрет">`:'📷'}</div><div class="v7-photo-copy"><b>${V.portrait?'Портрет ребёнка добавлен':'Портрет не добавлен'}</b><span>${V.portraitVisibleFamily?'Разрешён внутри семейного круга':'Только на устройстве ребёнка'}</span></div><label class="v7-photo-button">${V.portrait?'Заменить':'Добавить'}<input id="v7PhotoInput" type="file" accept="image/*" hidden></label></div>${V.portrait?`<button class="button secondary" style="margin-top:8px" data-v7-family-photo>${V.portraitVisibleFamily?'Не показывать семье':'Показывать семье'}</button><button class="button secondary" style="margin-top:8px" data-v7-remove-photo>Удалить фото</button>`:''}</section><section class="v7-parent-section"><h2>Текущий герой</h2><p>${names[V.character]} · аксессуар ${V.accessory==='none'?'без аксессуара':V.accessory}</p><button class="button primary violet" data-v7-go-world>Открыть кастомизацию</button></section>`;
 root.innerHTML=`<div class="parent-head"><button class="icon-button" data-action="parentBack">←</button><h1>Для взрослого</h1></div><nav class="v7-parent-nav"><button class="${tab==='today'?'on':''}" data-v7-parent-tab="today">Сегодня</button><button class="${tab==='missions'?'on':''}" data-v7-parent-tab="missions">Миссии</button><button class="${tab==='family'?'on':''}" data-v7-parent-tab="family">Семья</button><button class="${tab==='avatar'?'on':''}" data-v7-parent-tab="avatar">Персонаж</button></nav>${content}`;
}
function patchOnboarding(){const wrap=$('#onboardingWrap');if(!wrap)return;const B=base(),color=B.child?.color||'#7565ef',ill=wrap.querySelector('.ob-illustration');if(wrap.textContent.includes('ПЕРВАЯ ПОБЕДА')){if(ill)ill.innerHTML=charSvg(V.character,color,'wow');const p=wrap.querySelector('.ob-body p');if(p)p.textContent=`${names[V.character]} теперь твой компаньон: одно маленькое дело → видимый результат.`;return}if(!wrap.textContent.includes('Каким будет наш мир?'))return;if(ill)ill.innerHTML=charSvg(V.character,color);const h=wrap.querySelector('.ob-body h1');if(h)h.textContent='Выбери компаньона и наш мир';const body=wrap.querySelector('.ob-body'),theme=wrap.querySelector('.theme-grid');if(!body||!theme)return;let box=wrap.querySelector('.v7-onboard-character-block');if(!box){box=document.createElement('div');box.className='v7-onboard-character-block';body.insertBefore(box,theme)}box.innerHTML=`<h3>Кто пойдёт с тобой?</h3><div class="v7-onboard-character-grid">${Object.keys(names).map(t=>`<button class="v7-onboard-character ${V.character===t?'on':''}" data-v7-character="${t}">${charSvg(t,color)}<b>${names[t]}</b></button>`).join('')}</div>`}
function enhanceSheet(){const sheet=$('#sheet');if(!sheet||!sheet.innerHTML)return;sheet.classList.add('v7-sheet');const body=sheet.querySelector('.mission-body,.reward-screen,.chest-stage');if(body&&!body.querySelector('.v7-companion-mini')&&!sheet.querySelector('.big-chest')){const B=base(),mini=document.createElement('div');mini.className='v7-companion-mini';mini.innerHTML=charSvg(V.character,B.child?.color||'#7565ef',sheet.textContent.includes('готова')||sheet.textContent.includes('звёзд')?'wow':'happy');body.insertBefore(mini,body.firstChild)}}
function keepHeader(){const B=base(),counter=$('#starCount')||$('#starsTop');if(counter){if(counter.id!=='starCount')counter.id='starCount';const val=String(B.child?.stars||0);if(counter.textContent!==val)counter.textContent=val;const holder=counter.closest('.star-counter');if(holder&&holder.firstChild?.nodeType===3&&holder.firstChild.textContent!=='💎 ')holder.firstChild.textContent='💎 '}}
let busy=false;
function patch(){if(busy)return;busy=true;try{keepHeader();const home=$('#home');if(home?.classList.contains('on')&&!home.querySelector('.v7-home'))renderHome();const col=$('#collection');if(col?.classList.contains('on')&&!col.querySelector('.v7-world'))renderWorld();const par=$('#parent');if(par?.classList.contains('on')&&!par.querySelector('.v7-parent-nav'))renderParent();patchOnboarding();enhanceSheet();const nav=$('#bottomNav');if(nav){const c=nav.querySelector('[data-go="collection"]');if(c&&!c.dataset.v7Label){c.innerHTML='<span>🏡</span>Мир';c.dataset.v7Label='1'}const f=nav.querySelector('[data-family-tab]');if(f&&!f.dataset.v7Label){f.innerHTML='<span>👨‍👩‍👧</span>Команда';f.dataset.v7Label='1'}}}finally{busy=false}}
function react(){const el=$('#v7Speech');if(!el)return;const r=[`${names[V.character]} рад тебя видеть ✨`,`У тебя уже получается больше, чем кажется.`,`Одно маленькое дело — и снова можно играть.`,`Хочешь посмотреть, что изменилось в мире?`];el.textContent=r[Math.floor(Math.random()*r.length)]}
function openWorld(){const b=$('#bottomNav [data-go="collection"]');if(b)b.click()}
function openFamily(){const top=$('#topbar'),nav=$('#bottomNav');if(top)top.style.display='flex';if(nav)nav.style.display='grid';const b=$('[data-family-tab]');if(b)b.click()}
function wardrobe(){openWorld();setTimeout(()=>document.querySelector('.v7-custom-card')?.scrollIntoView({behavior:'smooth',block:'start'}),120)}
function handleFile(file){if(!file||!file.type.startsWith('image/'))return;const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const size=256,c=document.createElement('canvas');c.width=c.height=size;const ctx=c.getContext('2d'),scale=Math.max(size/img.width,size/img.height),w=img.width*scale,h=img.height*scale;ctx.drawImage(img,(size-w)/2,(size-h)/2,w,h);V.portrait=c.toDataURL('image/jpeg',.76);saveV();const col=$('#collection'),par=$('#parent');if(col?.classList.contains('on'))renderWorld();if(par?.classList.contains('on'))renderParent();};img.src=r.result};r.readAsDataURL(file)}
document.addEventListener('click',e=>{const ch=e.target.closest('[data-v7-character]');if(ch){V.character=ch.dataset.v7Character;saveV();$$('[data-v7-character]').forEach(x=>x.classList.toggle('on',x.dataset.v7Character===V.character));const home=$('#home'),col=$('#collection');if(home?.classList.contains('on'))renderHome();if(col?.classList.contains('on'))renderWorld();patchOnboarding();return}const ac=e.target.closest('[data-v7-accessory]');if(ac){V.accessory=ac.dataset.v7Accessory;saveV();renderWorld();return}const op=e.target.closest('[data-v7-open]');if(op){const a=op.dataset.v7Open;if(a==='family')return openFamily();if(a==='wardrobe'||a==='portrait')return wardrobe()}if(e.target.closest('[data-v7-pet]'))return react();const pt=e.target.closest('[data-v7-parent-tab]');if(pt){V.parentTab=pt.dataset.v7ParentTab;saveV();return renderParent()}if(e.target.closest('[data-v7-remove-photo]')){V.portrait=null;saveV();if($('#collection')?.classList.contains('on'))renderWorld();if($('#parent')?.classList.contains('on'))renderParent();return}if(e.target.closest('[data-v7-family-photo]')){V.portraitVisibleFamily=!V.portraitVisibleFamily;saveV();return renderParent()}if(e.target.closest('[data-v7-go-world]')){const top=$('#topbar'),nav=$('#bottomNav');if(top)top.style.display='flex';if(nav)nav.style.display='grid';return openWorld()}const obj=e.target.closest('[data-v7-object]');if(obj){const text={lantern:'Фонарь напоминает о первой находке 🏮',plant:'Сад растёт вместе с твоими привычками 🌱',flag:'У этого мира уже есть свой флаг 🚩',telescope:'Ночью здесь видно звёзды 🔭',kite:'Змей любит дни, когда всё получается 🪁',crystal:'Редкая находка из новой главы ✨',shelf:'Здесь живут найденные предметы.',bed:`${names[V.character]} отдыхает здесь после длинного дня.`}[obj.dataset.v7Object]||'Предмет из твоего мира.';const sp=$('#v7Speech');if(sp)sp.textContent=text;return}},true);
document.addEventListener('change',e=>{if(e.target.id==='v7PhotoInput')handleFile(e.target.files?.[0])});
document.addEventListener('click',()=>setTimeout(patch,0));
document.addEventListener('change',()=>setTimeout(patch,0));
window.addEventListener('pageshow',()=>setTimeout(patch,0));
setTimeout(patch,80);
})();