function overlayHtml(o){
 if(o.type==='mission'||o.type==='effort'||o.type==='help')return missionOverlay(o);
 if(o.type==='reward')return `<div class="overlay on"><section class="sheet"><div class="reward"><div style="font-size:13px;font-weight:900">МИССИЯ ГОТОВА</div><div class="reward-hero"><img src="${characterImg()}"></div><h2>Отличная работа!</h2><p>${o.support==='solo'?'Получилось без внешней подсказки.':o.support==='hint'?'Подсказка помогла закончить миссию.':'Часть пути вы прошли вместе.'}</p><div class="reward-hp">❤️ +${o.hp} HP</div><button class="btn yellow" data-close>Вернуться к ${chars[S.child.character].name}</button></div></section></div>`;
 if(o.type==='chest')return `<div class="overlay on"><section class="sheet"><div class="chest"><img src="${asset('chest.webp')}" alt=""><h2>Сундук дня готов!</h2><p>Внутри — не ещё одна цифра. Предмет появится в твоём мире.</p><button class="btn yellow" data-reveal style="margin-top:17px">Открыть</button></div></section></div>`;
 if(o.type==='chestReveal'){const x=items.find(i=>i.id===o.item);return `<div class="overlay on"><section class="sheet"><div class="chest"><h2>Новая находка!</h2><div class="reveal">${x?`<img src="${asset(x.img)}"><b>${x.name}</b><span>Теперь этот предмет живёт в твоей комнате.</span>`:`<img src="${asset('chest.webp')}"><b>Фрагмент новой главы</b><span>Мир стал ещё чуть больше.</span>`}</div><button class="btn yellow" data-close style="margin-top:17px">Посмотреть мир</button></div></section></div>`}
 if(o.type==='parentGate')return `<div class="overlay on"><section class="sheet"><div class="mission"><div class="mission-main"><div class="mission-visual" style="font-size:65px">🔐</div><h2>Для взрослого</h2><p>Введите PIN, чтобы менять правила, миссии и фото ребёнка.</p><input id="pin" inputmode="numeric" maxlength="4" placeholder="••••" style="margin-top:16px;width:210px;border:2px solid #e6e9f0;border-radius:17px;padding:14px;text-align:center;font-size:22px"></div><div class="mission-footer"><button class="btn purple" data-parent-enter>Войти</button><button class="btn ghost" data-close>Отмена</button></div></div></section></div>`;
 if(o.type==='nudge')return `<div class="overlay on"><section class="sheet"><div class="mission"><div class="mission-main"><div class="mission-visual" style="font-size:65px">⚡</div><h2>Подначить по-доброму</h2><p>Без свободного чата — только короткие игровые реакции.</p><div class="help-list">${['⚡ Твой ход','👀 Я тебя догоняю','👊 Давай вместе','🔥 Ещё одно','🏆 Красиво!'].map(x=>`<button class="help-choice" data-nudge-send="${x}"><b>${x}</b></button>`).join('')}</div></div></div></section></div>`;
 if(o.type==='challenge')return `<div class="overlay on"><section class="sheet"><div class="mission"><div class="mission-main"><div class="mission-visual" style="font-size:65px">⚔️</div><h2>Дружеский вызов</h2><p>У каждого своя полезная задача. Побеждает тот, кто первым завершит свою.</p><div class="help-list">${S.family.members.filter(x=>x.id!=='child').map(m=>`<button class="help-choice" data-challenge-to="${m.id}"><b>${m.avatar||'👤'} ${esc(m.name)}</b><span>Бросить вызов</span></button>`).join('')}</div></div></div></section></div>`;
 return '';
}
function missionOverlay(o){
 const m=S.missions.find(x=>x.id===o.missionId),step=m.steps[o.step||0];if(o.type==='effort')return `<div class="overlay on"><section class="sheet"><div class="mission"><div class="mission-main"><div class="mission-visual"><img src="${characterImg()}"></div><h2>Как тебе было?</h2><p>Это помогает MOKI выбрать правильный объём поддержки в следующий раз.</p><div class="effort">${[['easy','😎','Легко'],['ok','🙂','Нормально'],['hard','😵','Сложно']].map(([id,e,n])=>`<button data-effort="${id}"><strong>${e}</strong>${n}</button>`).join('')}</div></div></div></section></div>`;
 if(o.type==='help'){const mode=o.helpMode;if(mode)return `<div class="overlay on"><section class="sheet"><div class="mission"><div class="mission-main"><div class="mission-visual" style="font-size:60px">${mode==='hint'?'💡':mode==='show'?'👀':'🤝'}</div><h2>${mode==='hint'?esc(step.hint):mode==='show'?esc(step.show):'Позови взрослого только на этот шаг'}</h2><p>${mode==='together'?'Следующий шаг снова попробуешь сам.':'Не нужно делать всю миссию сразу.'}</p></div><div class="mission-footer"><button class="btn primary" data-back-step>Попробовать</button></div></div></section></div>`;return `<div class="overlay on"><section class="sheet"><div class="mission"><div class="mission-top"><button class="x" data-back-step>←</button><div class="stepbar"><i style="width:${((o.step+1)/m.steps.length)*100}%"></i></div><b>${o.step+1}/${m.steps.length}</b></div><div class="mission-main"><div class="mission-visual"><img src="${characterImg()}"></div><h2>Как помочь?</h2><p>Выбери минимальную помощь, которой сейчас достаточно.</p><div class="help-list"><button class="help-choice" data-help="hint"><div>💡</div><div><b>Дать намёк</b><span>Небольшая подсказка</span></div></button><button class="help-choice" data-help="show"><div>👀</div><div><b>Показать первый шаг</b><span>Конкретная инструкция</span></div></button><button class="help-choice" data-help="together"><div>🤝</div><div><b>Сделаем вместе</b><span>Позвать взрослого только на этот шаг</span></div></button></div></div></div></section></div>`}
 return `<div class="overlay on"><section class="sheet"><div class="mission"><div class="mission-top"><button class="x" data-close>✕</button><div class="stepbar"><i style="width:${((o.step+1)/m.steps.length)*100}%"></i></div><b>${o.step+1}/${m.steps.length}</b></div><div class="mission-main"><div class="mission-visual">${m.id==='bag'?`<img src="${asset('backpack.webp')}">`:`<div style="font-size:70px">${m.icon}</div>`}<img class="mhero" src="${characterImg()}"></div><h2>${esc(step.text)}</h2><p>Сейчас нужен только этот один шаг.</p><button class="help" data-open-help>💡 Помощь</button></div><div class="mission-footer"><button class="btn primary" data-step-done>Готово</button></div></div></section></div>`;
}
function onboardingHtml(){
 const i=S.ui.onboardingStep||0,total=9,progress=`<div class="ob-progress">${Array.from({length:total},(_,x)=>`<i class="${x<=i?'on':''}"></i>`).join('')}</div>`;
 let body='';
 if(i===0)body=`<div class="ob-body"><div class="ob-hero"><img src="${asset('moki.webp')}"></div><div style="font-size:10px;font-weight:1000;letter-spacing:.14em;color:#6d60e5">СНАЧАЛА — ВЗРОСЛОМУ</div><h1>MOKI тренирует самостоятельность</h1><p>Не «послушание» и не гонку за очками. Ребёнок видит одного живого героя и одно следующее действие.</p></div><button class="btn purple" data-ob-next>Настроить</button>`;
 if(i===1)body=`<div class="ob-body"><h1>Что сейчас сложнее всего?</h1><p>Выберите до трёх стартовых миссий. Остальные останутся в кабинете взрослого.</p><div class="goal-grid">${S.missions.slice(0,13).map(m=>`<button class="goal-card ${m.enabled?'on':''}" data-ob-goal="${m.id}"><b>${m.icon} ${esc(m.title)}</b><span>${m.group} · ≈ ${m.mins} мин</span></button>`).join('')}</div></div><button class="btn purple" data-ob-next>Дальше</button>`;
 if(i===2)body=`<div class="ob-body"><h1>Сколько помощи нужно сейчас?</h1><p>Это не оценка ребёнка. Просто стартовый уровень scaffolding.</p><div class="goal-grid">${[['0','🤝 Пока вместе'],['1','📋 По коротким шагам'],['2','🦸 Почти сам']].map(([n,t])=>`<button class="goal-card ${Number(S._obSupport??1)===Number(n)?'on':''}" data-ob-support="${n}"><b>${t}</b><span>${n==='0'?'Взрослый начинает рядом':n==='1'?'Ребёнок идёт по понятному чеклисту':'Обычно нужен только сигнал начать'}</span></button>`).join('')}</div></div><button class="btn purple" data-ob-next>Дальше</button>`;
 if(i===3)body=`<div class="ob-body"><h1>Последние настройки взрослого</h1><p>Имя нужно для обращений, PIN — чтобы ребёнок не менял правила.</p><div class="photo-step"><input id="obName" value="${esc(S.child.name==='Игрок'?'':S.child.name)}" placeholder="Имя ребёнка" style="width:100%;padding:14px;border:2px solid #e8eaf1;border-radius:16px"><input id="obPin" value="${S.parent.pin}" maxlength="4" inputmode="numeric" style="width:100%;padding:14px;border:2px solid #e8eaf1;border-radius:16px;margin-top:9px" placeholder="PIN"></div></div><button class="btn purple" data-ob-save>Сохранить</button>`;
 if(i===4)body=`<div class="ob-body"><div style="font-size:88px">📱➡️🧒</div><h1>Теперь передайте телефон ребёнку</h1><p>Дальше правила объяснит сам интерфейс. Взрослому не нужно проводить инструктаж.</p></div><button class="btn yellow" data-ob-next>Телефон у ребёнка</button>`;
 if(i===5)body=`<div class="ob-body"><h1>Выбери своего героя</h1><p>Кто будет жить рядом с тобой и проходить маленькие миссии?</p><div class="char-select">${Object.entries(chars).map(([id,c])=>`<button class="${S.child.character===id?'on':''}" data-character="${id}" data-ob-char><img src="${asset(c.img)}"><b>${c.name}</b></button>`).join('')}</div></div><button class="btn purple" data-ob-next>Выбрать ${chars[S.child.character].name}</button>`;
 if(i===6)body=`<div class="ob-body"><h1>Где будет жить твой герой?</h1><p>Мир будет постепенно меняться от реальных дел.</p><div class="theme-grid">${[['forest','Лес'],['space','Космос'],['ocean','Остров']].map(([id,n])=>`<button class="theme ${S.child.theme===id?'on':''}" data-theme="${id}"><i style="background-image:linear-gradient(135deg,${id==='forest'?'#72cf89,#4d885c':id==='space'?'#344582,#8b72bc':'#6ed4f4,#69cfa7'})"></i><span>${n}</span></button>`).join('')}</div></div><button class="btn purple" data-ob-next>Дальше</button>`;
 if(i===7)body=`<div class="ob-body"><h1>Добавим твой портрет?</h1><p>Он будет отдельным приватным медальоном — не лицом персонажа. Этот шаг можно пропустить.</p><div class="photo-step"><div class="photo-preview">${S.child.portrait?`<img src="${S.child.portrait}">`:'📷'}</div><div class="photo-actions"><label class="btn purple">Загрузить фото<input id="photoInput" type="file" accept="image/*" hidden></label><button class="btn ghost" data-ob-next>Пропустить / продолжить</button></div></div></div>`;
 if(i===8)body=`<div class="ob-body"><div class="ob-hero"><img src="${characterImg()}"></div><h1>Первая маленькая миссия</h1><p>Найди свой рюкзак. Не собирай его — просто найди. Так ты сразу поймёшь механику.</p></div><button class="btn yellow" data-ob-finish>Нашёл!</button>`;
 return `<div class="onboarding"><div class="ob">${progress}${body}</div></div>`;
}
function handlePhoto(file){if(!file||!file.type.startsWith('image/'))return;const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d'),sc=Math.max(256/im.width,256/im.height),w=im.width*sc,h=im.height*sc;x.drawImage(im,(256-w)/2,(256-h)/2,w,h);S.child.portrait=c.toDataURL('image/jpeg',.78);save();render()};im.src=r.result};r.readAsDataURL(file)}