function render(){
 resetDay();const a=$('#app');a.innerHTML=screenHtml();const ov=S.ui.overlay;document.body.querySelector('.overlay')?.remove();if(ov){document.body.insertAdjacentHTML('beforeend',overlayHtml(ov))}
}
function header(){
 const hp=S.child.hp||0;
 return `<div class="top"><div class="user">${portraitOrPet()}<div class="user-copy"><b>Привет, ${esc(S.child.name)}! 👋</b><span>${doneCount()?`Уже ${doneCount()} маленьких побед`:'Сегодня всё начинается с одного шага'}</span></div></div><div class="top-actions"><button class="pill">❤️ ${hp}</button><button class="round" data-parent>⚙️</button></div></div>`;
}
function home(){
 const m=nextMission(),hp=S.child.hp||0,goal=100,p=Math.min(100,hp/goal*100),night=new Date().getHours()>=21||new Date().getHours()<6,done=doneCount(),ready=done>=chestGoal()&&!S.daily.chestOpened;
 const speech=ready?'Сундук готов! Хочешь посмотреть, что внутри? ✨':m?(night?`Ещё не спишь? Готов к «${m.title}»?`:`Готов к «${m.title}»?`):'На сегодня всё. Можно отдыхать 🌿';
 return `<div class="${night?'night':''}">${header()}<section class="room"><div class="room-bg" style="--room:url('${asset('room.webp')}')"></div><div class="hpbar"><span class="heart">❤️</span><div class="track"><i style="width:${p}%"></i></div><span class="hpnum">${hp} / ${goal}</span></div><div class="note">Маленькие дела делают большой мир ♡</div><div class="speech">${esc(speech)}</div><div class="rug"></div>${hero()}${ready?`<button class="mission-banner" data-chest><span class="mission-art"><img src="${asset('chest.webp')}"></span><span class="mission-copy"><small>Награда готова</small><b>Открыть сундук дня</b></span><span class="go">›</span></button>`:m?`<button class="mission-banner" data-start="${m.id}"><span class="mission-art">${m.id==='bag'?`<img src="${asset('backpack.webp')}">`:`<span>${m.icon}</span>`}</span><span class="mission-copy"><small>Следующая миссия · ${m.hp} HP</small><b>${esc(m.title)}</b></span><span class="go">›</span></button>`:`<button class="mission-banner" data-screen="world"><span class="mission-art"><img src="${asset('plant.webp')}"></span><span class="mission-copy"><small>${done}/${active().length} сегодня</small><b>Посмотреть, как изменился мир</b></span><span class="go">›</span></button>`}</section>
 <nav class="home-nav"><button ${ready?'data-chest':'data-screen="world"'}><span class="nav-art"><img src="${asset('chest.webp')}"></span>Сокровища</button><button data-screen="family"><span class="nav-art"><span>👨‍👩‍👧</span></span>Команда</button><button data-screen="world" data-tab="wardrobe"><span class="nav-art"><img src="${asset('hat.webp')}"></span>Гардероб</button><button data-screen="world"><span class="nav-art"><span>🏡</span></span>Мой мир</button></nav></div>`;
}
function placedItems(){return S.child.collection.map(id=>{const x=items.find(i=>i.id===id);return x?`<button class="placed ${id}" data-world-item="${id}"><img src="${asset(x.img)}"></button>`:''}).join('')}
function world(){
 const tab=S.ui.worldTab||'items';
 const unlockedAcc=a=>S.child.chests>=a.need;
 return `<div class="page-head"><button class="back" data-screen="home">‹</button><div class="page-title"><b>Мой мир</b><span>Комната ${chars[S.child.character].name}</span></div><button class="round" data-parent>⚙️</button></div>
 <section class="world-scene"><div class="room-bg" style="--room:url('${asset('room.webp')}')"></div><div class="rug"></div>${placedItems()}${hero()}<div class="world-actions"><button data-worldtab="wardrobe"><b>👕</b>Гардероб</button><button data-worldtab="items"><b>⭐</b>Коллекция</button><button data-worldtab="characters"><b>🐾</b>Герои</button></div></section>
 <section class="drawer"><div class="segments"><button class="${tab==='items'?'on':''}" data-worldtab="items">Предметы</button><button class="${tab==='wardrobe'?'on':''}" data-worldtab="wardrobe">Гардероб</button><button class="${tab==='characters'?'on':''}" data-worldtab="characters">Персонажи</button></div>${tab==='items'?`<div class="item-grid">${items.map(x=>`<button class="item ${S.child.collection.includes(x.id)?'':'locked'}"><img src="${asset(x.img)}"><b>${x.name}</b>${!S.child.collection.includes(x.id)?'<span class="lock">🔒</span>':''}</button>`).join('')}</div>`:tab==='wardrobe'?`<div class="item-grid">${accessories.map(x=>`<button class="item ${unlockedAcc(x)?'':'locked'} ${S.child.accessory===x.id?'selected':''}" data-accessory="${x.id}" ${unlockedAcc(x)?'':'disabled'}>${x.img?`<img src="${asset(x.img)}">`:'<div style="height:58px;display:grid;place-items:center;font-size:26px">✨</div>'}<b>${x.name}</b>${!unlockedAcc(x)?`<span class="lock">${x.need} 🎁</span>`:''}</button>`).join('')}</div>`:`<div class="char-grid">${Object.entries(chars).map(([id,c])=>`<button class="char ${S.child.character===id?'on':''}" data-character="${id}"><img src="${asset(c.img)}"><b>${c.name}</b></button>`).join('')}</div>`}</section>`;
}
function family(){
 const total=totalFamily(),goal=S.family.goal,pct=Math.min(100,total/goal*100),left=Math.max(0,S.family.bossMax-total),bp=Math.max(0,100-left/S.family.bossMax*100);
 return `<div class="page-head"><button class="back" data-screen="home">‹</button><div class="page-title"><b>Наша команда</b><span>Вместе мы делаем больше</span></div><button class="round" data-parent>⚙️</button></div>
 <section class="family-hero"><div style="font-size:10px;font-weight:1000;letter-spacing:.14em;color:#bcd0ef">MOKI FAMILY · HP</div><h1>${esc(S.family.name)}</h1><p>У каждого свои реальные дела. Сравниваем не «кто лучше», а движение к своей цели.</p><div class="family-score">${total} HP <small>из ${goal}</small></div><div class="family-track"><i style="width:${pct}%"></i></div><div class="members">${S.family.members.slice(0,4).map(m=>memberHtml(m)).join('')}</div></section>
 <section class="family-card"><div class="boss"><div class="boss-art">${asset('boss.png')?`<img src="${asset('boss.png')}">`:'👾'}</div><div class="boss-copy"><b>${left?'Монстр Хаоса':'Монстр побеждён!'}</b><p>${left?'Каждое полезное дело всей команды отнимает ему HP.':'Команда справилась вместе. Новый раунд можно запустить из режима взрослого.'}</p><div class="track"><i style="width:${bp}%"></i></div><div style="font-size:9px;font-weight:900;margin-top:5px">${left} HP осталось</div></div></div><div class="boss-actions"><button data-nudge>⚡ Подначить</button><button data-challenge>⚔️ Вызов</button></div></section>
 <section class="family-card"><b style="font-size:14px">Последние действия</b>${S.family.feed.length?S.family.feed.slice(0,6).map(feedHtml).join(''):`<div class="feed"><div class="feed-ava">🌱</div><div class="feed-copy"><b>Пока тихо</b><span>Первое полезное дело сразу появится здесь.</span></div></div>`}</section>`;
}
function memberHtml(m){const is=m.id==='child';return `<div class="member"><div class="member-pic ${is&&!S.child.portrait?'pet':''}">${is?(S.child.portrait&&S.child.portraitFamily?`<img src="${S.child.portrait}">`:`<img src="${characterImg()}">`):`<span style="font-size:27px">${m.avatar||'👤'}</span>`}</div><b>${esc(is?S.child.name:m.name)}</b><span>${m.earned||0} HP</span></div>`}
function feedHtml(f){const m=S.family.members.find(x=>x.id===f.memberId),is=f.memberId==='child';return `<div class="feed"><div class="feed-ava">${is?`<img src="${S.child.portrait&&S.child.portraitFamily?S.child.portrait:characterImg()}">`:`<span>${m?.avatar||'👤'}</span>`}</div><div class="feed-copy"><b>${esc(is?S.child.name:m?.name||'Участник')} · ${esc(f.category)}</b><span>${esc(f.text)}</span></div><div class="feed-hp">+${f.hp||0} HP</div></div>`}
function metrics(){
 const h=S.history.filter(x=>x.type==='mission'),solo=h.filter(x=>x.support==='solo').length,hint=h.filter(x=>x.support==='hint').length,together=h.filter(x=>x.support==='together').length;return {solo,hint,together,total:h.length}
}
function parent(){
 const tab=S.ui.parentTab||'today',m=metrics(),a=active(),d=doneCount(),pct=a.length?Math.round(d/a.length*100):0;
 return `<div class="page-head"><button class="back" data-screen="home">‹</button><div class="page-title"><b>Родительский режим</b><span>${esc(S.child.name)} · самостоятельность</span></div><button class="round">⚙️</button></div><nav class="parent-tabs">${[['today','Сегодня'],['missions','Миссии'],['skills','Навыки'],['family','Семья'],['profile','Персонаж']].map(([id,n])=>`<button class="${tab===id?'on':''}" data-parenttab="${id}">${n}</button>`).join('')}</nav>${tab==='today'?parentToday(m,a,d,pct):tab==='missions'?parentMissions():tab==='skills'?parentSkills(m):tab==='family'?parentFamily():parentProfile()}`;
}
function parentToday(m,a,d,pct){return `<section class="panel"><div class="insight-top"><div><h2>Сегодня</h2><p>${d} из ${a.length} активных миссий. Смотрите прежде всего на объём помощи, а не на «послушание».</p></div><div class="ring" style="--p:${pct}%"><b>${pct}%</b></div></div></section><div class="stats"><div class="stat"><b>${m.solo}</b><span>без подсказок</span></div><div class="stat"><b>${m.hint}</b><span>с подсказкой</span></div><div class="stat"><b>${m.together}</b><span>вместе</span></div></div><section class="panel" style="margin-top:10px"><h2>Следующее решение</h2><p>${recommendation()}</p></section>`}
function recommendation(){const bag=S.history.filter(x=>x.missionId==='bag').slice(-5),solo=bag.filter(x=>x.support==='solo').length;if(bag.length>=4&&solo>=3)return 'Рюкзак уже несколько раз получился без подсказки. Попробуйте завтра скрыть подробный чеклист.';return 'Пока сохраняйте текущий объём поддержки. Когда ребёнок 3–4 раза справится без подсказки, MOKI предложит убрать одну опору.'}
function parentMissions(){return `<section class="panel"><h2>Дневной маршрут</h2><p>Можно включить много дел: ребёнок всё равно видит только одну следующую миссию.</p>${S.missions.map(m=>`<div class="mrow"><span class="mi">${m.icon}</span><span class="mc"><b>${esc(m.title)}</b><span>${m.group} · ${m.hp} HP · ${['Вместе','По шагам','Почти сам'][m.support]}</span></span><button class="toggle ${m.enabled?'on':''}" data-toggle="${m.id}"></button></div>`).join('')}</section>`}
function parentSkills(m){return `<section class="panel"><h2>Навыки самостоятельности</h2><p>Scaffolding → fading → mastery. Уменьшаем помощь только после устойчивого успеха.</p>${['Утро','Школа','Дом','Вечер'].map(g=>{const ms=S.missions.filter(x=>x.group===g||x.group.includes(g)),h=S.history.filter(x=>ms.some(q=>q.id===x.missionId)),solo=h.filter(x=>x.support==='solo').length,p=h.length?Math.min(100,Math.round(solo/h.length*100)):0;return `<div class="mrow"><span class="mi">${g==='Школа'?'🎒':g==='Дом'?'🏡':g==='Вечер'?'🌙':'☀️'}</span><span class="mc"><b>${g}</b><span>${h.length?`${p}% последних выполнений без внешней помощи`:'Нужны первые повторения'}</span><div class="track" style="margin-top:6px"><i style="width:${p}%"></i></div></span></div>`}).join('')}</section>`}
function parentFamily(){return `<section class="panel"><h2>Семейная игра</h2><p>Взрослые тоже должны вносить реальный вклад — иначе социальная механика теряет смысл.</p>${S.family.members.filter(x=>x.role!=='child').map(m=>`<div class="mrow"><span class="mi">${m.avatar||'👤'}</span><span class="mc"><b>${esc(m.name)}</b><span>${m.earned||0} HP</span></span><button class="btn ghost" data-adult-hp="${m.id}" data-hp="5">+5 HP</button></div>`).join('')}</section>`}
function parentProfile(){return `<section class="panel"><h2>Портрет ребёнка</h2><p>Фото — приватный медальон. Оно не заменяет лицо персонажа и не показывается друзьям.</p><div class="photo-preview">${S.child.portrait?`<img src="${S.child.portrait}">`:'📷'}</div><div class="photo-actions"><label class="btn purple" style="text-align:center">Загрузить / заменить<input id="photoInput" type="file" accept="image/*" hidden></label>${S.child.portrait?`<button class="btn ghost" data-photo-family>${S.child.portraitFamily?'Не показывать семье':'Показывать только семье'}</button><button class="btn ghost" data-photo-remove>Удалить фото</button>`:''}</div></section><section class="panel"><h2>Персонаж</h2><p>${chars[S.child.character].name} · ${chars[S.child.character].desc}</p><button class="btn purple" data-screen="world" data-tab="characters">Открыть выбор героя</button></section>`}
function screenHtml(){if(!S.onboarded)return onboardingHtml();return S.ui.screen==='family'?family():S.ui.screen==='world'?world():S.ui.screen==='parent'?parent():home()}